<?php

if(function_exists("register_field_group"))
{
	register_field_group(array (
		'id' => 'acf_archive-content',
		'title' => 'Archive Content',
		'fields' => array (
			array (
				'key' => 'field_qxr6jseoardss6',
				'label' => __('Archive Grid'),
				'name' => 'archive_grid',
				'type' => 'repeater',
				'sub_fields' => array (
					array (
						'key' => 'field_35x3wyn7wrdnw1',
						'label' => __('Unit Span'),
						'name' => 'unit_span',
						'type' => 'select',
						'column_width' => '',
						'choices' => array (
							'one-of-one' => 'One of one',
							'one-of-two' => 'One of two',
							'one-of-three' => 'One of three',
							'one-of-four' => 'One of four',
							'one-of-five' => 'One of five',
							'two-of-three' => 'Two of three',
							'two-of-five' => 'Two of five',
							'three-of-four' => 'Three of four',
							'three-of-five' => 'Three of five',
							'four-of-five' => 'Four of five',
						),
						'default_value' => 'one-of-one',
						'allow_null' => 0,
						'multiple' => 0,
					),
					array (
						'key' => 'field_ezmltlwwjnukmy',
						'label' => __('Unit'),
						'name' => 'unit',
						'type' => 'repeater',
						'sub_fields' => array (
							array (
								'key' => 'field_bd7ekjqlmlrlq2',
								'label' => __('Nested Unit Span'),
								'name' => 'nested_unit_span',
								'type' => 'select',
								'column_width' => '',
								'choices' => array (
									'one-of-one' => 'Nested -- One of one',
									'one-of-two' => 'Nested -- One of two',
									'one-of-three' => 'Nested -- One of three',
									'one-of-four' => 'Nested -- One of four',
									'one-of-five' => 'Nested -- One of five',
									'two-of-three' => 'Nested -- Two of three',
									'two-of-five' => 'Nested -- Two of five',
									'three-of-four' => 'Nested -- Three of four',
									'three-of-five' => 'Nested -- Three of five',
									'four-of-five' => 'Nested -- Four of five',
								),
								'default_value' => 'one-of-one',
								'allow_null' => 0,
								'multiple' => 0,
							),
							array (
								'key' => 'field_3yjai0r3rnmjfs',
								'label' => __('Nested Unit'),
								'name' => 'nested_unit',
								'type' => 'flexible_content',
								'column_width' => '',
								'layouts' => array (
									array (
										'label' => __('Accordion editor'),
										'name' => 'accordion_editor',
										'display' => 'row',
										'min' => '',
										'max' => '',
										'sub_fields' => array (
											array (
												'key' => 'field_nvtq4qbkxsqs9k',
												'label' => __('Heading type'),
												'name' => 'heading_type',
												'type' => 'select',
												'column_width' => '',
												'choices' => array (
													'heading_1' => 'Heading 1',
													'heading_2' => 'Heading 2',
													'heading_3' => 'Heading 3',
													'heading_4' => 'Heading 4',
													'paragraph_text' => 'Paragraph text',
												),
												'default_value' => 'paragraph_text',
												'allow_null' => 0,
												'multiple' => 0,
											),
											array (
												'key' => 'field_jeyq1ysqb84829',
												'label' => __('Accordions'),
												'name' => 'accordion',
												'type' => 'repeater',
												'column_width' => '',
												'sub_fields' => array (
													array (
														'key' => 'field_14tflcxwtv7wni',
														'label' => __('Heading'),
														'name' => 'heading',
														'type' => 'text',
														'column_width' => '',
														'default_value' => '',
														'placeholder' => '',
														'prepend' => '',
														'append' => '',
														'formatting' => 'html',
														'maxlength' => '',
													),
													array (
														'key' => 'field_3q83i68ju7jfif',
														'label' => __('Editor'),
														'name' => 'editor',
														'type' => 'wysiwyg',
														'column_width' => '',
														'default_value' => '',
														'toolbar' => 'full',
														'media_upload' => 'yes',
													),
												),
												'row_min' => '',
												'row_limit' => '',
												'layout' => 'row',
												'button_label' => 'Add an Accordion',
											),
										),
									),
									array (
										'label' => __('Accordion button'),
										'name' => 'accordion_button',
										'display' => 'row',
										'min' => '',
										'max' => '',
										'sub_fields' => array (
											array (
												'key' => 'field_ovpsm4gt4wya4o',
												'label' => __('Button text'),
												'name' => 'button_text',
												'type' => 'text',
												'column_width' => '',
												'default_value' => '',
												'placeholder' => '',
												'prepend' => '',
												'append' => '',
												'formatting' => 'html',
												'maxlength' => '',
											),
											array (
												'key' => 'field_vl5k7lys4wpefl',
												'label' => __('Editor'),
												'name' => 'editor',
												'type' => 'text',
												'column_width' => '',
												'default_value' => '',
												'placeholder' => '',
												'prepend' => '',
												'append' => '',
												'formatting' => 'html',
												'maxlength' => '',
											),
										),
									),
									array (
										'label' => __('Accordion links'),
										'name' => 'accordion_links',
										'display' => 'row',
										'min' => '',
										'max' => '',
										'sub_fields' => array (
											array (
												'key' => 'field_t80stcpiwfaesh',
												'label' => __('Heading type'),
												'name' => 'heading_type',
												'type' => 'select',
												'column_width' => '',
												'choices' => array (
													'heading_1' => 'Heading 1',
													'heading_2' => 'Heading 2',
													'heading_3' => 'Heading 3',
													'heading_4' => 'Heading 4',
													'paragraph_text' => 'Paragraph text',
												),
												'default_value' => 'paragraph_text',
												'allow_null' => 0,
												'multiple' => 0,
											),
											array (
												'key' => 'field_3yruqg5ghciww1',
												'label' => __('Accordions'),
												'name' => 'accordion',
												'type' => 'repeater',
												'column_width' => '',
												'sub_fields' => array (
													array (
														'key' => 'field_e1pxsgc79pg0ry',
														'label' => __('Heading'),
														'name' => 'heading',
														'type' => 'text',
														'column_width' => 3,
														'default_value' => '',
														'placeholder' => '',
														'prepend' => '',
														'append' => '',
														'formatting' => 'html',
														'maxlength' => '',
													),
													array (
														'key' => 'field_lnb3yza4cruzi9',
														'label' => __('Links'),
														'name' => 'links',
														'type' => 'repeater',
														'column_width' => '',
														'sub_fields' => array (
															array (
																'key' => 'field_xndr1qepc7j97l',
																'label' => __('Text'),
																'name' => 'text',
																'type' => 'text',
																'column_width' => '',
																'default_value' => '',
																'placeholder' => '',
																'prepend' => '',
																'append' => '',
																'formatting' => 'html',
																'maxlength' => '',
															),
															array (
																'key' => 'field_4w50s9zvwg0usj',
																'label' => __('Text 2'),
																'name' => 'text_2',
																'type' => 'text',
																'column_width' => '',
																'default_value' => '',
																'placeholder' => '',
																'prepend' => '',
																'append' => '',
																'formatting' => 'html',
																'maxlength' => '',
															),
															array (
																'key' => 'field_4aiwod1qdszdja',
																'label' => __('Text 2 type'),
																'name' => 'text_2_type',
																'type' => 'select',
																'instructions' => __('Choose type for text 2'),
																'column_width' => '',
																'choices' => array (
																	'text' => 'Text',
																	'class' => 'Class',
																	'url' => 'URL',
																),
																'default_value' => '',
																'allow_null' => 1,
																'multiple' => 0,
															),
														),
														'row_min' => '',
														'row_limit' => '',
														'layout' => 'row',
														'button_label' => 'Add a link',
													),
												),
												'row_min' => '',
												'row_limit' => '',
												'layout' => 'row',
												'button_label' => 'Add an Accordion',
											),
										),
									),
									array (
										'label' => __('Archive'),
										'name' => 'archive',
										'display' => 'row',
										'min' => '',
										'max' => '',
										'sub_fields' => array (
											array (
												'key' => 'field_adfas456b3b',
												'label' => __('Post Type'),
												'name' => 'post_type',
												'type' => 'text',
												'column_width' => '',
												'choices' => 'conservation-news',
												'default_value' => '',
												'placeholder' => '',
												'prepend' => '',
												'append' => '',
												'formatting' => 'html',
												'maxlength' => '',
											),
											array (
												'key' => 'field_psidud546c',
												'label' => __('Post Per Page'),
												'name' => 'post_per_page',
												'type' => 'number',
												'instructions' => __(''),
												'column_width' => 15,
												'default_value' => 10,
												'placeholder' => '',
												'prepend' => '',
												'append' => '',
												'min' => -1,
												'max' => '',
												'step' => '',
											),
											array (
												'key' => 'field_bd7ekjqdsfdmlrlq2',
												'label' => __('Archive Unit Span'),
												'name' => 'archive_unit_span',
												'type' => 'select',
												'column_width' => '',
												'choices' => array (
													'one-of-one' => 'One of one',
													'one-of-two' => 'One of two',
													'one-of-three' => 'One of three',
													'one-of-four' => 'One of four',
													'one-of-five' => 'One of five',
													'two-of-three' => 'Two of three',
													'two-of-five' => 'Two of five',
													'three-of-four' => 'Three of four',
													'three-of-five' => 'Three of five',
													'four-of-five' => 'Four of five',
												),
												'default_value' => 'one-of-one',
												'allow_null' => 0,
												'multiple' => 0,
											),
											array (
												'key' => 'field_5qpwsdonsds10',
												'label' => __('Filter by'),
												'name' => 'filter_by',
												'type' => 'select',
												'column_width' => '',
												'choices' => array (
													'category' => 'Category',
													'month' => 'Month',
													'start_date' => 'Start date',
													'published_date' => 'Published date',
													'last_name' => 'Last Name',
													'title' => 'Title',
												),
												'default_value' => 'title',
												'allow_null' => 0,
												'multiple' => 0,
											),
											array (
												'key' => 'field_5qpwsdons10',
												'label' => __('Elements to Display'),
												'name' => 'elements',
												'type' => 'repeater',
												'column_width' => '',
												'sub_fields' => array (
													array (
														'key' => 'field_df09ushkwse3',
														'label' => __('Element'),
														'name' => 'element',
														'type' => 'select',
														'column_width' => '',
														'choices' => array (
															'byline' => 'Byline',
															'dates' => 'Dates',
															'days' => 'Days',
															'email' => 'Email',
															'excerpt' => 'Excerpt',
															'full_name' => 'Full name',
															// 'relationship' => 'Relationship',
															'main_image' => 'Main image',
															'vimeo' => 'Vimeo',
															'youtube' => 'Youtube',
														),
														'default_value' => 'main_image',
														'allow_null' => 0,
														'multiple' => 0,
													),
													array (
														'key' => 'field_df0sdfaswse3',
														'label' => __('Unit span'),
														'name' => 'unit-span',
														'type' => 'select',
														'column_width' => '',
														'choices' => array (
															'one-of-one' => 'One of one',
															'one-of-two' => 'One of two',
															'one-of-three' => 'One of three',
															'one-of-four' => 'One of four',
															'one-of-five' => 'One of five',
															'two-of-three' => 'Two of three',
															'two-of-five' => 'Two of five',
															'three-of-four' => 'Three of four',
															'three-of-five' => 'Three of five',
															'four-of-five' => 'Four of five',
														),
														'default_value' => 'one-of-one',
														'allow_null' => 0,
														'multiple' => 0,
													),
												),
											'button_label' => 'Add another Element',
											),
										),
									),
									array (
										'label' => __('Blockquote'),
										'name' => 'blockquote',
										'display' => 'row',
										'min' => '',
										'max' => '',
										'sub_fields' => array (
											array (
												'key' => 'field_o3mtp9f43yw71p',
												'label' => __('Quote'),
												'name' => 'quote',
												'type' => 'text',
												'column_width' => '',
												'default_value' => '',
												'placeholder' => '',
												'prepend' => '',
												'append' => '',
												'formatting' => 'html',
												'maxlength' => '',
											),
											array (
												'key' => 'field_ik8p26ory1ljxk',
												'label' => __('Credit line 1'),
												'name' => 'credit_line_1',
												'type' => 'text',
												'column_width' => '',
												'default_value' => '',
												'placeholder' => '',
												'prepend' => '',
												'append' => '',
												'formatting' => 'html',
												'maxlength' => '',
											),
											array (
												'key' => 'field_scmdlm9iythdgk',
												'label' => __('Credit line 2'),
												'name' => 'credit_line_2',
												'type' => 'text',
												'column_width' => '',
												'default_value' => '',
												'placeholder' => '',
												'prepend' => '',
												'append' => '',
												'formatting' => 'html',
												'maxlength' => '',
											),
											array (
												'key' => 'field_t0dsr6etzt33dt',
												'label' => __('Credit line 2 type'),
												'name' => 'credit_line_2_type',
												'type' => 'select',
												'column_width' => '',
												'choices' => array (
													'text' => 'Text',
													'class' => 'Class',
													'url' => 'URL',
												),
												'default_value' => '',
												'allow_null' => 0,
												'multiple' => 0,
											),
											array (
												'key' => 'field_7t5738fbapea8u',
												'label' => __('New window'),
												'name' => 'new_window',
												'type' => 'true_false',
												'column_width' => '',
												'message' => '',
												'default_value' => 0,
											),
										),
									),
									array (
										'label' => __('Blockquote rotator'),
										'name' => 'blockquote_rotator',
										'display' => 'row',
										'min' => '',
										'max' => '',
										'sub_fields' => array (
											array (
												'key' => 'field_3mzeg7smctqo40',
												'label' => __('Quotes'),
												'name' => 'quotes',
												'type' => 'repeater',
												'column_width' => '',
												'sub_fields' => array (
													array (
														'key' => 'field_7eixev1s837zcv',
														'label' => __('Quote'),
														'name' => 'quote',
														'type' => 'text',
														'column_width' => '',
														'default_value' => '',
														'placeholder' => '',
														'prepend' => '',
														'append' => '',
														'formatting' => 'html',
														'maxlength' => '',
													),
													array (
														'key' => 'field_wvldxugrmtpui1',
														'label' => __('Credit line 1'),
														'name' => 'credit_line_1',
														'type' => 'text',
														'column_width' => '',
														'default_value' => '',
														'placeholder' => '',
														'prepend' => '',
														'append' => '',
														'formatting' => 'html',
														'maxlength' => '',
													),
													array (
														'key' => 'field_wq6uq7op6x49of',
														'label' => __('Credit line 2'),
														'name' => 'credit_line_2',
														'type' => 'text',
														'column_width' => '',
														'default_value' => '',
														'placeholder' => '',
														'prepend' => '',
														'append' => '',
														'formatting' => 'html',
														'maxlength' => '',
													),
													array (
														'key' => 'field_rya0wh6tqvto1r',
														'label' => __('Credit line 2 type'),
														'name' => 'credit_line_2_type',
														'type' => 'select',
														'column_width' => '',
														'choices' => array (
															'text' => 'Text',
															'class' => 'Class',
															'url' => 'URL',
														),
														'default_value' => '',
														'allow_null' => 0,
														'multiple' => 0,
													),
													array (
														'key' => 'field_26m66ti9vlu925',
														'label' => __('New window'),
														'name' => 'new_window',
														'type' => 'true_false',
														'column_width' => '',
														'message' => '',
														'default_value' => 0,
													),
												),
												'row_min' => '',
												'row_limit' => '',
												'layout' => 'row',
												'button_label' => 'Add a Quote',
											),
										),
									),
									array (
										'label' => __('Button link'),
										'name' => 'button_link',
										'display' => 'row',
										'min' => '',
										'max' => '',
										'sub_fields' => array (
											array (
												'key' => 'field_gsfzluwubr32j8',
												'label' => __('Text'),
												'name' => 'text',
												'type' => 'text',
												'column_width' => '',
												'default_value' => '',
												'placeholder' => '',
												'prepend' => '',
												'append' => '',
												'formatting' => 'html',
												'maxlength' => '',
											),
											array (
												'key' => 'field_oi9q8wl0wrf4bk',
												'label' => __('Link'),
												'name' => 'link',
												'type' => 'text',
												'column_width' => '',
												'default_value' => '',
												'placeholder' => '',
												'prepend' => '',
												'append' => '',
												'formatting' => 'html',
												'maxlength' => '',
											),
											array (
												'key' => 'field_rxe3i4w6o5keks',
												'label' => __('New window'),
												'name' => 'new_window',
												'type' => 'true_false',
												'column_width' => '',
												'message' => '',
												'default_value' => 0,
											),
										),
									),
									array (
										'label' => __('Editor'),
										'name' => 'editor',
										'display' => 'row',
										'min' => '',
										'max' => '',
										'sub_fields' => array (
											array (
												'key' => 'field_vcadob0nlad8uo',
												'label' => __('Editors'),
												'name' => 'editor',
												'type' => 'repeater',
												'column_width' => '',
												'sub_fields' => array (
													array (
														'key' => 'field_ef4aa2h38f6e4k',
														'label' => __('Editor'),
														'name' => 'editor',
														'type' => 'wysiwyg',
														'column_width' => '',
														'default_value' => '',
														'toolbar' => 'full',
														'media_upload' => 'yes',
													),
												),
												'row_min' => '',
												'row_limit' => '',
												'layout' => 'row',
												'button_label' => 'Add an Editor',
											),
										),
									),
									array (
										'label' => __('Heading'),
										'name' => 'heading',
										'display' => 'row',
										'min' => '',
										'max' => '',
										'sub_fields' => array (
											array (
												'key' => 'field_50cbbn2qi7itum',
												'label' => __('Heading'),
												'name' => 'heading',
												'type' => 'text',
												'column_width' => '',
												'default_value' => '',
												'placeholder' => '',
												'prepend' => '',
												'append' => '',
												'formatting' => 'html',
												'maxlength' => '',
											),
											array (
												'key' => 'field_zhm78sawnc4dad',
												'label' => __('Heading type'),
												'name' => 'heading_type',
												'type' => 'select',
												'column_width' => '',
												'choices' => array (
													'heading_1' => 'Heading 1',
													'heading_2' => 'Heading 2',
													'heading_3' => 'Heading 3',
													'heading_4' => 'Heading 4',
												),
												'default_value' => 'heading_2',
												'allow_null' => 0,
												'multiple' => 0,
											),
											array (
												'key' => 'field_48p9bjuuawk0cl',
												'label' => __('Link'),
												'name' => 'link',
												'type' => 'text',
												'column_width' => '',
												'default_value' => '',
												'placeholder' => '',
												'prepend' => '',
												'append' => '',
												'formatting' => 'html',
												'maxlength' => '',
											),
											array (
												'key' => 'field_qu25lrf1hior48',
												'label' => __('New window'),
												'name' => 'new_window',
												'type' => 'true_false',
												'column_width' => '',
												'message' => '',
												'default_value' => 0,
											),
										),
									),
									array (
										'label' => __('Image'),
										'name' => 'image',
										'display' => 'row',
										'min' => '',
										'max' => '',
										'sub_fields' => array (
											array (
												'key' => 'field_r9vjevhi6j4iia',
												'label' => __('Image'),
												'name' => 'image',
												'type' => 'image',
												'column_width' => '',
												'default_value' => '',
												'placeholder' => '',
												'prepend' => '',
												'append' => '',
												'formatting' => 'html',
												'maxlength' => '',
											),
											array (
												'key' => 'field_elxlzj24ktlv9s',
												'label' => __('Image link'),
												'name' => 'image_link',
												'type' => 'text',
												'column_width' => '',
												'default_value' => '',
												'placeholder' => '',
												'prepend' => '',
												'append' => '',
												'formatting' => 'html',
												'maxlength' => '',
											),
											array (
												'key' => 'field_bzp4sup7wihhe9',
												'label' => __('New window'),
												'name' => 'new_window',
												'type' => 'true_false',
												'column_width' => '',
												'message' => '',
												'default_value' => 0,
											),
										),
									),
									array (
										'label' => __('Image carousel'),
										'name' => 'image_carousel',
										'display' => 'row',
										'min' => '',
										'max' => '',
										'sub_fields' => array (
											array (
												'key' => 'field_b3i767b3yfa3y5',
												'label' => __('Images'),
												'name' => 'images',
												'type' => 'gallery',
												'column_width' => '',
												'preview_size' => 'thumbnail',
												'library' => 'all',
											),
										),
									),
									array (
										'label' => __('Image gallery'),
										'name' => 'image_gallery',
										'display' => 'row',
										'min' => '',
										'max' => '',
										'sub_fields' => array (
											array (
												'key' => 'field_54v8nksze0ec8j',
												'label' => __('Images'),
												'name' => 'images',
												'type' => 'gallery',
												'column_width' => '',
												'preview_size' => 'thumbnail',
												'library' => 'all',
											),
										),
									),
									array (
										'label' => __('Image rotator'),
										'name' => 'image_rotator',
										'display' => 'row',
										'min' => '',
										'max' => '',
										'sub_fields' => array (
											array (
												'key' => 'field_v5zbkj5mbdq3ad',
												'label' => __('Images'),
												'name' => 'images',
												'type' => 'gallery',
												'column_width' => '',
												'preview_size' => 'thumbnail',
												'library' => 'all',
											),
										),
									),
									array (
										'label' => __('Image with hover'),
										'name' => 'image_with_hover',
										'display' => 'row',
										'min' => '',
										'max' => '',
										'sub_fields' => array (
											array (
												'key' => 'field_ipsbpprbwxfx95',
												'label' => __('Image'),
												'name' => 'image',
												'type' => 'image',
												'column_width' => '',
												'save_format' => 'object',
												'preview_size' => 'thumbnail',
												'library' => 'all',
											),
											array (
												'key' => 'field_iiyas0k1jtcdhw',
												'label' => __('Hover image'),
												'name' => 'hover_image',
												'type' => 'image',
												'column_width' => '',
												'save_format' => 'object',
												'preview_size' => 'thumbnail',
												'library' => 'all',
											),
											array (
												'key' => 'field_zb3jrfwwu3p8gt',
												'label' => __('Link'),
												'name' => 'link',
												'type' => 'text',
												'column_width' => '',
												'default_value' => '',
												'placeholder' => '',
												'prepend' => '',
												'append' => '',
												'formatting' => 'html',
												'maxlength' => '',
											),
											array (
												'key' => 'field_jvsy0suq2uh4zw',
												'label' => __('New Window'),
												'name' => 'new_window',
												'type' => 'true_false',
												'column_width' => '',
												'message' => '',
												'default_value' => 0,
											),
										),
									),
									array (
										'label' => __('Main image'),
										'name' => 'main_image',
										'display' => 'row',
										'min' => '',
										'max' => '',
										'sub_fields' => array (
											array (
												'key' => 'field_b6li42nze9fgcm',
												'label' => __('Image'),
												'name' => 'image',
												'type' => 'image',
												'column_width' => '',
												'save_format' => 'object',
												'preview_size' => 'thumbnail',
												'library' => 'all',
											),
										),
									),
									array (
										'label' => __('Map'),
										'name' => 'map',
										'display' => 'row',
										'min' => '',
										'max' => '',
										'sub_fields' => array (
											array (
												'key' => 'field_cbms80doj6c93h',
												'label' => __('Map'),
												'name' => 'map',
												'type' => 'google_map',
												'column_width' => '',
												'center_lat' => '',
												'center_lng' => '',
												'height' => '',
											),
											array (
												'key' => 'field_v3ws12hsdx6iwh',
												'label' => __('Map height'),
												'name' => 'map_height',
												'type' => 'number',
												'instructions' => __('Please enter the map height'),
												'column_width' => 15,
												'default_value' => 300,
												'placeholder' => '',
												'prepend' => '',
												'append' => 'px',
												'min' => 50,
												'max' => '',
												'step' => '',
											),
											array (
												'key' => 'field_42prohsdli77n8',
												'label' => __('Style ID'),
												'name' => 'style_id',
												'type' => 'text',
												'instructions' => __('This is the ID of the map style you desire an ID can be retrieved from http://maps.cloudmade.com/editor'),
												'column_width' => '',
												'default_value' => 1714,
												'placeholder' => '',
												'prepend' => '',
												'append' => '',
												'formatting' => 'html',
												'maxlength' => '',
											),
											array (
												'key' => 'field_si3hjfizlaz3fd',
												'label' => __('Zoom level'),
												'name' => 'zoom_level',
												'type' => 'number',
												'column_width' => '',
												'default_value' => 3,
												'placeholder' => '',
												'prepend' => '',
												'append' => '',
												'min' => 0,
												'max' => 18,
												'step' => '',
											),
											array (
												'key' => 'field_s24pasdf4fqjhk',
												'label' => __('Markers'),
												'name' => 'markers',
												'type' => 'repeater',
												'column_width' => '',
												'sub_fields' => array (
													array (
														'key' => 'field_t8yt5qzz1bui78',
														'label' => __('Location'),
														'name' => 'location',
														'type' => 'google_map',
														'column_width' => '',
														'center_lat' => '',
														'center_lng' => '',
														'height' => '',
													),
													array (
														'key' => 'field_nxsv9asardhdy2',
														'label' => __('Image'),
														'name' => 'image',
														'type' => 'image',
														'instructions' => __('Add caption and text to image view on maker'),
														'column_width' => '',
														'save_format' => 'object',
														'preview_size' => 'thumbnail',
														'library' => 'all',
													),
												),
												'row_min' => '',
												'row_limit' => '',
												'layout' => 'row',
												'button_label' => 'Add a Map Marker',
											),
										),
									),
									array (
										'label' => __('PDF link'),
										'name' => 'pdf_link',
										'display' => 'row',
										'min' => '',
										'max' => '',
										'sub_fields' => array (
											array (
												'key' => 'field_8uj1aounza5lbz',
												'label' => __('Text'),
												'name' => 'text',
												'type' => 'text',
												'column_width' => '',
												'default_value' => '',
												'placeholder' => '',
												'prepend' => '',
												'append' => '',
												'formatting' => 'html',
												'maxlength' => '',
											),
											array (
												'key' => 'field_v0a54vja006ip6',
												'label' => __('Text type'),
												'name' => 'text_type',
												'type' => 'select',
												'column_width' => '',
												'choices' => array (
													'heading_1' => 'Heading 1',
													'heading_2' => 'Heading 2',
													'heading_3' => 'Heading 3',
													'heading_4' => 'Heading 4',
													'paragraph_text' => 'Paragraph text',
												),
												'default_value' => 'paragraph_text',
												'allow_null' => 0,
												'multiple' => 0,
											),
											array (
												'key' => 'field_byfxk0m2nnyg4o',
												'label' => __('PDF'),
												'name' => 'pdf',
												'type' => 'file',
												'column_width' => '',
												'save_format' => 'object',
												'library' => 'all',
											),
											array (
												'key' => 'field_r4txc9e0u4t3ko',
												'label' => __('New window'),
												'name' => 'new_window',
												'type' => 'true_false',
												'column_width' => '',
												'message' => '',
												'default_value' => 0,
											),
										),
									),
									array (
										'label' => __('Sub menu'),
										'name' => 'sub_menu',
										'display' => 'row',
										'min' => '',
										'max' => '',
										'sub_fields' => array (
											array (
												'key' => 'field_2xndakush8k1kq',
												'label' => __('Primary header menu'),
												'name' => 'primary_header_menu',
												'type' => 'true_false',
												'column_width' => '',
												'message' => '',
												'default_value' => 1,
											),
											array (
												'key' => 'field_nkehcamubdanlq',
												'label' => __('Custom theme menu location'),
												'name' => 'custom_theme_menu_location',
												'type' => 'text',
												'column_width' => '',
											),
										),
									),
									array (
										'label' => __('Text link'),
										'name' => 'text_link',
										'display' => 'row',
										'min' => '',
										'max' => '',
										'sub_fields' => array (
											array (
												'key' => 'field_bsx6pq9va5zmoe',
												'label' => __('Text links'),
												'name' => 'text_link',
												'type' => 'repeater',
												'column_width' => '',
												'sub_fields' => array (
													array (
														'key' => 'field_cfm0w5sowdkuar',
														'label' => __('Text'),
														'name' => 'text',
														'type' => 'text',
														'column_width' => '',
														'default_value' => '',
														'placeholder' => '',
														'prepend' => '',
														'append' => '',
														'formatting' => 'html',
														'maxlength' => '',
													),
													array (
														'key' => 'field_m2zhtzusfs7ixs',
														'label' => __('Link'),
														'name' => 'link',
														'type' => 'text',
														'column_width' => '',
														'default_value' => '',
														'placeholder' => '',
														'prepend' => '',
														'append' => '',
														'formatting' => 'html',
														'maxlength' => '',
													),
													array (
														'key' => 'field_a0bm5466yd74zh',
														'label' => __('New window'),
														'name' => 'new_window',
														'type' => 'true_false',
														'column_width' => '',
														'message' => '',
														'default_value' => 0,
													),
												),
												'row_min' => '',
												'row_limit' => '',
												'layout' => 'row',
												'button_label' => 'Add a Text Link',
											),
										),
									),
									array (
										'label' => __('Text to image link'),
										'name' => 'text_to_image_link',
										'display' => 'row',
										'min' => '',
										'max' => '',
										'sub_fields' => array (
											array (
												'key' => 'field_66m2arw0adipyw',
												'label' => __('Text'),
												'name' => 'text',
												'type' => 'text',
												'column_width' => '',
												'default_value' => '',
												'placeholder' => '',
												'prepend' => '',
												'append' => '',
												'formatting' => 'html',
												'maxlength' => '',
											),
											array (
												'key' => 'field_l85kyqisslsd2f',
												'label' => __('Text type'),
												'name' => 'text_type',
												'type' => 'select',
												'column_width' => '',
												'choices' => array (
													'heading_1' => 'Heading 1',
													'heading_2' => 'Heading 2',
													'heading_3' => 'Heading 3',
													'heading_4' => 'Heading 4',
													'paragraph_text' => 'Paragraph text',
												),
												'default_value' => 'paragraph_text',
												'allow_null' => 0,
												'multiple' => 0,
											),
											array (
												'key' => 'field_g2z0kct6igw179',
												'label' => __('Image'),
												'name' => 'image',
												'type' => 'image',
												'column_width' => '',
												'save_format' => 'object',
												'preview_size' => 'thumbnail',
												'library' => 'all',
											),
										),
									),
									array (
										'label' => __('Text rotator'),
										'name' => 'text_rotator',
										'display' => 'row',
										'min' => '',
										'max' => '',
										'sub_fields' => array (
											array (
												'key' => 'field_m4gmm2851imcx3',
												'label' => __('Heading'),
												'name' => 'heading',
												'type' => 'text',
												'column_width' => '',
												'default_value' => '',
												'placeholder' => '',
												'prepend' => '',
												'append' => '',
												'formatting' => 'html',
												'maxlength' => '',
											),
											array (
												'key' => 'field_vo4gapzv90ad0q',
												'label' => __('Heading type'),
												'name' => 'heading_type',
												'type' => 'select',
												'column_width' => '',
												'choices' => array (
													'heading_1' => 'Heading 1',
													'heading_2' => 'Heading 2',
													'heading_3' => 'Heading 3',
													'heading_4' => 'Heading 4',
													'paragraph_text' => 'Paragraph text',
												),
												'default_value' => 'paragraph_text',
												'allow_null' => 0,
												'multiple' => 0,
											),
											array (
												'key' => 'field_hqk0lt6h7a1rxr',
												'label' => __('Texts'),
												'name' => 'text',
												'type' => 'repeater',
												'column_width' => '',
												'sub_fields' => array (
													array (
														'key' => 'field_rvws7ttejwe9xk',
														'label' => __('Text'),
														'name' => 'text',
														'type' => 'text',
														'column_width' => '',
														'default_value' => '',
														'placeholder' => '',
														'prepend' => '',
														'append' => '',
														'formatting' => 'html',
														'maxlength' => '',
													),
												),
												'row_min' => '',
												'row_limit' => '',
												'layout' => 'table',
												'button_label' => 'Add Text',
											),
										),
									),
									array (
										'label' => __('Vimeo'),
										'name' => 'vimeo',
										'display' => 'row',
										'min' => '',
										'max' => '',
										'sub_fields' => array (
											array (
												'key' => 'field_tcbmubm6gdwhvj',
												'label' => __('Heading'),
												'name' => 'heading',
												'type' => 'text',
												'column_width' => '',
												'default_value' => '',
												'placeholder' => '',
												'prepend' => '',
												'append' => '',
												'formatting' => 'html',
												'maxlength' => '',
											),
											array (
												'key' => 'field_gi616zgmfyho2a',
												'label' => __('Video link'),
												'name' => 'video_link',
												'type' => 'text',
												'column_width' => '',
												'default_value' => '',
												'placeholder' => '',
												'prepend' => '',
												'append' => '',
												'formatting' => 'html',
												'maxlength' => '',
											),
											array (
												'key' => 'field_3vb4fn3ybfrn1n',
												'label' => __('Video image'),
												'name' => 'video_image',
												'type' => 'image',
												'column_width' => '',
												'save_format' => 'object',
												'preview_size' => 'thumbnail',
												'library' => 'all',
											),
											array (
												'key' => 'field_h8kzr8rwan1saa',
												'label' => __('Heading type'),
												'name' => 'heading_type',
												'type' => 'select',
												'column_width' => '',
												'choices' => array (
												),
												'default_value' => '',
												'allow_null' => 0,
												'multiple' => 0,
											),
										),
									),
									array (
										'label' => __('Youtube'),
										'name' => 'youtube',
										'display' => 'row',
										'min' => '',
										'max' => '',
										'sub_fields' => array (
											array (
												'key' => 'field_392u28xj9ylukq',
												'label' => __('Heading'),
												'name' => 'heading',
												'type' => 'text',
												'column_width' => '',
												'default_value' => '',
												'placeholder' => '',
												'prepend' => '',
												'append' => '',
												'formatting' => 'html',
												'maxlength' => '',
											),
											array (
												'key' => 'field_gtwz0ktb7dyigw',
												'label' => __('Video link'),
												'name' => 'video_link',
												'type' => 'text',
												'column_width' => '',
												'default_value' => '',
												'placeholder' => '',
												'prepend' => '',
												'append' => '',
												'formatting' => 'html',
												'maxlength' => '',
											),
											array (
												'key' => 'field_8vu24fw25iotjj',
												'label' => __('Video image'),
												'name' => 'video_image',
												'type' => 'image',
												'column_width' => '',
												'save_format' => 'object',
												'preview_size' => 'thumbnail',
												'library' => 'all',
											),
											array (
												'key' => 'field_07a7c9nh9om95d',
												'label' => __('Heading type'),
												'name' => 'heading_type',
												'type' => 'select',
												'column_width' => '',
												'choices' => array (
													'heading_1' => 'Heading 1',
													'heading_2' => 'Heading 2',
													'heading_3' => 'Heading 3',
													'heading_4' => 'Heading 4',
													'paragraph_text' => 'Paragraph text',
												),
												'default_value' => 'paragraph_text',
												'allow_null' => 0,
												'multiple' => 0,
											),
										),
									),
								),
								'button_label' => 'Add an Item',
								'min' => '',
								'max' => '',
							),
						),
						'row_min' => '',
						'row_limit' => '',
						'layout' => 'row',
						'button_label' => 'Add a Nested Unit',
					),
				),
				'row_min' => '',
				'row_limit' => '',
				'layout' => 'row',
				'button_label' => 'Add a Unit',
				),
			),
			'location' => array (
				array (
					array (
						'param' => 'page_template',
						'operator' => '==',
						'value' => 'archive.php',
						'order_no' => 0,
						'group_no' => 0,
					),
				),
			),
			'options' => array (
				'position' => 'normal',
				'layout' => 'no_box',
				'hide_on_screen' => array (
					0 => 'the_content',
				),
			),
			'menu_order' => 0,
		));
}
?>