<?php
if(function_exists("register_field_group"))
{
	register_field_group(array (
		'id' => 'acf_attachments',
		'title' => 'Attachments',
		'fields' => array (
			array (
				'key' => 'field_5499999wwwopo',
				'label' => 'URL',
				'name' => 'url',
				'type' => 'text',
				'column_width' => '',
				'default_value' => '',
			),
			array (
				'key' => 'field_5499eee444opo',
				'label' => 'Inscription',
				'name' => 'inscription',
				'type' => 'text',
				'column_width' => '',
				'default_value' => '',
			),
			array (
				'key' => 'field_529f434e32304',
				'label' => 'Inscription Type',
				'name' => 'inscription_type',
				'type' => 'select',
				'choices' => array (
					'paragraph' => 'Paragraph',
					'heading_1' => 'Heading 1',
					'heading_2' => 'Heading 2',
					'heading_3' => 'Heading 3',
					'heading_4' => 'Heading 4',
				),
				'default_value' => 'paragraph',
				'allow_null' => 0,
				'multiple' => 0,
			),
			array (
				'key' => 'field_5499esdf884opo',
				'label' => 'Inscription URL',
				'name' => 'inscription_url',
				'type' => 'text',
				'column_width' => '',
				'default_value' => '',
			),
			array (
				'key' => 'field_8e8e55sdf884opo',
				'label' => 'New Window',
				'name' => 'new_window',
				'type' => 'true_false',
				'column_width' => '',
				'message' => '',
				'default_value' => 0,
			),
			array (
				'key' => 'field_5sdf96e444opo',
				'label' => 'Text 1',
				'name' => 'text_1',
				'type' => 'text',
				'column_width' => '',
				'default_value' => '',
			),
			array (
				'key' => 'field_5499ee48sfspo',
				'label' => 'Text 2',
				'name' => 'text_2',
				'type' => 'text',
				'column_width' => '',
				'default_value' => '',
			),
			array (
				'key' => 'field_sdf55ee444opo',
				'label' => 'Text 3',
				'name' => 'text_3',
				'type' => 'text',
				'column_width' => '',
				'default_value' => '',
			),
			array (
				'key' => 'field_5499esdf8741',
				'label' => 'Map Text 1',
				'name' => 'map_line_1',
				'type' => 'text',
				'column_width' => '',
				'default_value' => '',
			),
			array (
				'key' => 'field_54sdfsdddsssdo',
				'label' => 'Map Text 2',
				'name' => 'map_line_2',
				'type' => 'text',
				'column_width' => '',
				'default_value' => '',
			),
			array (
				'key' => 'field_51149sdfe444opo',
				'label' => 'Map Text 3',
				'name' => 'map_line_3',
				'type' => 'text',
				'column_width' => '',
				'default_value' => '',
			),
			array (
				'key' => 'field_wtt9eee444opo',
				'label' => 'Map Text 4',
				'name' => 'map_line_4',
				'type' => 'text',
				'column_width' => '',
				'default_value' => '',
			),
			array (
				'key' => 'field_5rr44eee444opo',
				'label' => 'Map URL Text',
				'name' => 'map_url_text',
				'type' => 'text',
				'column_width' => '',
				'default_value' => '',
			),
			array (
				'key' => 'field_77uteee444opo',
				'label' => 'Map URL',
				'name' => 'map_url',
				'type' => 'text',
				'column_width' => '',
				'default_value' => '',
			),
		),
		'location' => array (
			array (
				array (
					'param' => 'ef_media',
					'operator' => '==',
					'value' => 'all',
					'order_no' => 3,
					'group_no' => 0,
				),
			),
		),
		'options' => array (
			'position' => 'normal',
			'layout' => 'no_box',
			'hide_on_screen' => array (
			),
		),
		'menu_order' => 0,
	));
}
?>