<?php

if(function_exists("register_field_group"))
{
	register_field_group(array (
		'id' => 'acf_flexible-content',
		'title' => 'Flexible Content',
		'fields' => array (
			array (
				'key' => 'field_527a680f291f1',
				'label' => __('Grid'),
				'name' => 'grid',
				'type' => 'repeater',
				'sub_fields' => array (
					array (
						'key' => 'field_527a6820291f2',
						'label' => __('Unit Span'),
						'name' => 'unit_span',
						'type' => 'select',
						'column_width' => '',
						'choices' => array (
							'one-of-one' => 'One of one',
							'one-of-two' => 'One of two',
							'one-of-three' => 'One of three',
							'one-of-four' => 'One of four',
							'one-of-five' => 'One of five',
							'two-of-three' => 'Two of three',
							'two-of-five' => 'Two of five',
							'three-of-four' => 'Three of four',
							'three-of-five' => 'Three of five',
							'four-of-five' => 'Four of five',
						),
						'default_value' => 'one-of-one',
						'allow_null' => 0,
						'multiple' => 0,
					),
					array (
						'key' => 'field_527a7b6748836dsdf33',
						'label' => __('Background image'),
						'name' => 'background_image',
						'type' => 'image',
						'column_width' => '',
						'default_value' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'formatting' => 'html',
						'maxlength' => '',
					),
					array (
						'key' => 'field_7778s5888ds8d88sds',
						'label' => __('Wrapper Class'),
						'name' => 'wrapper_class',
						'type' => 'text',
						'column_width' => '',
						'default_value' => '',
					),
					array (
						'key' => 'field_7778s5888ds8d88sd',
						'label' => __('Class'),
						'name' => 'class',
						'type' => 'text',
						'column_width' => '',
						'default_value' => '',
					),
					array (
						'key' => 'field_527a680f291f1',
						'label' => __('Unit'),
						'name' => 'unit',
						'type' => 'repeater',
						'sub_fields' => array (
							array (
								'key' => 'field_527a6820291f2',
								'label' => __('Nested Unit Span'),
								'name' => 'nested_unit_span',
								'type' => 'select',
								'column_width' => '',
								'choices' => array (
									'one-of-one' => 'Nested -- One of one',
									'one-of-two' => 'Nested -- One of two',
									'one-of-three' => 'Nested -- One of three',
									'one-of-four' => 'Nested -- One of four',
									'one-of-five' => 'Nested -- One of five',
									'two-of-three' => 'Nested -- Two of three',
									'two-of-five' => 'Nested -- Two of five',
									'three-of-four' => 'Nested -- Three of four',
									'three-of-five' => 'Nested -- Three of five',
									'four-of-five' => 'Nested -- Four of five',
								),
								'default_value' => 'one-of-one',
								'allow_null' => 0,
								'multiple' => 0,
							),
							array (
								'key' => 'field_7778s5888ds8d88sd',
								'label' => __('Class'),
								'name' => 'class',
								'type' => 'text',
								'column_width' => '',
								'default_value' => '',
							),
							array (
								'key' => 'field_527a6c8b291f5',
								'label' => __('Nested Unit'),
								'name' => 'nested_unit',
								'type' => 'flexible_content',
								'column_width' => '',
								'layouts' => array (
									array (
										'label' => __('Accordion button'),
										'name' => 'accordion_button',
										'display' => 'row',
										'min' => '',
										'max' => '',
										'sub_fields' => array (
											array (
												'key' => 'field_ocvb6334417ya4o',
												'label' => __('Button text'),
												'name' => 'button_text',
												'type' => 'text',
												'column_width' => '',
												'default_value' => '',
												'placeholder' => '',
												'prepend' => '',
												'append' => '',
												'formatting' => 'html',
												'maxlength' => '',
											),
											array (
												'key' => 'field_6b9c5b59951ntyl',
												'label' => __('Editor'),
												'name' => 'editor',
												'type' => 'text',
												'column_width' => '',
												'default_value' => '',
												'placeholder' => '',
												'prepend' => '',
												'append' => '',
												'formatting' => 'html',
												'maxlength' => '',
											),
											array (
												'key' => 'field_7778s5888ds8d88sd',
												'label' => __('Class'),
												'name' => 'class',
												'type' => 'text',
												'column_width' => '',
												'default_value' => '',
											),
										),
									),
									array (
										'label' => __('Accordion editor'),
										'name' => 'accordion_editor',
										'display' => 'row',
										'min' => '',
										'max' => '',
										'sub_fields' => array (
											array (
												'key' => 'field_527a7c426fb39',
												'label' => __('Heading type'),
												'name' => 'heading_type',
												'type' => 'select',
												'column_width' => '',
												'choices' => array (
													'heading_1' => 'Heading 1',
													'heading_2' => 'Heading 2',
													'heading_3' => 'Heading 3',
													'heading_4' => 'Heading 4',
													'paragraph_text' => 'Paragraph text',
												),
												'default_value' => 'paragraph_text',
												'allow_null' => 0,
												'multiple' => 0,
											),
											array (
												'key' => 'field_527b0068a418f',
												'label' => __('Accordions'),
												'name' => 'accordion',
												'type' => 'repeater',
												'column_width' => '',
												'sub_fields' => array (
													array (
														'key' => 'field_527b008da4190',
														'label' => __('Heading'),
														'name' => 'heading',
														'type' => 'text',
														'column_width' => '',
														'default_value' => '',
														'placeholder' => '',
														'prepend' => '',
														'append' => '',
														'formatting' => 'html',
														'maxlength' => '',
													),
													array (
														'key' => 'field_527b00aaa4191',
														'label' => __('Editor'),
														'name' => 'editor',
														'type' => 'wysiwyg',
														'column_width' => '',
														'default_value' => '',
														'toolbar' => 'full',
														'media_upload' => 'yes',
													),
													array (
														'key' => 'field_7778s5888ds8d88sd',
														'label' => __('Class'),
														'name' => 'class',
														'type' => 'text',
														'column_width' => '',
														'default_value' => '',
													),
												),
												'row_min' => '',
												'row_limit' => '',
												'layout' => 'row',
												'button_label' => 'Add an Accordion',
											),
											array (
												'key' => 'field_7778s5888ds8d88sd',
												'label' => __('Class'),
												'name' => 'class',
												'type' => 'text',
												'column_width' => '',
												'default_value' => '',
											),
										),
									),
									array (
										'label' => __('Accordion links'),
										'name' => 'accordion_links',
										'display' => 'row',
										'min' => '',
										'max' => '',
										'sub_fields' => array (
											array (
												'key' => 'field_527c5669815f4',
												'label' => __('Heading type'),
												'name' => 'heading_type',
												'type' => 'select',
												'column_width' => '',
												'choices' => array (
													'heading_1' => 'Heading 1',
													'heading_2' => 'Heading 2',
													'heading_3' => 'Heading 3',
													'heading_4' => 'Heading 4',
													'paragraph_text' => 'Paragraph text',
												),
												'default_value' => 'paragraph_text',
												'allow_null' => 0,
												'multiple' => 0,
											),
											array (
												'key' => 'field_527c5669815f5',
												'label' => __('Accordions'),
												'name' => 'accordion',
												'type' => 'repeater',
												'column_width' => '',
												'sub_fields' => array (
													array (
														'key' => 'field_527c5669815f6',
														'label' => __('Heading'),
														'name' => 'heading',
														'type' => 'text',
														'column_width' => 3,
														'default_value' => '',
														'placeholder' => '',
														'prepend' => '',
														'append' => '',
														'formatting' => 'html',
														'maxlength' => '',
													),
													array (
														'key' => 'field_527c5669815f7',
														'label' => __('Links'),
														'name' => 'links',
														'type' => 'repeater',
														'column_width' => '',
														'sub_fields' => array (
															array (
																'key' => 'field_527c56b5815f8',
																'label' => __('Text'),
																'name' => 'text',
																'type' => 'text',
																'column_width' => '',
																'default_value' => '',
																'placeholder' => '',
																'prepend' => '',
																'append' => '',
																'formatting' => 'html',
																'maxlength' => '',
															),
															array (
																'key' => 'field_527c56c7815f9',
																'label' => __('Text 2'),
																'name' => 'text_2',
																'type' => 'text',
																'column_width' => '',
																'default_value' => '',
																'placeholder' => '',
																'prepend' => '',
																'append' => '',
																'formatting' => 'html',
																'maxlength' => '',
															),
															array (
																'key' => 'field_527c5b1f3db92',
																'label' => __('Text 2 type'),
																'name' => 'text_2_type',
																'type' => 'select',
																'instructions' => __('Choose type for text 2'),
																'column_width' => '',
																'choices' => array (
																	'text' => 'Text',
																	'class' => 'Class',
																	'url' => 'URL',
																),
																'default_value' => '',
																'allow_null' => 1,
																'multiple' => 0,
															),
															array (
																'key' => 'field_7778s5888ds8d88sd',
																'label' => __('Class'),
																'name' => 'class',
																'type' => 'text',
																'column_width' => '',
																'default_value' => '',
															),
														),
														'row_min' => '',
														'row_limit' => '',
														'layout' => 'row',
														'button_label' => 'Add a link',
													),
													array (
														'key' => 'field_7778s5888ds8d88sd',
														'label' => __('Class'),
														'name' => 'class',
														'type' => 'text',
														'column_width' => '',
														'default_value' => '',
													),
												),
												'row_min' => '',
												'row_limit' => '',
												'layout' => 'row',
												'button_label' => 'Add an Accordion',
											),
											array (
												'key' => 'field_7778s5888ds8d88sd',
												'label' => __('Class'),
												'name' => 'class',
												'type' => 'text',
												'column_width' => '',
												'default_value' => '',
											),
										),
									),
									array (
										'label' => __('Blockquote'),
										'name' => 'blockquote',
										'display' => 'row',
										'min' => '',
										'max' => '',
										'sub_fields' => array (
											array (
												'key' => 'field_527a7aed4882d',
												'label' => __('Quote'),
												'name' => 'quote',
												'type' => 'text',
												'column_width' => '',
												'default_value' => '',
												'placeholder' => '',
												'prepend' => '',
												'append' => '',
												'formatting' => 'html',
												'maxlength' => '',
											),
											array (
												'key' => 'field_527a7afb4882e',
												'label' => __('Credit line 1'),
												'name' => 'credit_line_1',
												'type' => 'text',
												'column_width' => '',
												'default_value' => '',
												'placeholder' => '',
												'prepend' => '',
												'append' => '',
												'formatting' => 'html',
												'maxlength' => '',
											),
											array (
												'key' => 'field_527a7b064882f',
												'label' => __('Credit line 2'),
												'name' => 'credit_line_2',
												'type' => 'text',
												'column_width' => '',
												'default_value' => '',
												'placeholder' => '',
												'prepend' => '',
												'append' => '',
												'formatting' => 'html',
												'maxlength' => '',
											),
											array (
												'key' => 'field_527d31c986310',
												'label' => __('Credit line 2 type'),
												'name' => 'credit_line_2_type',
												'type' => 'select',
												'column_width' => '',
												'choices' => array (
													'text' => 'Text',
													'class' => 'Class',
													'url' => 'URL',
												),
												'default_value' => '',
												'allow_null' => 0,
												'multiple' => 0,
											),
											array (
												'key' => 'field_527d31f486311',
												'label' => __('New window'),
												'name' => 'new_window',
												'type' => 'true_false',
												'column_width' => '',
												'message' => '',
												'default_value' => 0,
											),
											array (
												'key' => 'field_7778s5888ds8d88sd',
												'label' => __('Class'),
												'name' => 'class',
												'type' => 'text',
												'column_width' => '',
												'default_value' => '',
											),
										),
									),
									array (
										'label' => __('Blockquote rotator'),
										'name' => 'blockquote_rotator',
										'display' => 'row',
										'min' => '',
										'max' => '',
										'sub_fields' => array (
											array (
												'key' => 'field_527a7b1e48831',
												'label' => __('Quotes'),
												'name' => 'quotes',
												'type' => 'repeater',
												'column_width' => '',
												'sub_fields' => array (
													array (
														'key' => 'field_527a7b2a48832',
														'label' => __('Quote'),
														'name' => 'quote',
														'type' => 'text',
														'column_width' => '',
														'default_value' => '',
														'placeholder' => '',
														'prepend' => '',
														'append' => '',
														'formatting' => 'html',
														'maxlength' => '',
													),
													array (
														'key' => 'field_527a7b3f48833',
														'label' => __('Credit line 1'),
														'name' => 'credit_line_1',
														'type' => 'text',
														'column_width' => '',
														'default_value' => '',
														'placeholder' => '',
														'prepend' => '',
														'append' => '',
														'formatting' => 'html',
														'maxlength' => '',
													),
													array (
														'key' => 'field_527a7b4d48834',
														'label' => __('Credit line 2'),
														'name' => 'credit_line_2',
														'type' => 'text',
														'column_width' => '',
														'default_value' => '',
														'placeholder' => '',
														'prepend' => '',
														'append' => '',
														'formatting' => 'html',
														'maxlength' => '',
													),
													array (
														'key' => 'field_527d29f6148da',
														'label' => __('Credit line 2 type'),
														'name' => 'credit_line_2_type',
														'type' => 'select',
														'column_width' => '',
														'choices' => array (
															'text' => 'Text',
															'class' => 'Class',
															'url' => 'URL',
														),
														'default_value' => '',
														'allow_null' => 0,
														'multiple' => 0,
													),
													array (
														'key' => 'field_527d2f192499e',
														'label' => __('New window'),
														'name' => 'new_window',
														'type' => 'true_false',
														'column_width' => '',
														'message' => '',
														'default_value' => 0,
													),
													array (
														'key' => 'field_7778s5888ds8d88sd',
														'label' => __('Class'),
														'name' => 'class',
														'type' => 'text',
														'column_width' => '',
														'default_value' => '',
													),
												),
												'row_min' => '',
												'row_limit' => '',
												'layout' => 'row',
												'button_label' => 'Add a Quote',
											),
											array (
												'key' => 'field_7778s5888ds8d88sd',
												'label' => __('Class'),
												'name' => 'class',
												'type' => 'text',
												'column_width' => '',
												'default_value' => '',
											),
										),
									),
									array (
										'label' => __('Button link'),
										'name' => 'button_link',
										'display' => 'row',
										'min' => '',
										'max' => '',
										'sub_fields' => array (
											array (
												'key' => 'field_527a7ab948829',
												'label' => __('Text'),
												'name' => 'text',
												'type' => 'text',
												'column_width' => '',
												'default_value' => '',
												'placeholder' => '',
												'prepend' => '',
												'append' => '',
												'formatting' => 'html',
												'maxlength' => '',
											),
											array (
												'key' => 'field_527a7acd4882a',
												'label' => __('Link'),
												'name' => 'link',
												'type' => 'text',
												'column_width' => '',
												'default_value' => '',
												'placeholder' => '',
												'prepend' => '',
												'append' => '',
												'formatting' => 'html',
												'maxlength' => '',
											),
											array (
												'key' => 'field_527a7ad84882b',
												'label' => __('New window'),
												'name' => 'new_window',
												'type' => 'true_false',
												'column_width' => '',
												'message' => '',
												'default_value' => 0,
											),
											array (
												'key' => 'field_7778s5888ds8d88sd',
												'label' => __('Class'),
												'name' => 'class',
												'type' => 'text',
												'column_width' => '',
												'default_value' => '',
											),
										),
									),
									array (
										'label' => __('Editor'),
										'name' => 'editor',
										'display' => 'row',
										'min' => '',
										'max' => '',
										'sub_fields' => array (
											array (
												'key' => 'field_527a99ffe011d',
												'label' => __('Editor'),
												'name' => 'editor',
												'type' => 'wysiwyg',
												'column_width' => '',
												'default_value' => '',
												'toolbar' => 'full',
												'media_upload' => 'yes',
											),
											array (
												'key' => 'field_7778s5888ds8d88sd',
												'label' => __('Class'),
												'name' => 'class',
												'type' => 'text',
												'column_width' => '',
												'default_value' => '',
											),
										),
									),
									array (
										'label' => __('Heading'),
										'name' => 'heading',
										'display' => 'row',
										'min' => '',
										'max' => '',
										'sub_fields' => array (
											array (
												'key' => 'field_52ds2968ded6',
												'label' => __('Heading'),
												'name' => 'heading',
												'type' => 'text',
												'column_width' => '',
												'default_value' => '',
												'placeholder' => '',
												'prepend' => '',
												'append' => '',
												'formatting' => 'html',
												'maxlength' => '',
											),
											array (
												'key' => 'field_527d3de66555s554',
												'label' => __('Heading type'),
												'name' => 'heading_type',
												'type' => 'select',
												'column_width' => '',
												'choices' => array (
													'heading_1' => 'Heading 1',
													'heading_2' => 'Heading 2',
													'heading_3' => 'Heading 3',
													'heading_4' => 'Heading 4',
												),
												'default_value' => 'heading_2',
												'allow_null' => 0,
												'multiple' => 0,
											),
											array (
												'key' => 'field_4sdf9ded60a',
												'label' => __('Link'),
												'name' => 'link',
												'type' => 'text',
												'column_width' => '',
												'default_value' => '',
												'placeholder' => '',
												'prepend' => '',
												'append' => '',
												'formatting' => 'html',
												'maxlength' => '',
											),
											array (
												'key' => 'field_527a7sfd80b',
												'label' => __('New window'),
												'name' => 'new_window',
												'type' => 'true_false',
												'column_width' => '',
												'message' => '',
												'default_value' => 0,
											),
											array (
												'key' => 'field_7778s5888ds8d88sd',
												'label' => __('Class'),
												'name' => 'class',
												'type' => 'text',
												'column_width' => '',
												'default_value' => '',
											),
										),
									),
									array (
										'label' => __('Image'),
										'name' => 'image',
										'display' => 'row',
										'min' => '',
										'max' => '',
										'sub_fields' => array (
											array (
												'key' => 'field_527a7b6748836',
												'label' => __('Image'),
												'name' => 'image',
												'type' => 'image',
												'column_width' => '',
												'default_value' => '',
												'placeholder' => '',
												'prepend' => '',
												'append' => '',
												'formatting' => 'html',
												'maxlength' => '',
											),
											array (
												'key' => 'field_525645dd7791f2',
												'label' => __('Image size'),
												'name' => 'image_size',
												'type' => 'select',
												'column_width' => '',
												'choices' => array (
													'thumbnail' => 'Thumbnail',
													'medium' => 'Medium',
													'full' => 'Full',
													'main-image' => 'Main image',
													'gallery-thumbnail' => 'Gallery thumbnail',
													'headshot-image' => 'Headshot image',
													'map-image' => 'Map image',
													'one-of-one-image' => 'One of one image',
													'one-of-two-image' => 'One of two image',
													'one-of-three-image' => 'One of three image',
													'one-of-four-image' => 'One of four image',
													'one-of-five-image' => 'One of five image',
													'two-of-three-image' => 'Two of three image',
													'two-of-five-image' => 'Two of five image',
													'three-of-four-image' => 'Three of four image',
													'three-of-five-image' => 'Three of five image',
													'four-of-five-image' => 'Four of five image',
													'square-one-of-one-image' => 'Square One of one image',
													'square-one-of-two-image' => 'Square One of two image',
													'square-one-of-three-image' => 'Square One of three image',
													'square-one-of-four-image' => 'Square One of four image',
													'square-one-of-five-image' => 'Square One of five image',
													'square-two-of-three-image' => 'Square Two of three image',
													'square-two-of-five-image' => 'Square Two of five image',
													'square-three-of-four-image' => 'Square Three of four image',
													'square-three-of-five-image' => 'Square Three of five image',
													'square-four-of-five-image' => 'Square Four of five image'
												),
												'default_value' => 'one-of-one-image',
												'allow_null' => 0,
												'multiple' => 0,
											),
											array (
												'key' => 'field_527a7b7f48837',
												'label' => __('Image link'),
												'name' => 'image_link',
												'type' => 'text',
												'column_width' => '',
												'default_value' => '',
												'placeholder' => '',
												'prepend' => '',
												'append' => '',
												'formatting' => 'html',
												'maxlength' => '',
											),
											array (
												'key' => 'field_527a7b8748838',
												'label' => __('New window'),
												'name' => 'new_window',
												'type' => 'true_false',
												'column_width' => '',
												'message' => '',
												'default_value' => 0,
											),
											array (
												'key' => 'field_7778s5888ds8d88sd',
												'label' => __('Class'),
												'name' => 'class',
												'type' => 'text',
												'column_width' => '',
												'default_value' => '',
											),
										),
									),
									array (
										'label' => __('Image carousel'),
										'name' => 'image_carousel',
										'display' => 'row',
										'min' => '',
										'max' => '',
										'sub_fields' => array (
											array (
												'key' => 'field_527ad4eadc276',
												'label' => __('Images'),
												'name' => 'images',
												'type' => 'gallery',
												'column_width' => '',
												'preview_size' => 'thumbnail',
												'library' => 'all',
											),
											array (
												'key' => 'field_7778s5888ds8d88sd',
												'label' => __('Class'),
												'name' => 'class',
												'type' => 'text',
												'column_width' => '',
												'default_value' => '',
											),
										),
									),
									array (
										'label' => __('Image gallery'),
										'name' => 'image_gallery',
										'display' => 'row',
										'min' => '',
										'max' => '',
										'sub_fields' => array (
											array (
												'key' => 'field_527d482fb389c',
												'label' => __('Images'),
												'name' => 'images',
												'type' => 'gallery',
												'column_width' => '',
												'preview_size' => 'thumbnail',
												'library' => 'all',
											),
											array (
												'key' => 'field_88d4sascbkos',
												'label' => __('Columns'),
												'name' => 'columns',
												'type' => 'number',
												'column_width' => 15,
												'placeholder' => '',
												'default_value' => 5,
												'min' => 1,
												'max' => '',
												'step' => '',
											),
											array (
												'key' => 'field_69sdf8d973145gboks011d',
												'label' => __('Group'),
												'name' => 'group',
												'type' => 'true_false',
												'column_width' => '',
												'message' => '',
												'default_value' => 0,
											),
											array (
												'key' => 'field_7778s5888ds8d88sd',
												'label' => __('Class'),
												'name' => 'class',
												'type' => 'text',
												'column_width' => '',
												'default_value' => '',
											),
										),
									),
									array (
										'label' => __('Image link gallery'),
										'name' => 'image_link_gallery',
										'display' => 'row',
										'min' => '',
										'max' => '',
										'sub_fields' => array (
											array (
												'key' => 'field_527d65d4fs4d65465',
												'label' => __('Images'),
												'name' => 'images',
												'type' => 'gallery',
												'column_width' => '',
												'preview_size' => 'thumbnail',
												'library' => 'all',
											),
											array (
												'key' => 'field_88d4sascbkos',
												'label' => __('Columns'),
												'name' => 'columns',
												'type' => 'number',
												'column_width' => 15,
												'placeholder' => '',
												'default_value' => 5,
												'min' => 1,
												'max' => '',
											),
											array (
												'key' => 'field_7778s5888ds8d88sd',
												'label' => __('Class'),
												'name' => 'class',
												'type' => 'text',
												'column_width' => '',
												'default_value' => '',
											),
										),
									),
									array (
										'label' => __('Image rotator'),
										'name' => 'image_rotator',
										'display' => 'row',
										'min' => '',
										'max' => '',
										'sub_fields' => array (
											array (
												'key' => 'field_527aca0569bb5',
												'label' => __('Images'),
												'name' => 'images',
												'type' => 'gallery',
												'column_width' => '',
												'preview_size' => 'thumbnail',
												'library' => 'all',
											),
											array (
												'key' => 'field_7778s5888ds8d88sd',
												'label' => __('Class'),
												'name' => 'class',
												'type' => 'text',
												'column_width' => '',
												'default_value' => '',
											),
										),
									),
									array (
										'label' => __('Image with hover'),
										'name' => 'image_with_hover',
										'display' => 'row',
										'min' => '',
										'max' => '',
										'sub_fields' => array (
											array (
												'key' => 'field_527a7bb96fb2e',
												'label' => __('Image'),
												'name' => 'image',
												'type' => 'image',
												'column_width' => '',
												'save_format' => 'object',
												'preview_size' => 'thumbnail',
												'library' => 'all',
											),
											array (
												'key' => 'field_527a7bc86fb2f',
												'label' => __('Hover image'),
												'name' => 'hover_image',
												'type' => 'image',
												'column_width' => '',
												'save_format' => 'object',
												'preview_size' => 'thumbnail',
												'library' => 'all',
											),
											array (
												'key' => 'field_527a7bda6fb30',
												'label' => __('Link'),
												'name' => 'link',
												'type' => 'text',
												'column_width' => '',
												'default_value' => '',
												'placeholder' => '',
												'prepend' => '',
												'append' => '',
												'formatting' => 'html',
												'maxlength' => '',
											),
											array (
												'key' => 'field_527a7be26fb31',
												'label' => __('New Window'),
												'name' => 'new_window',
												'type' => 'true_false',
												'column_width' => '',
												'message' => '',
												'default_value' => 0,
											),
											array (
												'key' => 'field_7778s5888ds8d88sd',
												'label' => __('Class'),
												'name' => 'class',
												'type' => 'text',
												'column_width' => '',
												'default_value' => '',
											),
										),
									),
									array (
										'label' => __('Main image'),
										'name' => 'main_image',
										'display' => 'row',
										'min' => '',
										'max' => '',
										'sub_fields' => array (
											array (
												'key' => 'field_527b2632285be',
												'label' => __('Image'),
												'name' => 'image',
												'type' => 'image',
												'column_width' => '',
												'save_format' => 'object',
												'preview_size' => 'thumbnail',
												'library' => 'all',
											),
											array (
												'key' => 'field_7778s5888ds8d88sd',
												'label' => __('Class'),
												'name' => 'class',
												'type' => 'text',
												'column_width' => '',
												'default_value' => '',
											),
										),
									),
									array (
										'label' => __('Map'),
										'name' => 'map',
										'display' => 'row',
										'min' => '',
										'max' => '',
										'sub_fields' => array (
											array (
												'key' => 'field_527d774989f16',
												'label' => __('Map'),
												'name' => 'map',
												'type' => 'google_map',
												'column_width' => '',
												'center_lat' => '',
												'center_lng' => '',
												'height' => '',
											),
											array (
												'key' => 'field_527d774989f17',
												'label' => __('Map height'),
												'name' => 'map_height',
												'type' => 'number',
												'instructions' => __('Please enter the map height'),
												'column_width' => 15,
												'default_value' => 300,
												'placeholder' => '',
												'prepend' => '',
												'append' => 'px',
												'min' => 50,
												'max' => '',
												'step' => '',
											),
											array (
												'key' => 'field_527d774989f18',
												'label' => __('Style ID'),
												'name' => 'style_id',
												'type' => 'text',
												'instructions' => __('This is the ID of the map style you desire an ID can be retrieved from http://maps.cloudmade.com/editor'),
												'column_width' => '',
												'default_value' => 1714,
												'placeholder' => '',
												'prepend' => '',
												'append' => '',
												'formatting' => 'html',
												'maxlength' => '',
											),
											array (
												'key' => 'field_527d774989f19',
												'label' => __('Zoom level'),
												'name' => 'zoom_level',
												'type' => 'number',
												'column_width' => '',
												'default_value' => 3,
												'placeholder' => '',
												'prepend' => '',
												'append' => '',
												'min' => 0,
												'max' => 18,
												'step' => '',
											),
											array (
												'key' => 'field_527d774989f1a',
												'label' => __('Markers'),
												'name' => 'markers',
												'type' => 'repeater',
												'column_width' => '',
												'sub_fields' => array (
													array (
														'key' => 'field_527d774989f1b',
														'label' => __('Location'),
														'name' => 'location',
														'type' => 'google_map',
														'column_width' => '',
														'center_lat' => '',
														'center_lng' => '',
														'height' => '',
													),
													array (
														'key' => 'field_527d774989f1c',
														'label' => __('Image'),
														'name' => 'image',
														'type' => 'image',
														'instructions' => __('Add caption and text to image view on maker'),
														'column_width' => '',
														'save_format' => 'object',
														'preview_size' => 'thumbnail',
														'library' => 'all',
													),
													array (
														'key' => 'field_7778s5888ds8d88sd',
														'label' => __('Class'),
														'name' => 'class',
														'type' => 'text',
														'column_width' => '',
														'default_value' => '',
													),
												),
												'row_min' => '',
												'row_limit' => '',
												'layout' => 'row',
												'button_label' => 'Add a Map Marker',
											),
										),
									),
									array (
										'label' => __('PDF link'),
										'name' => 'pdf_link',
										'display' => 'row',
										'min' => '',
										'max' => '',
										'sub_fields' => array (
											array (
												'key' => 'field_527a7bfd6fb33',
												'label' => __('Text'),
												'name' => 'text',
												'type' => 'text',
												'column_width' => '',
												'default_value' => '',
												'placeholder' => '',
												'prepend' => '',
												'append' => '',
												'formatting' => 'html',
												'maxlength' => '',
											),
											array (
												'key' => 'field_527d20db9fdb0',
												'label' => __('Text type'),
												'name' => 'text_type',
												'type' => 'select',
												'column_width' => '',
												'choices' => array (
													'heading_1' => 'Heading 1',
													'heading_2' => 'Heading 2',
													'heading_3' => 'Heading 3',
													'heading_4' => 'Heading 4',
													'paragraph_text' => 'Paragraph text',
												),
												'default_value' => 'paragraph_text',
												'allow_null' => 0,
												'multiple' => 0,
											),
											array (
												'key' => 'field_527a7c0c6fb34',
												'label' => __('PDF'),
												'name' => 'pdf',
												'type' => 'file',
												'column_width' => '',
												'save_format' => 'object',
												'library' => 'all',
											),
											array (
												'key' => 'field_527a7c166fb35',
												'label' => __('New window'),
												'name' => 'new_window',
												'type' => 'true_false',
												'column_width' => '',
												'message' => '',
												'default_value' => 0,
											),
											array (
												'key' => 'field_7778s5888ds8d88sd',
												'label' => __('Class'),
												'name' => 'class',
												'type' => 'text',
												'column_width' => '',
												'default_value' => '',
											),
										),
									),
									array (
										'label' => __('Shortcode'),
										'name' => 'shortcode',
										'display' => 'row',
										'min' => '',
										'max' => '',
										'sub_fields' => array (
											array (
												'key' => 'field_527d3de6sa9s5c59dv84654',
												'label' => __('Shortcodes'),
												'name' => 'shortcodes',
												'type' => 'select',
												'column_width' => '',
												'choices' => $shortcode_choices,
												'message' => '',
												'default_value' => '',
											),
											array (
												'key' => 'field_7778s5888ds8d88sd',
												'label' => __('Class'),
												'name' => 'class',
												'type' => 'text',
												'column_width' => '',
												'default_value' => '',
											),
										),
									),
									array (
										'label' => __('Sub menu'),
										'name' => 'sub_menu',
										'display' => 'row',
										'min' => '',
										'max' => '',
										'sub_fields' => array (
											array (
												'key' => 'field_527d3de684654',
												'label' => __('Primary header menu'),
												'name' => 'primary_header_menu',
												'type' => 'true_false',
												'column_width' => '',
												'message' => '',
												'default_value' => 1,
											),
											array (
												'key' => 'field_527anmdisn276',
												'label' => __('Custom theme menu location'),
												'name' => 'custom_theme_menu_location',
												'type' => 'text',
												'column_width' => '',
											),
										),
									),
									array (
										'label' => __('Text link'),
										'name' => 'text_link',
										'display' => 'row',
										'min' => '',
										'max' => '',
										'sub_fields' => array (
											array (
												'key' => 'field_527a79f1748ce',
												'label' => __('Text links'),
												'name' => 'text_link',
												'type' => 'repeater',
												'column_width' => '',
												'sub_fields' => array (
													array (
														'key' => 'field_527a79fe748cf',
														'label' => __('Text'),
														'name' => 'text',
														'type' => 'text',
														'column_width' => '',
														'default_value' => '',
														'placeholder' => '',
														'prepend' => '',
														'append' => '',
														'formatting' => 'html',
														'maxlength' => '',
													),
													array (
														'key' => 'field_527a7a15748d0',
														'label' => __('Link'),
														'name' => 'link',
														'type' => 'text',
														'column_width' => '',
														'default_value' => '',
														'placeholder' => '',
														'prepend' => '',
														'append' => '',
														'formatting' => 'html',
														'maxlength' => '',
													),
													array (
														'key' => 'field_527a7a1b748d1',
														'label' => __('New window'),
														'name' => 'new_window',
														'type' => 'true_false',
														'column_width' => '',
														'message' => '',
														'default_value' => 0,
													),
													array (
														'key' => 'field_7778s5888ds8d88sd',
														'label' => __('Class'),
														'name' => 'class',
														'type' => 'text',
														'column_width' => '',
														'default_value' => '',
													),
												),
												'row_min' => '',
												'row_limit' => '',
												'layout' => 'row',
												'button_label' => 'Add a Text Link',
											),
											array (
												'key' => 'field_7778s5888ds8d88sd',
												'label' => __('Class'),
												'name' => 'class',
												'type' => 'text',
												'column_width' => '',
												'default_value' => '',
											),
										),
									),
									array (
										'label' => __('Text to image link'),
										'name' => 'text_to_image_link',
										'display' => 'row',
										'min' => '',
										'max' => '',
										'sub_fields' => array (
											array (
												'key' => 'field_527a7a5c48824',
												'label' => __('Text'),
												'name' => 'text',
												'type' => 'text',
												'column_width' => '',
												'default_value' => '',
												'placeholder' => '',
												'prepend' => '',
												'append' => '',
												'formatting' => 'html',
												'maxlength' => '',
											),
											array (
												'key' => 'field_527d41afb3ba7',
												'label' => __('Text type'),
												'name' => 'text_type',
												'type' => 'select',
												'column_width' => '',
												'choices' => array (
													'heading_1' => 'Heading 1',
													'heading_2' => 'Heading 2',
													'heading_3' => 'Heading 3',
													'heading_4' => 'Heading 4',
													'paragraph_text' => 'Paragraph text',
												),
												'default_value' => 'paragraph_text',
												'allow_null' => 0,
												'multiple' => 0,
											),
											array (
												'key' => 'field_527a7a6c48825',
												'label' => __('Image'),
												'name' => 'image',
												'type' => 'image',
												'column_width' => '',
												'save_format' => 'object',
												'preview_size' => 'thumbnail',
												'library' => 'all',
											),
											array (
												'key' => 'field_7778s5888ds8d88sd',
												'label' => __('Class'),
												'name' => 'class',
												'type' => 'text',
												'column_width' => '',
												'default_value' => '',
											),
										),
									),
									array (
										'label' => __('Text rotator'),
										'name' => 'text_rotator',
										'display' => 'row',
										'min' => '',
										'max' => '',
										'sub_fields' => array (
											array (
												'key' => 'field_527d3dda02ed7',
												'label' => __('Heading'),
												'name' => 'heading',
												'type' => 'text',
												'column_width' => '',
												'default_value' => '',
												'placeholder' => '',
												'prepend' => '',
												'append' => '',
												'formatting' => 'html',
												'maxlength' => '',
											),
											array (
												'key' => 'field_527d3de602ed8',
												'label' => __('Heading type'),
												'name' => 'heading_type',
												'type' => 'select',
												'column_width' => '',
												'choices' => array (
													'heading_1' => 'Heading 1',
													'heading_2' => 'Heading 2',
													'heading_3' => 'Heading 3',
													'heading_4' => 'Heading 4',
													'paragraph_text' => 'Paragraph text',
												),
												'default_value' => 'paragraph_text',
												'allow_null' => 0,
												'multiple' => 0,
											),
											array (
												'key' => 'field_527a7a7c48826',
												'label' => __('Texts'),
												'name' => 'text',
												'type' => 'repeater',
												'column_width' => '',
												'sub_fields' => array (
													array (
														'key' => 'field_527a7a9348827',
														'label' => __('Text'),
														'name' => 'text',
														'type' => 'text',
														'column_width' => '',
														'default_value' => '',
														'placeholder' => '',
														'prepend' => '',
														'append' => '',
														'formatting' => 'html',
														'maxlength' => '',
													),
													array (
														'key' => 'field_7778s5888ds8d88sd',
														'label' => __('Class'),
														'name' => 'class',
														'type' => 'text',
														'column_width' => '',
														'default_value' => '',
													),
												),
												'row_min' => '',
												'row_limit' => '',
												'layout' => 'table',
												'button_label' => 'Add Text',
											),
											array (
												'key' => 'field_7778s5888ds8d88sd',
												'label' => __('Class'),
												'name' => 'class',
												'type' => 'text',
												'column_width' => '',
												'default_value' => '',
											),
										),
									),
									array (
										'label' => __('Title'),
										'name' => 'title',
										'display' => 'row',
										'min' => '',
										'max' => '',
										'sub_fields' => array (
											array (
												'key' => 'field_5srf77eesn276',
												'label' => __('Title'),
												'name' => 'title',
												'type' => 'true_false',
												'column_width' => '',
												'message' => '',
												'default_value' => 1,
											),
											array (
												'key' => 'field_52aadeee25654',
												'label' => __('Title type'),
												'name' => 'title_type',
												'type' => 'select',
												'column_width' => '',
												'choices' => array (
													'heading_1' => 'Heading 1',
													'heading_2' => 'Heading 2',
													'heading_3' => 'Heading 3',
													'heading_4' => 'Heading 4',
												),
												'default_value' => 'heading_1',
												'allow_null' => 0,
												'multiple' => 0,
											),
											array (
												'key' => 'field_4sdf9ded60a',
												'label' => __('Link'),
												'name' => 'link',
												'type' => 'text',
												'column_width' => '',
												'default_value' => '',
												'placeholder' => '',
												'prepend' => '',
												'append' => '',
												'formatting' => 'html',
												'maxlength' => '',
											),
											array (
												'key' => 'field_527a7sfd80b',
												'label' => __('New window'),
												'name' => 'new_window',
												'type' => 'true_false',
												'column_width' => '',
												'message' => '',
												'default_value' => 0,
											),
											array (
												'key' => 'field_7778s5888ds8d88sd',
												'label' => __('Class'),
												'name' => 'class',
												'type' => 'text',
												'column_width' => '',
												'default_value' => '',
											),
										),
									),
									array (
										'label' => __('Vimeo'),
										'name' => 'vimeo',
										'display' => 'row',
										'min' => '',
										'max' => '',
										'sub_fields' => array (
											array (
												'key' => 'field_527a7d156fb43',
												'label' => __('Heading'),
												'name' => 'heading',
												'type' => 'text',
												'column_width' => '',
												'default_value' => '',
												'placeholder' => '',
												'prepend' => '',
												'append' => '',
												'formatting' => 'html',
												'maxlength' => '',
											),
											array (
												'key' => 'field_527a7d156fb44',
												'label' => __('Video link'),
												'name' => 'video_link',
												'type' => 'text',
												'column_width' => '',
												'default_value' => '',
												'placeholder' => '',
												'prepend' => '',
												'append' => '',
												'formatting' => 'html',
												'maxlength' => '',
											),
											array (
												'key' => 'field_527a7d156fb45',
												'label' => __('Video image'),
												'name' => 'video_image',
												'type' => 'image',
												'column_width' => '',
												'save_format' => 'object',
												'preview_size' => 'thumbnail',
												'library' => 'all',
											),
											array (
												'key' => 'field_527a7d156fb46',
												'label' => __('Heading type'),
												'name' => 'heading_type',
												'type' => 'select',
												'column_width' => '',
												'choices' => array (
												),
												'default_value' => '',
												'allow_null' => 0,
												'multiple' => 0,
											),
											array (
												'key' => 'field_7778s5888ds8d88sd',
												'label' => __('Class'),
												'name' => 'class',
												'type' => 'text',
												'column_width' => '',
												'default_value' => '',
											),
										),
									),
									array (
										'label' => __('Youtube'),
										'name' => 'youtube',
										'display' => 'row',
										'min' => '',
										'max' => '',
										'sub_fields' => array (
											array (
												'key' => 'field_527a7c976fb3e',
												'label' => __('Heading'),
												'name' => 'heading',
												'type' => 'text',
												'column_width' => '',
												'default_value' => '',
												'placeholder' => '',
												'prepend' => '',
												'append' => '',
												'formatting' => 'html',
												'maxlength' => '',
											),
											array (
												'key' => 'field_527a7cb46fb3f',
												'label' => __('Video link'),
												'name' => 'video_link',
												'type' => 'text',
												'column_width' => '',
												'default_value' => '',
												'placeholder' => '',
												'prepend' => '',
												'append' => '',
												'formatting' => 'html',
												'maxlength' => '',
											),
											array (
												'key' => 'field_527a7cd26fb40',
												'label' => __('Video image'),
												'name' => 'video_image',
												'type' => 'image',
												'column_width' => '',
												'save_format' => 'object',
												'preview_size' => 'thumbnail',
												'library' => 'all',
											),
											array (
												'key' => 'field_527a7ce06fb41',
												'label' => __('Heading type'),
												'name' => 'heading_type',
												'type' => 'select',
												'column_width' => '',
												'choices' => array (
													'heading_1' => 'Heading 1',
													'heading_2' => 'Heading 2',
													'heading_3' => 'Heading 3',
													'heading_4' => 'Heading 4',
													'paragraph_text' => 'Paragraph text',
												),
												'default_value' => 'paragraph_text',
												'allow_null' => 0,
												'multiple' => 0,
											),
											array (
												'key' => 'field_7778s5888ds8d88sd',
												'label' => __('Class'),
												'name' => 'class',
												'type' => 'text',
												'column_width' => '',
												'default_value' => '',
											),
										),
									),
								),

								'button_label' => 'Add an Item',
								'min' => '',
								'max' => '',
							),
						),
						'row_min' => '',
						'row_limit' => '',
						'layout' => 'row',
						'button_label' => 'Add a Nested Unit',
					),
				),
				'row_min' => '',
				'row_limit' => '',
				'layout' => 'row',
				'button_label' => 'Add a Unit',
				),
			),
			'location' => array (
				array (
					array (
						'param' => 'page_template',
						'operator' => '==',
						'value' => 'default',
						'order_no' => 0,
						'group_no' => 0,
					),
				),
			),
			'options' => array (
				'position' => 'normal',
				'layout' => 'no_box',
				'hide_on_screen' => array (
					0 => 'the_content',
				),
			),
			'menu_order' => 1,
		));
}
?>
