<?php

if(function_exists("register_field_group"))
{
	register_field_group(array (
		'id' => 'acf_single-content',
		'title' => 'Single Content',
		'fields' => array (
			array (
				'key' => 'field_ue1u1jf8lnmrd',
				'label' => __('Single Grid'),
				'name' => 'single_grid',
				'type' => 'repeater',
				'sub_fields' => array (
					array (
						'key' => 'field_b826tcql66vi',
						'label' => __('Unit Span'),
						'name' => 'unit_span',
						'type' => 'select',
						'column_width' => '',
						'choices' => array (
							'one-of-one' => 'One of one',
							'one-of-two' => 'One of two',
							'one-of-three' => 'One of three',
							'one-of-four' => 'One of four',
							'one-of-five' => 'One of five',
							'two-of-three' => 'Two of three',
							'two-of-five' => 'Two of five',
							'three-of-four' => 'Three of four',
							'three-of-five' => 'Three of five',
							'four-of-five' => 'Four of five',
						),
						'default_value' => 'one-of-one',
						'allow_null' => 0,
						'multiple' => 0,
					),
					array (
						'key' => 'field_7778s58c6e011d',
						'label' => __('Class'),
						'name' => 'class',
						'type' => 'text',
						'column_width' => '',
						'default_value' => '',
					),
					array (
						'key' => 'field_lo6mr1rpmiqpqd',
						'label' => __('Unit'),
						'name' => 'unit',
						'type' => 'repeater',
						'sub_fields' => array (
							array (
								'key' => 'field_2ibkvdjohxcvip',
								'label' => __('Nested Unit Span'),
								'name' => 'nested_unit_span',
								'type' => 'select',
								'column_width' => '',
								'choices' => array (
									'one-of-one' => 'Nested -- One of one',
									'one-of-two' => 'Nested -- One of two',
									'one-of-three' => 'Nested -- One of three',
									'one-of-four' => 'Nested -- One of four',
									'one-of-five' => 'Nested -- One of five',
									'two-of-three' => 'Nested -- Two of three',
									'two-of-five' => 'Nested -- Two of five',
									'three-of-four' => 'Nested -- Three of four',
									'three-of-five' => 'Nested -- Three of five',
									'four-of-five' => 'Nested -- Four of five',
								),
								'default_value' => 'one-of-one',
								'allow_null' => 0,
								'multiple' => 0,
							),
							array (
								'key' => 'field_7778s58c6e011d',
								'label' => __('Class'),
								'name' => 'class',
								'type' => 'text',
								'column_width' => '',
								'default_value' => '',
							),
							array (
								'key' => 'field_qtvxfqzcn2fukv',
								'label' => __('Nested Unit'),
								'name' => 'nested_unit',
								'type' => 'flexible_content',
								'column_width' => '',
								'layouts' => array (
									array (
										'label' => __('Accordion editor'),
										'name' => 'accordion_editor',
										'display' => 'row',
										'min' => '',
										'max' => '',
										'sub_fields' => array (
											array (
												'key' => 'field_rqngx7b1vhfo4p',
												'label' => __('Heading type'),
												'name' => 'heading_type',
												'type' => 'select',
												'column_width' => '',
												'choices' => array (
													'heading_1' => 'Heading 1',
													'heading_2' => 'Heading 2',
													'heading_3' => 'Heading 3',
													'heading_4' => 'Heading 4',
													'paragraph_text' => 'Paragraph text',
												),
												'default_value' => 'paragraph_text',
												'allow_null' => 0,
												'multiple' => 0,
											),
											array (
												'key' => 'field_uiltqtkkspoel9',
												'label' => __('Accordions'),
												'name' => 'accordion',
												'type' => 'repeater',
												'column_width' => '',
												'sub_fields' => array (
													array (
														'key' => 'field_8isnpe7pl0g7k1',
														'label' => __('Heading'),
														'name' => 'heading',
														'type' => 'text',
														'column_width' => '',
														'default_value' => '',
														'placeholder' => '',
														'prepend' => '',
														'append' => '',
														'formatting' => 'html',
														'maxlength' => '',
													),
													array (
														'key' => 'field_43d55qwej40hpw',
														'label' => __('Editor'),
														'name' => 'editor',
														'type' => 'wysiwyg',
														'column_width' => '',
														'default_value' => '',
														'toolbar' => 'full',
														'media_upload' => 'yes',
													),
													array (
														'key' => 'field_7778s58c6e011d',
														'label' => __('Class'),
														'name' => 'class',
														'type' => 'text',
														'column_width' => '',
														'default_value' => '',
													),
												),
												'row_min' => '',
												'row_limit' => '',
												'layout' => 'row',
												'button_label' => 'Add an Accordion',
											),
											array (
												'key' => 'field_7778s58c6e011d',
												'label' => __('Class'),
												'name' => 'class',
												'type' => 'text',
												'column_width' => '',
												'default_value' => '',
											),
										),
									),
									array (
										'label' => __('Accordion button'),
										'name' => 'accordion_button',
										'display' => 'row',
										'min' => '',
										'max' => '',
										'sub_fields' => array (
											array (
												'key' => 'field_qj2m5dgdsfmuig',
												'label' => __('Button text'),
												'name' => 'button_text',
												'type' => 'text',
												'column_width' => '',
												'default_value' => '',
												'placeholder' => '',
												'prepend' => '',
												'append' => '',
												'formatting' => 'html',
												'maxlength' => '',
											),
											array (
												'key' => 'field_0qchrl59u58gv3',
												'label' => __('Editor'),
												'name' => 'editor',
												'type' => 'text',
												'column_width' => '',
												'default_value' => '',
												'placeholder' => '',
												'prepend' => '',
												'append' => '',
												'formatting' => 'html',
												'maxlength' => '',
											),
											array (
												'key' => 'field_7778s58c6e011d',
												'label' => __('Class'),
												'name' => 'class',
												'type' => 'text',
												'column_width' => '',
												'default_value' => '',
											),
										),
									),
									array (
										'label' => __('Accordion links'),
										'name' => 'accordion_links',
										'display' => 'row',
										'min' => '',
										'max' => '',
										'sub_fields' => array (
											array (
												'key' => 'field_f9igtty3qlao6u',
												'label' => __('Heading type'),
												'name' => 'heading_type',
												'type' => 'select',
												'column_width' => '',
												'choices' => array (
													'heading_1' => 'Heading 1',
													'heading_2' => 'Heading 2',
													'heading_3' => 'Heading 3',
													'heading_4' => 'Heading 4',
													'paragraph_text' => 'Paragraph text',
												),
												'default_value' => 'paragraph_text',
												'allow_null' => 0,
												'multiple' => 0,
											),
											array (
												'key' => 'field_itw8hjx2rkxc8z',
												'label' => __('Accordions'),
												'name' => 'accordion',
												'type' => 'repeater',
												'column_width' => '',
												'sub_fields' => array (
													array (
														'key' => 'field_2q4m39fc04r04l',
														'label' => __('Heading'),
														'name' => 'heading',
														'type' => 'text',
														'column_width' => 3,
														'default_value' => '',
														'placeholder' => '',
														'prepend' => '',
														'append' => '',
														'formatting' => 'html',
														'maxlength' => '',
													),
													array (
														'key' => 'field_gs37t6h9m1oraj',
														'label' => __('Links'),
														'name' => 'links',
														'type' => 'repeater',
														'column_width' => '',
														'sub_fields' => array (
															array (
																'key' => 'field_gtgcq0qpp1hv9z',
																'label' => __('Text'),
																'name' => 'text',
																'type' => 'text',
																'column_width' => '',
																'default_value' => '',
																'placeholder' => '',
																'prepend' => '',
																'append' => '',
																'formatting' => 'html',
																'maxlength' => '',
															),
															array (
																'key' => 'field_nz1y59vb6kkjj7',
																'label' => __('Text 2'),
																'name' => 'text_2',
																'type' => 'text',
																'column_width' => '',
																'default_value' => '',
																'placeholder' => '',
																'prepend' => '',
																'append' => '',
																'formatting' => 'html',
																'maxlength' => '',
															),
															array (
																'key' => 'field_2pdby0iekaiz3w',
																'label' => __('Text 2 type'),
																'name' => 'text_2_type',
																'type' => 'select',
																'instructions' => __('Choose type for text 2'),
																'column_width' => '',
																'choices' => array (
																	'text' => 'Text',
																	'class' => 'Class',
																	'url' => 'URL',
																),
																'default_value' => '',
																'allow_null' => 1,
																'multiple' => 0,
															),
														),
														'row_min' => '',
														'row_limit' => '',
														'layout' => 'row',
														'button_label' => 'Add a link',
													),
													array (
														'key' => 'field_7778s58c6e011d',
														'label' => __('Class'),
														'name' => 'class',
														'type' => 'text',
														'column_width' => '',
														'default_value' => '',
													),
												),
												'row_min' => '',
												'row_limit' => '',
												'layout' => 'row',
												'button_label' => 'Add an Accordion',
											),
											array (
												'key' => 'field_7778s58c6e011d',
												'label' => __('Class'),
												'name' => 'class',
												'type' => 'text',
												'column_width' => '',
												'default_value' => '',
											),
										),
									),
									array (
										'label' => __('Archive accordion last name'),
										'name' => 'accordion_last_name',
										'display' => 'row',
										'min' => '',
										'max' => '',
										'sub_fields' => array (
											array (
												'key' => 'field_dsdposdfwsd0876a',
												'label' => __('Archive accordion last name'),
												'name' => 'accordion_last_name',
												'type' => 'true_false',
												'column_width' => '',
												'message' => '',
												'default_value' => 1,
											),
										),
									),
									array (
										'label' => __('Archive accordion publish date'),
										'name' => 'accordion_publish_date',
										'display' => 'row',
										'min' => '',
										'max' => '',
										'sub_fields' => array (
											array (
												'key' => 'field_sdfs55eewr097sd7786a',
												'label' => __('Archive accordion publish date'),
												'name' => 'accordion_publish_date',
												'type' => 'true_false',
												'column_width' => '',
												'message' => '',
												'default_value' => 1,
											),
										),
									),
									array (
										'label' => __('Archive accordion start date'),
										'name' => 'accordion_start_date',
										'display' => 'row',
										'min' => '',
										'max' => '',
										'sub_fields' => array (
											array (
												'key' => 'field_324j23lkj54a6as46a',
												'label' => __('Archive accordion start date'),
												'name' => 'accordion_start_date',
												'type' => 'true_false',
												'column_width' => '',
												'message' => '',
												'default_value' => 1,
											),
										),
									),
									array (
										'label' => __('Archive accordion category'),
										'name' => 'accordion_taxonomy_term',
										'display' => 'row',
										'min' => '',
										'max' => '',
										'sub_fields' => array (
											array (
												'key' => 'field_dereqwk326556dfder556a',
												'label' => __('Archive accordion category'),
												'name' => 'accordion_taxonomy_term',
												'type' => 'true_false',
												'column_width' => '',
												'message' => '',
												'default_value' => 1,
											),
										),
									),
									array (
										'label' => __('Blockquote'),
										'name' => 'blockquote',
										'display' => 'row',
										'min' => '',
										'max' => '',
										'sub_fields' => array (
											array (
												'key' => 'field_hvsdk8y8fmo5lg',
												'label' => __('Quote'),
												'name' => 'quote',
												'type' => 'text',
												'column_width' => '',
												'default_value' => '',
												'placeholder' => '',
												'prepend' => '',
												'append' => '',
												'formatting' => 'html',
												'maxlength' => '',
											),
											array (
												'key' => 'field_2fa6m93elgku0f',
												'label' => __('Credit line 1'),
												'name' => 'credit_line_1',
												'type' => 'text',
												'column_width' => '',
												'default_value' => '',
												'placeholder' => '',
												'prepend' => '',
												'append' => '',
												'formatting' => 'html',
												'maxlength' => '',
											),
											array (
												'key' => 'field_23p6vvlfxy1qt7',
												'label' => __('Credit line 2'),
												'name' => 'credit_line_2',
												'type' => 'text',
												'column_width' => '',
												'default_value' => '',
												'placeholder' => '',
												'prepend' => '',
												'append' => '',
												'formatting' => 'html',
												'maxlength' => '',
											),
											array (
												'key' => 'field_jnezdz3axnhfro',
												'label' => __('Credit line 2 type'),
												'name' => 'credit_line_2_type',
												'type' => 'select',
												'column_width' => '',
												'choices' => array (
													'text' => 'Text',
													'class' => 'Class',
													'url' => 'URL',
												),
												'default_value' => '',
												'allow_null' => 0,
												'multiple' => 0,
											),
											array (
												'key' => 'field_1mle7ck2uabdkl',
												'label' => __('New window'),
												'name' => 'new_window',
												'type' => 'true_false',
												'column_width' => '',
												'message' => '',
												'default_value' => 0,
											),
											array (
												'key' => 'field_7778s58c6e011d',
												'label' => __('Class'),
												'name' => 'class',
												'type' => 'text',
												'column_width' => '',
												'default_value' => '',
											),
										),
									),
									array (
										'label' => __('Blockquote rotator'),
										'name' => 'blockquote_rotator',
										'display' => 'row',
										'min' => '',
										'max' => '',
										'sub_fields' => array (
											array (
												'key' => 'field_unehjz64ajcq9h',
												'label' => __('Quotes'),
												'name' => 'quotes',
												'type' => 'repeater',
												'column_width' => '',
												'sub_fields' => array (
													array (
														'key' => 'field_4awbqob3tzxr7s',
														'label' => __('Quote'),
														'name' => 'quote',
														'type' => 'text',
														'column_width' => '',
														'default_value' => '',
														'placeholder' => '',
														'prepend' => '',
														'append' => '',
														'formatting' => 'html',
														'maxlength' => '',
													),
													array (
														'key' => 'field_7kxvc2p8g0egdf',
														'label' => __('Credit line 1'),
														'name' => 'credit_line_1',
														'type' => 'text',
														'column_width' => '',
														'default_value' => '',
														'placeholder' => '',
														'prepend' => '',
														'append' => '',
														'formatting' => 'html',
														'maxlength' => '',
													),
													array (
														'key' => 'field_6yh9vta0vhz0pt',
														'label' => __('Credit line 2'),
														'name' => 'credit_line_2',
														'type' => 'text',
														'column_width' => '',
														'default_value' => '',
														'placeholder' => '',
														'prepend' => '',
														'append' => '',
														'formatting' => 'html',
														'maxlength' => '',
													),
													array (
														'key' => 'field_aagd7dbc75zcvr',
														'label' => __('Credit line 2 type'),
														'name' => 'credit_line_2_type',
														'type' => 'select',
														'column_width' => '',
														'choices' => array (
															'text' => 'Text',
															'class' => 'Class',
															'url' => 'URL',
														),
														'default_value' => '',
														'allow_null' => 0,
														'multiple' => 0,
													),
													array (
														'key' => 'field_b9a08rjsml8ta9',
														'label' => __('New window'),
														'name' => 'new_window',
														'type' => 'true_false',
														'column_width' => '',
														'message' => '',
														'default_value' => 0,
													),
													array (
														'key' => 'field_7778s58c6e011d',
														'label' => __('Class'),
														'name' => 'class',
														'type' => 'text',
														'column_width' => '',
														'default_value' => '',
													),
												),
												'row_min' => '',
												'row_limit' => '',
												'layout' => 'row',
												'button_label' => 'Add a Quote',
											),
											array (
												'key' => 'field_7778s58c6e011d',
												'label' => __('Class'),
												'name' => 'class',
												'type' => 'text',
												'column_width' => '',
												'default_value' => '',
											),
										),
									),
									array (
										'label' => __('Button link'),
										'name' => 'button_link',
										'display' => 'row',
										'min' => '',
										'max' => '',
										'sub_fields' => array (
											array (
												'key' => 'field_vcvbfknjj2i3ve',
												'label' => __('Text'),
												'name' => 'text',
												'type' => 'text',
												'column_width' => '',
												'default_value' => '',
												'placeholder' => '',
												'prepend' => '',
												'append' => '',
												'formatting' => 'html',
												'maxlength' => '',
											),
											array (
												'key' => 'field_7k2sxqe84ngwn7',
												'label' => __('Link'),
												'name' => 'link',
												'type' => 'text',
												'column_width' => '',
												'default_value' => '',
												'placeholder' => '',
												'prepend' => '',
												'append' => '',
												'formatting' => 'html',
												'maxlength' => '',
											),
											array (
												'key' => 'field_dkkj28xbb60zxa',
												'label' => __('New window'),
												'name' => 'new_window',
												'type' => 'true_false',
												'column_width' => '',
												'message' => '',
												'default_value' => 0,
											),
											array (
												'key' => 'field_7778s58c6e011d',
												'label' => __('Class'),
												'name' => 'class',
												'type' => 'text',
												'column_width' => '',
												'default_value' => '',
											),
										),
									),
									array (
										'label' => __('Byline'),
										'name' => 'byline',
										'display' => 'row',
										'min' => '',
										'max' => '',
										'sub_fields' => array (
											array (
												'key' => 'field_8fs6d59085dszxa',
												'label' => __('Byline'),
												'name' => 'byline',
												'type' => 'true_false',
												'column_width' => '',
												'message' => '',
												'default_value' => 1,
											),
											array (
												'key' => 'field_7778s58c6e011d',
												'label' => __('Class'),
												'name' => 'class',
												'type' => 'text',
												'column_width' => '',
												'default_value' => '',
											),
										),
									),
									array (
										'label' => __('Dates'),
										'name' => 'dates',
										'display' => 'row',
										'min' => '',
										'max' => '',
										'sub_fields' => array (
											array (
												'key' => 'field_woj20awuz9ba9j',
												'label' => __('Date start'),
												'name' => 'date_start',
												'type' => 'date_picker',
												'date_format' => 'yymmdd',
												'display_format' => 'mm/dd/yy',
												'first_day' => 1,
											),
											array (
												'key' => 'field_82cqctpbywhm37',
												'label' => __('Date end'),
												'name' => 'date_end',
												'type' => 'date_picker',
												'date_format' => 'yymmdd',
												'display_format' => 'mm/dd/yy',
												'first_day' => 1,
											),
											array (
												'key' => 'field_7778s58c6e011d',
												'label' => __('Class'),
												'name' => 'class',
												'type' => 'text',
												'column_width' => '',
												'default_value' => '',
											),
										),
									),
									array (
										'label' => __('Days'),
										'name' => 'days',
										'display' => 'row',
										'min' => '',
										'max' => '',
										'sub_fields' => array (
											array (
												'key' => 'field_ipve58ql3ryqjv',
												'label' => __('Days'),
												'name' => 'days',
												'type' => 'repeater',
												'sub_fields' => array (
													array (
														'key' => 'field_it2axg4l0xdvbv',
														'label' => __('Day'),
														'name' => 'day',
														'type' => 'date_picker',
														'column_width' => '',
														'date_format' => 'yymmdd',
														'display_format' => 'mm/dd/yy',
														'first_day' => 1,
													),
													array (
														'key' => 'field_7778s58c6e011d',
														'label' => __('Class'),
														'name' => 'class',
														'type' => 'text',
														'column_width' => '',
														'default_value' => '',
													),
												),
												'row_min' => '',
												'row_limit' => '',
												'layout' => 'table',
												'button_label' => 'Add Day',
											),
											array (
												'key' => 'field_7778s58c6e011d',
												'label' => __('Class'),
												'name' => 'class',
												'type' => 'text',
												'column_width' => '',
												'default_value' => '',
											),
										),
									),
									array (
										'label' => __('Editor'),
										'name' => 'editor',
										'display' => 'row',
										'min' => '',
										'max' => '',
										'sub_fields' => array (
											array (
												'key' => 'field_bs9fch9x6x00ua',
												'label' => __('Editors'),
												'name' => 'editor',
												'type' => 'repeater',
												'column_width' => '',
												'sub_fields' => array (
													array (
														'key' => 'field_x3e0353vexvhbl',
														'label' => __('Editor'),
														'name' => 'editor',
														'type' => 'wysiwyg',
														'column_width' => '',
														'default_value' => '',
														'toolbar' => 'full',
														'media_upload' => 'yes',
													),
												),
												'row_min' => '',
												'row_limit' => '',
												'layout' => 'row',
												'button_label' => 'Add an Editor',
											),
											array (
												'key' => 'field_7778s58c6e011d',
												'label' => __('Class'),
												'name' => 'class',
												'type' => 'text',
												'column_width' => '',
												'default_value' => '',
											),
										),
									),
									array (
										'label' => __('Email'),
										'name' => 'email',
										'display' => 'row',
										'min' => '',
										'max' => '',
										'sub_fields' => array (
											array (
												'key' => 'field_528cfs544504',
												'label' => __('Email'),
												'name' => 'email',
												'type' => 'email',
												'default_value' => '',
												'placeholder' => '',
												'prepend' => '',
												'append' => '',
											),
										),
									),
									array (
										'label' => __('Excerpt'),
										'name' => 'excerpt',
										'display' => 'row',
										'min' => '',
										'max' => '',
										'sub_fields' => array (
											array (
												'key' => 'field_vcpouknl4er5',
												'label' => __('Excerpt'),
												'name' => 'excerpt',
												'type' => 'text',
												'column_width' => '',
											),
										),
									),
									array (
										'label' => __('Full Name'),
										'name' => 'full_name',
										'display' => 'row',
										'min' => '',
										'max' => '',
										'sub_fields' => array (
											array (
												'key' => 'field_vcpouknlad8uo',
												'label' => __('First name'),
												'name' => 'first_name',
												'type' => 'text',
												'column_width' => '',
											),
											array (
												'key' => 'field_vcpou6455fd8uo',
												'label' => __('Last name'),
												'name' => 'last_name',
												'type' => 'text',
												'column_width' => '',
											),
										),
									),
									array (
										'label' => __('Heading'),
										'name' => 'heading',
										'display' => 'row',
										'min' => '',
										'max' => '',
										'sub_fields' => array (
											array (
												'key' => 'field_l24cozxgl2jga4',
												'label' => __('Heading'),
												'name' => 'heading',
												'type' => 'text',
												'column_width' => '',
												'default_value' => '',
												'placeholder' => '',
												'prepend' => '',
												'append' => '',
												'formatting' => 'html',
												'maxlength' => '',
											),
											array (
												'key' => 'field_g18v71t674x13k',
												'label' => __('Heading type'),
												'name' => 'heading_type',
												'type' => 'select',
												'column_width' => '',
												'choices' => array (
													'heading_1' => 'Heading 1',
													'heading_2' => 'Heading 2',
													'heading_3' => 'Heading 3',
													'heading_4' => 'Heading 4',
												),
												'default_value' => 'heading_2',
												'allow_null' => 0,
												'multiple' => 0,
											),
											array (
												'key' => 'field_cw90ttw88rrfv6',
												'label' => __('Link'),
												'name' => 'link',
												'type' => 'text',
												'column_width' => '',
												'default_value' => '',
												'placeholder' => '',
												'prepend' => '',
												'append' => '',
												'formatting' => 'html',
												'maxlength' => '',
											),
											array (
												'key' => 'field_nzlfwjf17t6k4o',
												'label' => __('New window'),
												'name' => 'new_window',
												'type' => 'true_false',
												'column_width' => '',
												'message' => '',
												'default_value' => 0,
											),
											array (
												'key' => 'field_7778s58c6e011d',
												'label' => __('Class'),
												'name' => 'class',
												'type' => 'text',
												'column_width' => '',
												'default_value' => '',
											),
										),
									),
									array (
										'label' => __('Image'),
										'name' => 'image',
										'display' => 'row',
										'min' => '',
										'max' => '',
										'sub_fields' => array (
											array (
												'key' => 'field_96w61d29k9d2qf',
												'label' => __('Image'),
												'name' => 'image',
												'type' => 'image',
												'column_width' => '',
												'default_value' => '',
												'placeholder' => '',
												'prepend' => '',
												'append' => '',
												'formatting' => 'html',
												'maxlength' => '',
											),
											array (
												'key' => 'field_t8noz6201ou07v',
												'label' => __('Image link'),
												'name' => 'image_link',
												'type' => 'text',
												'column_width' => '',
												'default_value' => '',
												'placeholder' => '',
												'prepend' => '',
												'append' => '',
												'formatting' => 'html',
												'maxlength' => '',
											),
											array (
												'key' => 'field_lfxang6v7hdux7',
												'label' => __('New window'),
												'name' => 'new_window',
												'type' => 'true_false',
												'column_width' => '',
												'message' => '',
												'default_value' => 0,
											),
											array (
												'key' => 'field_7778s58c6e011d',
												'label' => __('Class'),
												'name' => 'class',
												'type' => 'text',
												'column_width' => '',
												'default_value' => '',
											),
										),
									),
									array (
										'label' => __('Image carousel'),
										'name' => 'image_carousel',
										'display' => 'row',
										'min' => '',
										'max' => '',
										'sub_fields' => array (
											array (
												'key' => 'field_unf45mauh6vjlm',
												'label' => __('Images'),
												'name' => 'images',
												'type' => 'gallery',
												'column_width' => '',
												'preview_size' => 'thumbnail',
												'library' => 'all',
											),
										),
									),
									array (
										'label' => __('Image gallery'),
										'name' => 'image_gallery',
										'display' => 'row',
										'min' => '',
										'max' => '',
										'sub_fields' => array (
											array (
												'key' => 'field_tyur86dmjv71xd',
												'label' => __('Images'),
												'name' => 'images',
												'type' => 'gallery',
												'column_width' => '',
												'preview_size' => 'thumbnail',
												'library' => 'all',
											),
											array (
												'key' => 'field_7778s58c6e011d',
												'label' => __('Class'),
												'name' => 'class',
												'type' => 'text',
												'column_width' => '',
												'default_value' => '',
											),
										),
									),
									array (
										'label' => __('Image link gallery'),
										'name' => 'image_link_gallery',
										'display' => 'row',
										'min' => '',
										'max' => '',
										'sub_fields' => array (
											array (
												'key' => 'field_12ds66sees4d65465',
												'label' => __('Images'),
												'name' => 'images',
												'type' => 'gallery',
												'column_width' => '',
												'preview_size' => 'thumbnail',
												'library' => 'all',
											),
											array (
												'key' => 'field_12s99xxsscbkos',
												'label' => __('Columns'),
												'name' => 'columns',
												'type' => 'number',
												'column_width' => 15,
												'placeholder' => '',
												'min' => 1,
												'max' => '',
											),
											array (
												'key' => 'field_7778s58c6e011d',
												'label' => __('Class'),
												'name' => 'class',
												'type' => 'text',
												'column_width' => '',
												'default_value' => '',
											),
										),
									),
									array (
										'label' => __('Image rotator'),
										'name' => 'image_rotator',
										'display' => 'row',
										'min' => '',
										'max' => '',
										'sub_fields' => array (
											array (
												'key' => 'field_y5xky8x2td04vw',
												'label' => __('Images'),
												'name' => 'images',
												'type' => 'gallery',
												'column_width' => '',
												'preview_size' => 'thumbnail',
												'library' => 'all',
											),
											array (
												'key' => 'field_7778s58c6e011d',
												'label' => __('Class'),
												'name' => 'class',
												'type' => 'text',
												'column_width' => '',
												'default_value' => '',
											),
										),
									),
									array (
										'label' => __('Image with hover'),
										'name' => 'image_with_hover',
										'display' => 'row',
										'min' => '',
										'max' => '',
										'sub_fields' => array (
											array (
												'key' => 'field_g4x9zsd269kgll',
												'label' => __('Image'),
												'name' => 'image',
												'type' => 'image',
												'column_width' => '',
												'save_format' => 'object',
												'preview_size' => 'thumbnail',
												'library' => 'all',
											),
											array (
												'key' => 'field_6nnmsdx0j0x6m1',
												'label' => __('Hover image'),
												'name' => 'hover_image',
												'type' => 'image',
												'column_width' => '',
												'save_format' => 'object',
												'preview_size' => 'thumbnail',
												'library' => 'all',
											),
											array (
												'key' => 'field_mrv4u8vhj10hzd',
												'label' => __('Link'),
												'name' => 'link',
												'type' => 'text',
												'column_width' => '',
												'default_value' => '',
												'placeholder' => '',
												'prepend' => '',
												'append' => '',
												'formatting' => 'html',
												'maxlength' => '',
											),
											array (
												'key' => 'field_1c5f84dbin05pr',
												'label' => __('New Window'),
												'name' => 'new_window',
												'type' => 'true_false',
												'column_width' => '',
												'message' => '',
												'default_value' => 0,
											),
											array (
												'key' => 'field_7778s58c6e011d',
												'label' => __('Class'),
												'name' => 'class',
												'type' => 'text',
												'column_width' => '',
												'default_value' => '',
											),
										),
									),
									array (
										'label' => __('Main image'),
										'name' => 'main_image',
										'display' => 'row',
										'min' => '',
										'max' => '',
										'sub_fields' => array (
											array (
												'key' => 'field_963dflwmrncucg',
												'label' => __('Image'),
												'name' => 'image',
												'type' => 'image',
												'column_width' => '',
												'save_format' => 'object',
												'preview_size' => 'thumbnail',
												'library' => 'all',
											),
											array (
												'key' => 'field_7778s58c6e011d',
												'label' => __('Class'),
												'name' => 'class',
												'type' => 'text',
												'column_width' => '',
												'default_value' => '',
											),
										),
									),
									array (
										'label' => __('Map'),
										'name' => 'map',
										'display' => 'row',
										'min' => '',
										'max' => '',
										'sub_fields' => array (
											array (
												'key' => 'field_48odhep6z5ubsx',
												'label' => __('Map'),
												'name' => 'map',
												'type' => 'google_map',
												'column_width' => '',
												'center_lat' => '',
												'center_lng' => '',
												'height' => '',
											),
											array (
												'key' => 'field_9itcwqmouhrhd9',
												'label' => __('Map height'),
												'name' => 'map_height',
												'type' => 'number',
												'instructions' => __('Please enter the map height'),
												'column_width' => 15,
												'default_value' => 300,
												'placeholder' => '',
												'prepend' => '',
												'append' => 'px',
												'min' => 50,
												'max' => '',
												'step' => '',
											),
											array (
												'key' => 'field_o1n2zq18nujd0m',
												'label' => __('Style ID'),
												'name' => 'style_id',
												'type' => 'text',
												'instructions' => __('This is the ID of the map style you desire an ID can be retrieved from http://maps.cloudmade.com/editor'),
												'column_width' => '',
												'default_value' => 1714,
												'placeholder' => '',
												'prepend' => '',
												'append' => '',
												'formatting' => 'html',
												'maxlength' => '',
											),
											array (
												'key' => 'field_rfe6leswfxfshq',
												'label' => __('Zoom level'),
												'name' => 'zoom_level',
												'type' => 'number',
												'column_width' => '',
												'default_value' => 3,
												'placeholder' => '',
												'prepend' => '',
												'append' => '',
												'min' => 0,
												'max' => 18,
												'step' => '',
											),
											array (
												'key' => 'field_thrg1s669z9umy',
												'label' => __('Markers'),
												'name' => 'markers',
												'type' => 'repeater',
												'column_width' => '',
												'sub_fields' => array (
													array (
														'key' => 'field_oh46oz690dhm7f',
														'label' => __('Location'),
														'name' => 'location',
														'type' => 'google_map',
														'column_width' => '',
														'center_lat' => '',
														'center_lng' => '',
														'height' => '',
													),
													array (
														'key' => 'field_b01bj7kb94jf9e',
														'label' => __('Image'),
														'name' => 'image',
														'type' => 'image',
														'instructions' => __('Add caption and text to image view on maker'),
														'column_width' => '',
														'save_format' => 'object',
														'preview_size' => 'thumbnail',
														'library' => 'all',
													),
													array (
														'key' => 'field_7778s58c6e011d',
														'label' => __('Class'),
														'name' => 'class',
														'type' => 'text',
														'column_width' => '',
														'default_value' => '',
													),
												),
												'row_min' => '',
												'row_limit' => '',
												'layout' => 'row',
												'button_label' => 'Add a Map Marker',
											),
										),
									),
									array (
										'label' => __('PDF link'),
										'name' => 'pdf_link',
										'display' => 'row',
										'min' => '',
										'max' => '',
										'sub_fields' => array (
											array (
												'key' => 'field_7kh7iwpfqtlk2k',
												'label' => __('Text'),
												'name' => 'text',
												'type' => 'text',
												'column_width' => '',
												'default_value' => '',
												'placeholder' => '',
												'prepend' => '',
												'append' => '',
												'formatting' => 'html',
												'maxlength' => '',
											),
											array (
												'key' => 'field_1rr9xa8vq1b8i8',
												'label' => __('Text type'),
												'name' => 'text_type',
												'type' => 'select',
												'column_width' => '',
												'choices' => array (
													'heading_1' => 'Heading 1',
													'heading_2' => 'Heading 2',
													'heading_3' => 'Heading 3',
													'heading_4' => 'Heading 4',
													'paragraph_text' => 'Paragraph text',
												),
												'default_value' => 'paragraph_text',
												'allow_null' => 0,
												'multiple' => 0,
											),
											array (
												'key' => 'field_jcmyqhcq1a8u9w',
												'label' => __('PDF'),
												'name' => 'pdf',
												'type' => 'file',
												'column_width' => '',
												'save_format' => 'object',
												'library' => 'all',
											),
											array (
												'key' => 'field_q0rmfj5tzmjf5a',
												'label' => __('New window'),
												'name' => 'new_window',
												'type' => 'true_false',
												'column_width' => '',
												'message' => '',
												'default_value' => 0,
											),
											array (
												'key' => 'field_7778s58c6e011d',
												'label' => __('Class'),
												'name' => 'class',
												'type' => 'text',
												'column_width' => '',
												'default_value' => '',
											),
										),
									),
									array (
										'label' => __('Sub menu'),
										'name' => 'sub_menu',
										'display' => 'row',
										'min' => '',
										'max' => '',
										'sub_fields' => array (
											array (
												'key' => 'field_onbdnuqiwtg6n1',
												'label' => __('Primary header menu'),
												'name' => 'primary_header_menu',
												'type' => 'true_false',
												'column_width' => '',
												'message' => '',
												'default_value' => 1,
											),
											array (
												'key' => 'field_02z62n93upvymx',
												'label' => __('Custom theme menu location'),
												'name' => 'custom_theme_menu_location',
												'type' => 'text',
												'column_width' => '',
											),
										),
									),
									array (
										'label' => __('Text link'),
										'name' => 'text_link',
										'display' => 'row',
										'min' => '',
										'max' => '',
										'sub_fields' => array (
											array (
												'key' => 'field_e6uevc1x40vi13',
												'label' => __('Text links'),
												'name' => 'text_link',
												'type' => 'repeater',
												'column_width' => '',
												'sub_fields' => array (
													array (
														'key' => 'field_q6jdsraag9fl6v',
														'label' => __('Text'),
														'name' => 'text',
														'type' => 'text',
														'column_width' => '',
														'default_value' => '',
														'placeholder' => '',
														'prepend' => '',
														'append' => '',
														'formatting' => 'html',
														'maxlength' => '',
													),
													array (
														'key' => 'field_kgkd9296nr57t8',
														'label' => __('Link'),
														'name' => 'link',
														'type' => 'text',
														'column_width' => '',
														'default_value' => '',
														'placeholder' => '',
														'prepend' => '',
														'append' => '',
														'formatting' => 'html',
														'maxlength' => '',
													),
													array (
														'key' => 'field_f6mg1b3upfcr8e',
														'label' => __('New window'),
														'name' => 'new_window',
														'type' => 'true_false',
														'column_width' => '',
														'message' => '',
														'default_value' => 0,
													),
													array (
														'key' => 'field_7778s58c6e011d',
														'label' => __('Class'),
														'name' => 'class',
														'type' => 'text',
														'column_width' => '',
														'default_value' => '',
													),
												),
												'row_min' => '',
												'row_limit' => '',
												'layout' => 'row',
												'button_label' => 'Add a Text Link',
											),
											array (
												'key' => 'field_7778s58c6e011d',
												'label' => __('Class'),
												'name' => 'class',
												'type' => 'text',
												'column_width' => '',
												'default_value' => '',
											),
										),
									),
									array (
										'label' => __('Text to image link'),
										'name' => 'text_to_image_link',
										'display' => 'row',
										'min' => '',
										'max' => '',
										'sub_fields' => array (
											array (
												'key' => 'field_aqwum90dmff5wx',
												'label' => __('Text'),
												'name' => 'text',
												'type' => 'text',
												'column_width' => '',
												'default_value' => '',
												'placeholder' => '',
												'prepend' => '',
												'append' => '',
												'formatting' => 'html',
												'maxlength' => '',
											),
											array (
												'key' => 'field_dnv7rb2gre0l1v',
												'label' => __('Text type'),
												'name' => 'text_type',
												'type' => 'select',
												'column_width' => '',
												'choices' => array (
													'heading_1' => 'Heading 1',
													'heading_2' => 'Heading 2',
													'heading_3' => 'Heading 3',
													'heading_4' => 'Heading 4',
													'paragraph_text' => 'Paragraph text',
												),
												'default_value' => 'paragraph_text',
												'allow_null' => 0,
												'multiple' => 0,
											),
											array (
												'key' => 'field_vvrc1h9c8dgrzh',
												'label' => __('Image'),
												'name' => 'image',
												'type' => 'image',
												'column_width' => '',
												'save_format' => 'object',
												'preview_size' => 'thumbnail',
												'library' => 'all',
											),
											array (
												'key' => 'field_7778s58c6e011d',
												'label' => __('Class'),
												'name' => 'class',
												'type' => 'text',
												'column_width' => '',
												'default_value' => '',
											),
										),
									),
									array (
										'label' => __('Text rotator'),
										'name' => 'text_rotator',
										'display' => 'row',
										'min' => '',
										'max' => '',
										'sub_fields' => array (
											array (
												'key' => 'field_7q1wnl543xivr1',
												'label' => __('Heading'),
												'name' => 'heading',
												'type' => 'text',
												'column_width' => '',
												'default_value' => '',
												'placeholder' => '',
												'prepend' => '',
												'append' => '',
												'formatting' => 'html',
												'maxlength' => '',
											),
											array (
												'key' => 'field_pfcfgidyoqyv6k',
												'label' => __('Heading type'),
												'name' => 'heading_type',
												'type' => 'select',
												'column_width' => '',
												'choices' => array (
													'heading_1' => 'Heading 1',
													'heading_2' => 'Heading 2',
													'heading_3' => 'Heading 3',
													'heading_4' => 'Heading 4',
													'paragraph_text' => 'Paragraph text',
												),
												'default_value' => 'paragraph_text',
												'allow_null' => 0,
												'multiple' => 0,
											),
											array (
												'key' => 'field_rn9rqzu10dkmw1',
												'label' => __('Texts'),
												'name' => 'text',
												'type' => 'repeater',
												'column_width' => '',
												'sub_fields' => array (
													array (
														'key' => 'field_qd4u9aev7iv7ml',
														'label' => __('Text'),
														'name' => 'text',
														'type' => 'text',
														'column_width' => '',
														'default_value' => '',
														'placeholder' => '',
														'prepend' => '',
														'append' => '',
														'formatting' => 'html',
														'maxlength' => '',
													),
													array (
														'key' => 'field_7778s58c6e011d',
														'label' => __('Class'),
														'name' => 'class',
														'type' => 'text',
														'column_width' => '',
														'default_value' => '',
													),
												),
												'row_min' => '',
												'row_limit' => '',
												'layout' => 'table',
												'button_label' => 'Add Text',
											),
											array (
												'key' => 'field_7778s58c6e011d',
												'label' => __('Class'),
												'name' => 'class',
												'type' => 'text',
												'column_width' => '',
												'default_value' => '',
											),
										),
									),
									array (
										'label' => __('Title'),
										'name' => 'title',
										'display' => 'row',
										'min' => '',
										'max' => '',
										'sub_fields' => array (
											array (
												'key' => 'field_ad4f165346276',
												'label' => __('Title'),
												'name' => 'title',
												'type' => 'true_false',
												'column_width' => '',
												'message' => '',
												'default_value' => 1,
											),
											array (
												'key' => 'field_tyutyiy6deee25654',
												'label' => __('Title type'),
												'name' => 'title_type',
												'type' => 'select',
												'column_width' => '',
												'choices' => array (
													'heading_1' => 'Heading 1',
													'heading_2' => 'Heading 2',
													'heading_3' => 'Heading 3',
													'heading_4' => 'Heading 4',
												),
												'default_value' => 'heading_1',
												'allow_null' => 0,
												'multiple' => 0,
											),
											array (
												'key' => 'field_rtyrt87960a',
												'label' => __('Link'),
												'name' => 'link',
												'type' => 'text',
												'column_width' => '',
												'default_value' => '',
												'placeholder' => '',
												'prepend' => '',
												'append' => '',
												'formatting' => 'html',
												'maxlength' => '',
											),
											array (
												'key' => 'field_rtytryrtyrty787',
												'label' => __('New window'),
												'name' => 'new_window',
												'type' => 'true_false',
												'column_width' => '',
												'message' => '',
												'default_value' => 0,
											),
											array (
												'key' => 'field_rty44fe011d',
												'label' => __('Class'),
												'name' => 'class',
												'type' => 'text',
												'column_width' => '',
												'default_value' => '',
											),
										),
									),
									array (
										'label' => __('Vimeo'),
										'name' => 'vimeo',
										'display' => 'row',
										'min' => '',
										'max' => '',
										'sub_fields' => array (
											array (
												'key' => 'field_yhvfhctkiennxl',
												'label' => __('Heading'),
												'name' => 'heading',
												'type' => 'text',
												'column_width' => '',
												'default_value' => '',
												'placeholder' => '',
												'prepend' => '',
												'append' => '',
												'formatting' => 'html',
												'maxlength' => '',
											),
											array (
												'key' => 'field_bnbsdengn00ul0',
												'label' => __('Video link'),
												'name' => 'video_link',
												'type' => 'text',
												'column_width' => '',
												'default_value' => '',
												'placeholder' => '',
												'prepend' => '',
												'append' => '',
												'formatting' => 'html',
												'maxlength' => '',
											),
											array (
												'key' => 'field_dn8pgta8tls5x7',
												'label' => __('Video image'),
												'name' => 'video_image',
												'type' => 'image',
												'column_width' => '',
												'save_format' => 'object',
												'preview_size' => 'thumbnail',
												'library' => 'all',
											),
											array (
												'key' => 'field_oth2vxw2okq5oa',
												'label' => __('Heading type'),
												'name' => 'heading_type',
												'type' => 'select',
												'column_width' => '',
												'choices' => array (
												),
												'default_value' => '',
												'allow_null' => 0,
												'multiple' => 0,
											),
											array (
												'key' => 'field_7778s58c6e011d',
												'label' => __('Class'),
												'name' => 'class',
												'type' => 'text',
												'column_width' => '',
												'default_value' => '',
											),
										),
									),
									array (
										'label' => __('Youtube'),
										'name' => 'youtube',
										'display' => 'row',
										'min' => '',
										'max' => '',
										'sub_fields' => array (
											array (
												'key' => 'field_h2lmob17pxs4zv',
												'label' => __('Heading'),
												'name' => 'heading',
												'type' => 'text',
												'column_width' => '',
												'default_value' => '',
												'placeholder' => '',
												'prepend' => '',
												'append' => '',
												'formatting' => 'html',
												'maxlength' => '',
											),
											array (
												'key' => 'field_e1mkup32bzhw67',
												'label' => __('Video link'),
												'name' => 'video_link',
												'type' => 'text',
												'column_width' => '',
												'default_value' => '',
												'placeholder' => '',
												'prepend' => '',
												'append' => '',
												'formatting' => 'html',
												'maxlength' => '',
											),
											array (
												'key' => 'field_idvo2vmq8xt3mw',
												'label' => __('Video image'),
												'name' => 'video_image',
												'type' => 'image',
												'column_width' => '',
												'save_format' => 'object',
												'preview_size' => 'thumbnail',
												'library' => 'all',
											),
											array (
												'key' => 'field_cji484z295l5i4',
												'label' => __('Heading type'),
												'name' => 'heading_type',
												'type' => 'select',
												'column_width' => '',
												'choices' => array (
													'heading_1' => 'Heading 1',
													'heading_2' => 'Heading 2',
													'heading_3' => 'Heading 3',
													'heading_4' => 'Heading 4',
													'paragraph_text' => 'Paragraph text',
												),
												'default_value' => 'paragraph_text',
												'allow_null' => 0,
												'multiple' => 0,
											),
											array (
												'key' => 'field_7778s58c6e011d',
												'label' => __('Class'),
												'name' => 'class',
												'type' => 'text',
												'column_width' => '',
												'default_value' => '',
											),
										),
									),
								),
								'button_label' => 'Add an Item',
								'min' => '',
								'max' => '',
							),
						),
						'row_min' => '',
						'row_limit' => '',
						'layout' => 'row',
						'button_label' => 'Add a Nested Unit',
					),
				),
				'row_min' => '',
				'row_limit' => '',
				'layout' => 'row',
				'button_label' => 'Add a Unit',
				),
			),
			'location' => array (
				array (
					array (
						'param' => 'page_template',
						'operator' => '!=',
						'value' => 'default',
						'order_no' => 0,
						'group_no' => 0,
					),
					array (
						'param' => 'page_template',
						'operator' => '!=',
						'value' => 'archive.php',
						'order_no' => 0,
						'group_no' => 1,
					),
					array (
						'param' => 'page_template',
						'operator' => '!=',
						'value' => 'taxonomy.php',
						'order_no' => 0,
						'group_no' => 1,
					),
					array (
						'param' => 'taxonomy',
						'operator' => '!=',
						'value' => '1',
						'order_no' => 0,
						'group_no' => 0,
					),
				),
			),
			'options' => array (
				'position' => 'normal',
				'layout' => 'no_box',
				'hide_on_screen' => array (
					0 => 'the_content',
				),
			),
			'menu_order' => 0,
		));
}
?>