<?php
if(function_exists("register_field_group"))
{
	register_field_group(array (
		'id' => 'acf_taxonomy-content',
		'title' => 'Taxonomy Content',
		'fields' => array (
			array (
				'key' => 'field_sdfssdf7136ad',
				'label' => __('Taxonomy Grid'),
				'name' => 'taxonomy_grid',
				'type' => 'repeater',
				'sub_fields' => array (
					array (
						'key' => 'field_56s4df6s6546sdfnw1',
						'label' => __('Unit Span'),
						'name' => 'unit_span',
						'type' => 'select',
						'column_width' => '',
						'choices' => array (
							'one-of-one' => 'One of one',
							'one-of-two' => 'One of two',
							'one-of-three' => 'One of three',
							'one-of-four' => 'One of four',
							'one-of-five' => 'One of five',
							'two-of-three' => 'Two of three',
							'two-of-five' => 'Two of five',
							'three-of-four' => 'Three of four',
							'three-of-five' => 'Three of five',
							'four-of-five' => 'Four of five',
						),
						'default_value' => 'one-of-one',
						'allow_null' => 0,
						'multiple' => 0,
					),
					array (
						'key' => 'field_7778s5888ds8d88sd',
						'label' => __('Class'),
						'name' => 'class',
						'type' => 'text',
						'column_width' => '',
						'default_value' => '',
					),
					array (
						'key' => 'field_esfd5sdf456s65465nukmy',
						'label' => __('Unit'),
						'name' => 'unit',
						'type' => 'repeater',
						'sub_fields' => array (
							array (
								'key' => 'field_sf4s545465487swwlmlrlq2',
								'label' => __('Nested Unit Span'),
								'name' => 'nested_unit_span',
								'type' => 'select',
								'column_width' => '',
								'choices' => array (
									'one-of-one' => 'Nested -- One of one',
									'one-of-two' => 'Nested -- One of two',
									'one-of-three' => 'Nested -- One of three',
									'one-of-four' => 'Nested -- One of four',
									'one-of-five' => 'Nested -- One of five',
									'two-of-three' => 'Nested -- Two of three',
									'two-of-five' => 'Nested -- Two of five',
									'three-of-four' => 'Nested -- Three of four',
									'three-of-five' => 'Nested -- Three of five',
									'four-of-five' => 'Nested -- Four of five',
								),
								'default_value' => 'one-of-one',
								'allow_null' => 0,
								'multiple' => 0,
							),
							array (
								'key' => 'field_7778s5888ds8d88sd',
								'label' => __('Class'),
								'name' => 'class',
								'type' => 'text',
								'column_width' => '',
								'default_value' => '',
							),
							array (
								'key' => 'field_3y8919sdfjutnmjfs',
								'label' => __('Nested Unit'),
								'name' => 'nested_unit',
								'type' => 'flexible_content',
								'column_width' => '',
								'layouts' => array (
									array (
										'label' => __('Accordion button'),
										'name' => 'accordion_button',
										'display' => 'row',
										'min' => '',
										'max' => '',
										'sub_fields' => array (
											array (
												'key' => 'field_ocvb6334417ya4o',
												'label' => __('Button text'),
												'name' => 'button_text',
												'type' => 'text',
												'column_width' => '',
												'default_value' => '',
												'placeholder' => '',
												'prepend' => '',
												'append' => '',
												'formatting' => 'html',
												'maxlength' => '',
											),
											array (
												'key' => 'field_6b9c5b59951ntyl',
												'label' => __('Editor'),
												'name' => 'editor',
												'type' => 'text',
												'column_width' => '',
												'default_value' => '',
												'placeholder' => '',
												'prepend' => '',
												'append' => '',
												'formatting' => 'html',
												'maxlength' => '',
											),
											array (
												'key' => 'field_7778s5888ds8d88sd',
												'label' => __('Class'),
												'name' => 'class',
												'type' => 'text',
												'column_width' => '',
												'default_value' => '',
											),
										),
									),
									array (
										'label' => __('Accordion editor'),
										'name' => 'accordion_editor',
										'display' => 'row',
										'min' => '',
										'max' => '',
										'sub_fields' => array (
											array (
												'key' => 'field_nt19n19t1nns9k',
												'label' => __('Heading type'),
												'name' => 'heading_type',
												'type' => 'select',
												'column_width' => '',
												'choices' => array (
													'heading_1' => 'Heading 1',
													'heading_2' => 'Heading 2',
													'heading_3' => 'Heading 3',
													'heading_4' => 'Heading 4',
													'paragraph_text' => 'Paragraph text',
												),
												'default_value' => 'paragraph_text',
												'allow_null' => 0,
												'multiple' => 0,
											),
											array (
												'key' => 'field_mu28um28u84829',
												'label' => __('Accordions'),
												'name' => 'accordion',
												'type' => 'repeater',
												'column_width' => '',
												'sub_fields' => array (
													array (
														'key' => 'field_3mu9m3i9wtv7wni',
														'label' => __('Heading'),
														'name' => 'heading',
														'type' => 'text',
														'column_width' => '',
														'default_value' => '',
														'placeholder' => '',
														'prepend' => '',
														'append' => '',
														'formatting' => 'html',
														'maxlength' => '',
													),
													array (
														'key' => 'field_3q8b9tyny9jww',
														'label' => __('Editor'),
														'name' => 'editor',
														'type' => 'wysiwyg',
														'column_width' => '',
														'default_value' => '',
														'toolbar' => 'full',
														'media_upload' => 'yes',
													),
												),
												'row_min' => '',
												'row_limit' => '',
												'layout' => 'row',
												'button_label' => 'Add an Accordion',
											),
											array (
												'key' => 'field_7778s5888ds8d88sd',
												'label' => __('Class'),
												'name' => 'class',
												'type' => 'text',
												'column_width' => '',
												'default_value' => '',
											),
										),
									),
									array (
										'label' => __('Accordion links'),
										'name' => 'accordion_links',
										'display' => 'row',
										'min' => '',
										'max' => '',
										'sub_fields' => array (
											array (
												'key' => 'field_t80st64tit6k4tth',
												'label' => __('Heading type'),
												'name' => 'heading_type',
												'type' => 'select',
												'column_width' => '',
												'choices' => array (
													'heading_1' => 'Heading 1',
													'heading_2' => 'Heading 2',
													'heading_3' => 'Heading 3',
													'heading_4' => 'Heading 4',
													'paragraph_text' => 'Paragraph text',
												),
												'default_value' => 'paragraph_text',
												'allow_null' => 0,
												'multiple' => 0,
											),
											array (
												'key' => 'field_3y1ve9ewfnm',
												'label' => __('Accordions'),
												'name' => 'accordion',
												'type' => 'repeater',
												'column_width' => '',
												'sub_fields' => array (
													array (
														'key' => 'field_fhgf29pg0ry',
														'label' => __('Heading'),
														'name' => 'heading',
														'type' => 'text',
														'column_width' => 3,
														'default_value' => '',
														'placeholder' => '',
														'prepend' => '',
														'append' => '',
														'formatting' => 'html',
														'maxlength' => '',
													),
													array (
														'key' => 'field_lnb3yza4cruzi9',
														'label' => __('Links'),
														'name' => 'links',
														'type' => 'repeater',
														'column_width' => '',
														'sub_fields' => array (
															array (
																'key' => 'field_xndr1qep3w9z3xw',
																'label' => __('Text'),
																'name' => 'text',
																'type' => 'text',
																'column_width' => '',
																'default_value' => '',
																'placeholder' => '',
																'prepend' => '',
																'append' => '',
																'formatting' => 'html',
																'maxlength' => '',
															),
															array (
																'key' => 'field_zw39xfeg0usj',
																'label' => __('Text 2'),
																'name' => 'text_2',
																'type' => 'text',
																'column_width' => '',
																'default_value' => '',
																'placeholder' => '',
																'prepend' => '',
																'append' => '',
																'formatting' => 'html',
																'maxlength' => '',
															),
															array (
																'key' => 'field_4aiwow5fw1144447',
																'label' => __('Text 2 type'),
																'name' => 'text_2_type',
																'type' => 'select',
																'instructions' => __('Choose type for text 2'),
																'column_width' => '',
																'choices' => array (
																	'text' => 'Text',
																	'class' => 'Class',
																	'url' => 'URL',
																),
																'default_value' => '',
																'allow_null' => 1,
																'multiple' => 0,
															),
														),
														array (
															'key' => 'field_7778s5888ds8d88sd',
															'label' => __('Class'),
															'name' => 'class',
															'type' => 'text',
															'column_width' => '',
															'default_value' => '',
														),
														'row_min' => '',
														'row_limit' => '',
														'layout' => 'row',
														'button_label' => 'Add a link',
													),
													array (
														'key' => 'field_7778s5888ds8d88sd',
														'label' => __('Class'),
														'name' => 'class',
														'type' => 'text',
														'column_width' => '',
														'default_value' => '',
													),
												),
												'row_min' => '',
												'row_limit' => '',
												'layout' => 'row',
												'button_label' => 'Add an Accordion',
											),
											array (
												'key' => 'field_7778s5888ds8d88sd',
												'label' => __('Class'),
												'name' => 'class',
												'type' => 'text',
												'column_width' => '',
												'default_value' => '',
											),
										),
									),
									array (
										'label' => __('Taxonomy'),
										'name' => 'taxonomy',
										'display' => 'row',
										'min' => '',
										'max' => '',
										'sub_fields' => array (
											array (
												'key' => 'field_w4ef6qw4fqfe6c',
												'label' => __('Post Per Page'),
												'name' => 'post_per_page',
												'type' => 'number',
												'instructions' => __(''),
												'column_width' => 15,
												'default_value' => 10,
												'placeholder' => '',
												'prepend' => '',
												'append' => '',
												'min' => -1,
												'max' => '',
												'step' => '',
											),
											array (
												'key' => 'field_wegf1w91hlrlq2',
												'label' => __('Taxonomy Unit Span'),
												'name' => 'taxonomy_unit_span',
												'type' => 'select',
												'column_width' => '',
												'choices' => array (
													'one-of-one' => 'One of one',
													'one-of-two' => 'One of two',
													'one-of-three' => 'One of three',
													'one-of-four' => 'One of four',
													'one-of-five' => 'One of five',
													'two-of-three' => 'Two of three',
													'two-of-five' => 'Two of five',
													'three-of-four' => 'Three of four',
													'three-of-five' => 'Three of five',
													'four-of-five' => 'Four of five',
												),
												'default_value' => 'one-of-one',
												'allow_null' => 0,
												'multiple' => 0,
											),
											array (
												'key' => 'field_5qp93q9qds10',
												'label' => __('Filter by'),
												'name' => 'filter_by',
												'type' => 'select',
												'column_width' => '',
												'choices' => array (
													'start_date' => 'Start date',
													'published_date' => 'Published date',
													'last_name' => 'Last Name',
												),
												'default_value' => 'published_date',
												'allow_null' => 0,
												'multiple' => 0,
											),
											array (
												'key' => 'field_5qw4w4qqqons10',
												'label' => __('Elements to Display'),
												'name' => 'elements',
												'type' => 'repeater',
												'column_width' => '',
												'sub_fields' => array (
													array (
														'key' => 'field_df0efs59529wse3',
														'label' => __('Element'),
														'name' => 'element',
														'type' => 'select',
														'column_width' => '',
														'choices' => array (
															'byline' => 'Byline',
															'dates' => 'Dates',
															'days' => 'Days',
															'email' => 'Email',
															'excerpt' => 'Excerpt',
															'full_name' => 'Full name',
															'main_image' => 'Main image',
															'image' => 'Image',
															'iframe' => 'IFrame',
															'title' => 'Title',
															'vimeo' => 'Vimeo',
															'youtube' => 'Youtube',
														),
														'default_value' => 'main_image',
														'allow_null' => 0,
														'multiple' => 0,
													),
													array (
														'key' => 'field_df0sdf661wse3',
														'label' => __('Unit span'),
														'name' => 'unit-span',
														'type' => 'select',
														'column_width' => '',
														'choices' => array (
															'one-of-one' => 'One of one',
															'one-of-two' => 'One of two',
															'one-of-three' => 'One of three',
															'one-of-four' => 'One of four',
															'one-of-five' => 'One of five',
															'two-of-three' => 'Two of three',
															'two-of-five' => 'Two of five',
															'three-of-four' => 'Three of four',
															'three-of-five' => 'Three of five',
															'four-of-five' => 'Four of five',
														),
														'default_value' => 'one-of-one',
														'allow_null' => 0,
														'multiple' => 0,
													),
													array (
														'key' => 'field_dfdad55991177eaasd44eed03',
														'label' => __('Operator'),
														'name' => 'operator',
														'type' => 'select',
														'column_width' => '',
														'choices' => array (
															'and' => 'And',
															'or' => 'Or',
														),
														'default_value' => 'and',
														'allow_null' => 0,
														'multiple' => 0,
													),
												),
												'button_label' => 'Add another Element',
											),
										),
									),
									array (
										'label' => __('Taxonomy accordion last name'),
										'name' => 'accordion_last_name',
										'display' => 'row',
										'min' => '',
										'max' => '',
										'sub_fields' => array (
											array (
												'key' => 'field_dssdd4frooer556a',
												'label' => __('Taxonomy accordion last name'),
												'name' => 'accordion_last_name',
												'type' => 'true_false',
												'column_width' => '',
												'message' => '',
												'default_value' => 1,
											),
										),
									),
									array (
										'label' => __('Taxonomy accordion publish date'),
										'name' => 'accordion_publish_date',
										'display' => 'row',
										'min' => '',
										'max' => '',
										'sub_fields' => array (
											array (
												'key' => 'field_sdfs55e7sdrte6ww',
												'label' => __('Taxonomy accordion publish date'),
												'name' => 'accordion_publish_date',
												'type' => 'true_false',
												'column_width' => '',
												'message' => '',
												'default_value' => 1,
											),
										),
									),
									array (
										'label' => __('Taxonomy accordion start date'),
										'name' => 'accordion_start_date',
										'display' => 'row',
										'min' => '',
										'max' => '',
										'sub_fields' => array (
											array (
												'key' => 'field_swer996as46a',
												'label' => __('Taxonomy accordion start date'),
												'name' => 'accordion_start_date',
												'type' => 'true_false',
												'column_width' => '',
												'message' => '',
												'default_value' => 1,
											),
										),
									),
									array (
										'label' => __('Taxonomy start date'),
										'name' => 'taxonomy_start_date',
										'display' => 'row',
										'min' => '',
										'max' => '',
										'sub_fields' => array (
											array (
												'key' => 'field_dsd66sas46a',
												'label' => __('Taxonomy start date'),
												'name' => 'taxonomy_start_date',
												'type' => 'true_false',
												'column_width' => '',
												'message' => '',
												'default_value' => 1,
											),
										),
									),
									array (
										'label' => __('Taxonomy last name'),
										'name' => 'taxonomy_last_name',
										'display' => 'row',
										'min' => '',
										'max' => '',
										'sub_fields' => array (
											array (
												'key' => 'field_nb6vvcas46a',
												'label' => __('Taxonomy last name'),
												'name' => 'taxonomy_last_name',
												'type' => 'true_false',
												'column_width' => '',
												'message' => '',
												'default_value' => 1,
											),
										),
									),
									array (
										'label' => __('Archive category'),
										'name' => 'archive_taxonomy',
										'display' => 'row',
										'min' => '',
										'max' => '',
										'sub_fields' => array (
											array (
												'key' => 'field_dsdasddf5pooieas46a',
												'label' => __('Archive category'),
												'name' => 'archive_taxonomy',
												'type' => 'true_false',
												'column_width' => '',
												'message' => '',
												'default_value' => 1,
											),
										),
									),
									array (
										'label' => __('Blockquote'),
										'name' => 'blockquote',
										'display' => 'row',
										'min' => '',
										'max' => '',
										'sub_fields' => array (
											array (
												'key' => 'field_o3mcvb7n9cv8743yw71p',
												'label' => __('Quote'),
												'name' => 'quote',
												'type' => 'text',
												'column_width' => '',
												'default_value' => '',
												'placeholder' => '',
												'prepend' => '',
												'append' => '',
												'formatting' => 'html',
												'maxlength' => '',
											),
											array (
												'key' => 'field_ikc8bn976ory1ljxk',
												'label' => __('Credit line 1'),
												'name' => 'credit_line_1',
												'type' => 'text',
												'column_width' => '',
												'default_value' => '',
												'placeholder' => '',
												'prepend' => '',
												'append' => '',
												'formatting' => 'html',
												'maxlength' => '',
											),
											array (
												'key' => 'field_scvb5n569iythdgk',
												'label' => __('Credit line 2'),
												'name' => 'credit_line_2',
												'type' => 'text',
												'column_width' => '',
												'default_value' => '',
												'placeholder' => '',
												'prepend' => '',
												'append' => '',
												'formatting' => 'html',
												'maxlength' => '',
											),
											array (
												'key' => 'field_t0dsr6etcvb7988dt',
												'label' => __('Credit line 2 type'),
												'name' => 'credit_line_2_type',
												'type' => 'select',
												'column_width' => '',
												'choices' => array (
													'text' => 'Text',
													'class' => 'Class',
													'url' => 'URL',
												),
												'default_value' => '',
												'allow_null' => 0,
												'multiple' => 0,
											),
											array (
												'key' => 'field_7t5738fcvbn87a8u',
												'label' => __('New window'),
												'name' => 'new_window',
												'type' => 'true_false',
												'column_width' => '',
												'message' => '',
												'default_value' => 0,
											),
											array (
												'key' => 'field_7778s5888ds8d88sd',
												'label' => __('Class'),
												'name' => 'class',
												'type' => 'text',
												'column_width' => '',
												'default_value' => '',
											),
										),
									),
									array (
										'label' => __('Blockquote rotator'),
										'name' => 'blockquote_rotator',
										'display' => 'row',
										'min' => '',
										'max' => '',
										'sub_fields' => array (
											array (
												'key' => 'field_3mzetyui797tqo40',
												'label' => __('Quotes'),
												'name' => 'quotes',
												'type' => 'repeater',
												'column_width' => '',
												'sub_fields' => array (
													array (
														'key' => 'field_tyui897987s837zcv',
														'label' => __('Quote'),
														'name' => 'quote',
														'type' => 'text',
														'column_width' => '',
														'default_value' => '',
														'placeholder' => '',
														'prepend' => '',
														'append' => '',
														'formatting' => 'html',
														'maxlength' => '',
													),
													array (
														'key' => 'field_wvl126rty6mtpui1',
														'label' => __('Credit line 1'),
														'name' => 'credit_line_1',
														'type' => 'text',
														'column_width' => '',
														'default_value' => '',
														'placeholder' => '',
														'prepend' => '',
														'append' => '',
														'formatting' => 'html',
														'maxlength' => '',
													),
													array (
														'key' => 'field_wq6uq7tu2t6549of',
														'label' => __('Credit line 2'),
														'name' => 'credit_line_2',
														'type' => 'text',
														'column_width' => '',
														'default_value' => '',
														'placeholder' => '',
														'prepend' => '',
														'append' => '',
														'formatting' => 'html',
														'maxlength' => '',
													),
													array (
														'key' => 'field_ryartyu99qvto1r',
														'label' => __('Credit line 2 type'),
														'name' => 'credit_line_2_type',
														'type' => 'select',
														'column_width' => '',
														'choices' => array (
															'text' => 'Text',
															'class' => 'Class',
															'url' => 'URL',
														),
														'default_value' => '',
														'allow_null' => 0,
														'multiple' => 0,
													),
													array (
														'key' => 'field_26m66tirty549',
														'label' => __('New window'),
														'name' => 'new_window',
														'type' => 'true_false',
														'column_width' => '',
														'message' => '',
														'default_value' => 0,
													),
													array (
														'key' => 'field_7778s5888ds8d88sd',
														'label' => __('Class'),
														'name' => 'class',
														'type' => 'text',
														'column_width' => '',
														'default_value' => '',
													),
												),
												'row_min' => '',
												'row_limit' => '',
												'layout' => 'row',
												'button_label' => 'Add a Quote',
											),
										),
									),
									array (
										'label' => __('Button link'),
										'name' => 'button_link',
										'display' => 'row',
										'min' => '',
										'max' => '',
										'sub_fields' => array (
											array (
												'key' => 'field_gsfz23t1yu3332j8',
												'label' => __('Text'),
												'name' => 'text',
												'type' => 'text',
												'column_width' => '',
												'default_value' => '',
												'placeholder' => '',
												'prepend' => '',
												'append' => '',
												'formatting' => 'html',
												'maxlength' => '',
											),
											array (
												'key' => 'field_oi9q39639tryrf4bk',
												'label' => __('Link'),
												'name' => 'link',
												'type' => 'text',
												'column_width' => '',
												'default_value' => '',
												'placeholder' => '',
												'prepend' => '',
												'append' => '',
												'formatting' => 'html',
												'maxlength' => '',
											),
											array (
												'key' => 'field_rxe3i4w6t9y8917teks',
												'label' => __('New window'),
												'name' => 'new_window',
												'type' => 'true_false',
												'column_width' => '',
												'message' => '',
												'default_value' => 0,
											),
											array (
												'key' => 'field_7778s5888ds8d88sd',
												'label' => __('Class'),
												'name' => 'class',
												'type' => 'text',
												'column_width' => '',
												'default_value' => '',
											),
										),
									),
									array (
										'label' => __('Editor'),
										'name' => 'editor',
										'display' => 'row',
										'min' => '',
										'max' => '',
										'sub_fields' => array (
											array (
												'key' => 'field_vcayttut2t8tyu25lad8uo',
												'label' => __('Editors'),
												'name' => 'editor',
												'type' => 'repeater',
												'column_width' => '',
												'sub_fields' => array (
													array (
														'key' => 'field_tyu36992h38f6e4k',
														'label' => __('Editor'),
														'name' => 'editor',
														'type' => 'wysiwyg',
														'column_width' => '',
														'default_value' => '',
														'toolbar' => 'full',
														'media_upload' => 'yes',
													),
												array (
													'key' => 'field_7778s5888ds8d88sd',
													'label' => __('Class'),
													'name' => 'class',
													'type' => 'text',
													'column_width' => '',
													'default_value' => '',
												),
												),
												'row_min' => '',
												'row_limit' => '',
												'layout' => 'row',
												'button_label' => 'Add an Editor',
											),
											array (
												'key' => 'field_7778s5888ds8d88sd',
												'label' => __('Class'),
												'name' => 'class',
												'type' => 'text',
												'column_width' => '',
												'default_value' => '',
											),
										),
									),
									array (
										'label' => __('Heading'),
										'name' => 'heading',
										'display' => 'row',
										'min' => '',
										'max' => '',
										'sub_fields' => array (
											array (
												'key' => 'field_50cbbntuy5929856',
												'label' => __('Heading'),
												'name' => 'heading',
												'type' => 'text',
												'column_width' => '',
												'default_value' => '',
												'placeholder' => '',
												'prepend' => '',
												'append' => '',
												'formatting' => 'html',
												'maxlength' => '',
											),
											array (
												'key' => 'field_zhty362t9ad',
												'label' => __('Heading type'),
												'name' => 'heading_type',
												'type' => 'select',
												'column_width' => '',
												'choices' => array (
													'heading_1' => 'Heading 1',
													'heading_2' => 'Heading 2',
													'heading_3' => 'Heading 3',
													'heading_4' => 'Heading 4',
												),
												'default_value' => 'heading_2',
												'allow_null' => 0,
												'multiple' => 0,
											),
											array (
												'key' => 'field_48ty26tu280cl',
												'label' => __('Link'),
												'name' => 'link',
												'type' => 'text',
												'column_width' => '',
												'default_value' => '',
												'placeholder' => '',
												'prepend' => '',
												'append' => '',
												'formatting' => 'html',
												'maxlength' => '',
											),
											array (
												'key' => 'field_qty63u269tyuu',
												'label' => __('New window'),
												'name' => 'new_window',
												'type' => 'true_false',
												'column_width' => '',
												'message' => '',
												'default_value' => 0,
											),
											array (
												'key' => 'field_7778s5888ds8d88sd',
												'label' => __('Class'),
												'name' => 'class',
												'type' => 'text',
												'column_width' => '',
												'default_value' => '',
											),
										),
									),
									array (
										'label' => __('Image'),
										'name' => 'image',
										'display' => 'row',
										'min' => '',
										'max' => '',
										'sub_fields' => array (
											array (
												'key' => 'field_r9vtuy9hwqe2r4iia',
												'label' => __('Image'),
												'name' => 'image',
												'type' => 'image',
												'column_width' => '',
												'default_value' => '',
												'placeholder' => '',
												'prepend' => '',
												'append' => '',
												'formatting' => 'html',
												'maxlength' => '',
											),
											array (
												'key' => 'field_elxqwer233tlv9s',
												'label' => __('Image link'),
												'name' => 'image_link',
												'type' => 'text',
												'column_width' => '',
												'default_value' => '',
												'placeholder' => '',
												'prepend' => '',
												'append' => '',
												'formatting' => 'html',
												'maxlength' => '',
											),
											array (
												'key' => 'field_bzp4supreww25e9',
												'label' => __('New window'),
												'name' => 'new_window',
												'type' => 'true_false',
												'column_width' => '',
												'message' => '',
												'default_value' => 0,
											),
											array (
												'key' => 'field_7778s5888ds8d88sd',
												'label' => __('Class'),
												'name' => 'class',
												'type' => 'text',
												'column_width' => '',
												'default_value' => '',
											),
										),
									),
									array (
										'label' => __('Image carousel'),
										'name' => 'image_carousel',
										'display' => 'row',
										'min' => '',
										'max' => '',
										'sub_fields' => array (
											array (
												'key' => 'field_b3i7werw6569a3y5',
												'label' => __('Images'),
												'name' => 'images',
												'type' => 'gallery',
												'column_width' => '',
												'preview_size' => 'thumbnail',
												'library' => 'all',
											),
											array (
												'key' => 'field_7778s5888ds8d88sd',
												'label' => __('Class'),
												'name' => 'class',
												'type' => 'text',
												'column_width' => '',
												'default_value' => '',
											),
										),
									),
									array (
										'label' => __('Image gallery'),
										'name' => 'image_gallery',
										'display' => 'row',
										'min' => '',
										'max' => '',
										'sub_fields' => array (
											array (
												'key' => 'field_54v8n36ds99ec8j',
												'label' => __('Images'),
												'name' => 'images',
												'type' => 'gallery',
												'column_width' => '',
												'preview_size' => 'thumbnail',
												'library' => 'all',
											),
											array (
												'key' => 'field_7778s5888ds8d88sd',
												'label' => __('Class'),
												'name' => 'class',
												'type' => 'text',
												'column_width' => '',
												'default_value' => '',
											),
										),
									),
									array (
										'label' => __('Image rotator'),
										'name' => 'image_rotator',
										'display' => 'row',
										'min' => '',
										'max' => '',
										'sub_fields' => array (
											array (
												'key' => 'field_sd69695mbdq3ad',
												'label' => __('Images'),
												'name' => 'images',
												'type' => 'gallery',
												'column_width' => '',
												'preview_size' => 'thumbnail',
												'library' => 'all',
											),
											array (
												'key' => 'field_7778s5888ds8d88sd',
												'label' => __('Class'),
												'name' => 'class',
												'type' => 'text',
												'column_width' => '',
												'default_value' => '',
											),
										),
									),
									array (
										'label' => __('Image with hover'),
										'name' => 'image_with_hover',
										'display' => 'row',
										'min' => '',
										'max' => '',
										'sub_fields' => array (
											array (
												'key' => 'field_sfsd636wxfx95',
												'label' => __('Image'),
												'name' => 'image',
												'type' => 'image',
												'column_width' => '',
												'save_format' => 'object',
												'preview_size' => 'thumbnail',
												'library' => 'all',
											),
											array (
												'key' => 'field_iiyas0kxc1z6Xc1cdhw',
												'label' => __('Hover image'),
												'name' => 'hover_image',
												'type' => 'image',
												'column_width' => '',
												'save_format' => 'object',
												'preview_size' => 'thumbnail',
												'library' => 'all',
											),
											array (
												'key' => 'field_zb3jzxcz12151t',
												'label' => __('Link'),
												'name' => 'link',
												'type' => 'text',
												'column_width' => '',
												'default_value' => '',
												'placeholder' => '',
												'prepend' => '',
												'append' => '',
												'formatting' => 'html',
												'maxlength' => '',
											),
											array (
												'key' => 'field_jvsyascxzc34zw',
												'label' => __('New Window'),
												'name' => 'new_window',
												'type' => 'true_false',
												'column_width' => '',
												'message' => '',
												'default_value' => 0,
											),
											array (
												'key' => 'field_7778s5888ds8d88sd',
												'label' => __('Class'),
												'name' => 'class',
												'type' => 'text',
												'column_width' => '',
												'default_value' => '',
											),
										),
									),
									array (
										'label' => __('Main image'),
										'name' => 'main_image',
										'display' => 'row',
										'min' => '',
										'max' => '',
										'sub_fields' => array (
											array (
												'key' => 'field_b6lzxcz2xc26m',
												'label' => __('Image'),
												'name' => 'image',
												'type' => 'image',
												'column_width' => '',
												'save_format' => 'object',
												'preview_size' => 'thumbnail',
												'library' => 'all',
											),
										),
									),
									array (
										'label' => __('Map'),
										'name' => 'map',
										'display' => 'row',
										'min' => '',
										'max' => '',
										'sub_fields' => array (
											array (
												'key' => 'field_cbms80dozxcz26293h',
												'label' => __('Map'),
												'name' => 'map',
												'type' => 'google_map',
												'column_width' => '',
												'center_lat' => '',
												'center_lng' => '',
												'height' => '',
											),
											array (
												'key' => 'field_v3ws12xcvcx626iwh',
												'label' => __('Map height'),
												'name' => 'map_height',
												'type' => 'number',
												'instructions' => __('Please enter the map height'),
												'column_width' => 15,
												'default_value' => 300,
												'placeholder' => '',
												'prepend' => '',
												'append' => 'px',
												'min' => 50,
												'max' => '',
												'step' => '',
											),
											array (
												'key' => 'field_42pxvc6i77n8',
												'label' => __('Style ID'),
												'name' => 'style_id',
												'type' => 'text',
												'instructions' => __('This is the ID of the map style you desire an ID can be retrieved from http://maps.cloudmade.com/editor'),
												'column_width' => '',
												'default_value' => 1714,
												'placeholder' => '',
												'prepend' => '',
												'append' => '',
												'formatting' => 'html',
												'maxlength' => '',
											),
											array (
												'key' => 'field_si3hjxcv5x959z3fd',
												'label' => __('Zoom level'),
												'name' => 'zoom_level',
												'type' => 'number',
												'column_width' => '',
												'default_value' => 3,
												'placeholder' => '',
												'prepend' => '',
												'append' => '',
												'min' => 0,
												'max' => 18,
												'step' => '',
											),
											array (
												'key' => 'field_s24pcxv78x79qjhk',
												'label' => __('Markers'),
												'name' => 'markers',
												'type' => 'repeater',
												'column_width' => '',
												'sub_fields' => array (
													array (
														'key' => 'field_txcv55i78',
														'label' => __('Location'),
														'name' => 'location',
														'type' => 'google_map',
														'column_width' => '',
														'center_lat' => '',
														'center_lng' => '',
														'height' => '',
													),
													array (
														'key' => 'field_nxsvxcvx51587nn',
														'label' => __('Image'),
														'name' => 'image',
														'type' => 'image',
														'instructions' => __('Add caption and text to image view on maker'),
														'column_width' => '',
														'save_format' => 'object',
														'preview_size' => 'thumbnail',
														'library' => 'all',
													),
											array (
												'key' => 'field_7778s5888ds8d88sd',
												'label' => __('Class'),
												'name' => 'class',
												'type' => 'text',
												'column_width' => '',
												'default_value' => '',
											),
												),
												'row_min' => '',
												'row_limit' => '',
												'layout' => 'row',
												'button_label' => 'Add a Map Marker',
											),
										),
									),
									array (
										'label' => __('PDF link'),
										'name' => 'pdf_link',
										'display' => 'row',
										'min' => '',
										'max' => '',
										'sub_fields' => array (
											array (
												'key' => 'field_8udfgd885lbz',
												'label' => __('Text'),
												'name' => 'text',
												'type' => 'text',
												'column_width' => '',
												'default_value' => '',
												'placeholder' => '',
												'prepend' => '',
												'append' => '',
												'formatting' => 'html',
												'maxlength' => '',
											),
											array (
												'key' => 'field_v0a54vja00sd6ip6',
												'label' => __('Text type'),
												'name' => 'text_type',
												'type' => 'select',
												'column_width' => '',
												'choices' => array (
													'heading_1' => 'Heading 1',
													'heading_2' => 'Heading 2',
													'heading_3' => 'Heading 3',
													'heading_4' => 'Heading 4',
													'paragraph_text' => 'Paragraph text',
												),
												'default_value' => 'paragraph_text',
												'allow_null' => 0,
												'multiple' => 0,
											),
											array (
												'key' => 'field_byvbnv16nnyg4o',
												'label' => __('PDF'),
												'name' => 'pdf',
												'type' => 'file',
												'column_width' => '',
												'save_format' => 'object',
												'library' => 'all',
											),
											array (
												'key' => 'field_r4vbn1v3t3ko',
												'label' => __('New window'),
												'name' => 'new_window',
												'type' => 'true_false',
												'column_width' => '',
												'message' => '',
												'default_value' => 0,
											),
											array (
												'key' => 'field_7778s5888ds8d88sd',
												'label' => __('Class'),
												'name' => 'class',
												'type' => 'text',
												'column_width' => '',
												'default_value' => '',
											),
										),
									),
									array (
										'label' => __('Sub menu'),
										'name' => 'sub_menu',
										'display' => 'row',
										'min' => '',
										'max' => '',
										'sub_fields' => array (
											array (
												'key' => 'field_2xvbn12v2kush8k1kq',
												'label' => __('Primary header menu'),
												'name' => 'primary_header_menu',
												'type' => 'true_false',
												'column_width' => '',
												'message' => '',
												'default_value' => 1,
											),
											array (
												'key' => 'field_nbvn212danlq',
												'label' => __('Custom theme menu location'),
												'name' => 'custom_theme_menu_location',
												'type' => 'text',
												'column_width' => '',
											),
										),
									),
									array (
										'label' => __('Text link'),
										'name' => 'text_link',
										'display' => 'row',
										'min' => '',
										'max' => '',
										'sub_fields' => array (
											array (
												'key' => 'field_bsx6vbn45a5zmoe',
												'label' => __('Text links'),
												'name' => 'text_link',
												'type' => 'repeater',
												'column_width' => '',
												'sub_fields' => array (
													array (
														'key' => 'field_cfm0w5vbnvb4545r',
														'label' => __('Text'),
														'name' => 'text',
														'type' => 'text',
														'column_width' => '',
														'default_value' => '',
														'placeholder' => '',
														'prepend' => '',
														'append' => '',
														'formatting' => 'html',
														'maxlength' => '',
													),
													array (
														'key' => 'field_m2zhtzbvnnvb17ixs',
														'label' => __('Link'),
														'name' => 'link',
														'type' => 'text',
														'column_width' => '',
														'default_value' => '',
														'placeholder' => '',
														'prepend' => '',
														'append' => '',
														'formatting' => 'html',
														'maxlength' => '',
													),
													array (
														'key' => 'field_a0bmvbn54zh',
														'label' => __('New window'),
														'name' => 'new_window',
														'type' => 'true_false',
														'column_width' => '',
														'message' => '',
														'default_value' => 0,
													),
												),
												'row_min' => '',
												'row_limit' => '',
												'layout' => 'row',
												'button_label' => 'Add a Text Link',
											),
											array (
												'key' => 'field_7778s5888ds8d88sd',
												'label' => __('Class'),
												'name' => 'class',
												'type' => 'text',
												'column_width' => '',
												'default_value' => '',
											),
										),
									),
									array (
										'label' => __('Text to image link'),
										'name' => 'text_to_image_link',
										'display' => 'row',
										'min' => '',
										'max' => '',
										'sub_fields' => array (
											array (
												'key' => 'field_66vbn566pyw',
												'label' => __('Text'),
												'name' => 'text',
												'type' => 'text',
												'column_width' => '',
												'default_value' => '',
												'placeholder' => '',
												'prepend' => '',
												'append' => '',
												'formatting' => 'html',
												'maxlength' => '',
											),
											array (
												'key' => 'field_l85kyqissvb7n9v87d2f',
												'label' => __('Text type'),
												'name' => 'text_type',
												'type' => 'select',
												'column_width' => '',
												'choices' => array (
													'heading_1' => 'Heading 1',
													'heading_2' => 'Heading 2',
													'heading_3' => 'Heading 3',
													'heading_4' => 'Heading 4',
													'paragraph_text' => 'Paragraph text',
												),
												'default_value' => 'paragraph_text',
												'allow_null' => 0,
												'multiple' => 0,
											),
											array (
												'key' => 'field_g2z0vbn7897w179',
												'label' => __('Image'),
												'name' => 'image',
												'type' => 'image',
												'column_width' => '',
												'save_format' => 'object',
												'preview_size' => 'thumbnail',
												'library' => 'all',
											),
											array (
												'key' => 'field_7778s5888ds8d88sd',
												'label' => __('Class'),
												'name' => 'class',
												'type' => 'text',
												'column_width' => '',
												'default_value' => '',
											),
										),
									),
									array (
										'label' => __('Text rotator'),
										'name' => 'text_rotator',
										'display' => 'row',
										'min' => '',
										'max' => '',
										'sub_fields' => array (
											array (
												'key' => 'field_m4gmmvbn898imcx3',
												'label' => __('Heading'),
												'name' => 'heading',
												'type' => 'text',
												'column_width' => '',
												'default_value' => '',
												'placeholder' => '',
												'prepend' => '',
												'append' => '',
												'formatting' => 'html',
												'maxlength' => '',
											),
											array (
												'key' => 'field_vvbn79v87apzv90ad0q',
												'label' => __('Heading type'),
												'name' => 'heading_type',
												'type' => 'select',
												'column_width' => '',
												'choices' => array (
													'heading_1' => 'Heading 1',
													'heading_2' => 'Heading 2',
													'heading_3' => 'Heading 3',
													'heading_4' => 'Heading 4',
													'paragraph_text' => 'Paragraph text',
												),
												'default_value' => 'paragraph_text',
												'allow_null' => 0,
												'multiple' => 0,
											),
											array (
												'key' => 'field_hqkvb87n987a1rxr',
												'label' => __('Texts'),
												'name' => 'text',
												'type' => 'repeater',
												'column_width' => '',
												'sub_fields' => array (
													array (
														'key' => 'field_r65v4bn87ttejwe9xk',
														'label' => __('Text'),
														'name' => 'text',
														'type' => 'text',
														'column_width' => '',
														'default_value' => '',
														'placeholder' => '',
														'prepend' => '',
														'append' => '',
														'formatting' => 'html',
														'maxlength' => '',
													),
												),
												'row_min' => '',
												'row_limit' => '',
												'layout' => 'table',
												'button_label' => 'Add Text',
											),
											array (
												'key' => 'field_7778s5888ds8d88sd',
												'label' => __('Class'),
												'name' => 'class',
												'type' => 'text',
												'column_width' => '',
												'default_value' => '',
											),
										),
									),
									array (
										'label' => __('Title'),
										'name' => 'title',
										'display' => 'row',
										'min' => '',
										'max' => '',
										'sub_fields' => array (
											array (
												'key' => 'field_ad4f16dfsf5346276',
												'label' => __('Title'),
												'name' => 'title',
												'type' => 'true_false',
												'column_width' => '',
												'message' => '',
												'default_value' => 1,
											),
											array (
												'key' => 'field_tyutyfiy6deee2565tuty4',
												'label' => __('Title type'),
												'name' => 'title_type',
												'type' => 'select',
												'column_width' => '',
												'choices' => array (
													'heading_1' => 'Heading 1',
													'heading_2' => 'Heading 2',
													'heading_3' => 'Heading 3',
													'heading_4' => 'Heading 4',
												),
												'default_value' => 'heading_1',
												'allow_null' => 0,
												'multiple' => 0,
											),
											array (
												'key' => 'field_rtyrht87960fyuta',
												'label' => __('Link'),
												'name' => 'link',
												'type' => 'text',
												'column_width' => '',
												'default_value' => '',
												'placeholder' => '',
												'prepend' => '',
												'append' => '',
												'formatting' => 'html',
												'maxlength' => '',
											),
											array (
												'key' => 'field_rsdftytryrtyrty787ytut',
												'label' => __('New window'),
												'name' => 'new_window',
												'type' => 'true_false',
												'column_width' => '',
												'message' => '',
												'default_value' => 0,
											),
											array (
												'key' => 'field_rtysdf44fe011tutyd',
												'label' => __('Class'),
												'name' => 'class',
												'type' => 'text',
												'column_width' => '',
												'default_value' => '',
											),
										),
									),
									array (
										'label' => __('Vimeo'),
										'name' => 'vimeo',
										'display' => 'row',
										'min' => '',
										'max' => '',
										'sub_fields' => array (
											array (
												'key' => 'field_tcvbn8v7b9876gdwhvj',
												'label' => __('Heading'),
												'name' => 'heading',
												'type' => 'text',
												'column_width' => '',
												'default_value' => '',
												'placeholder' => '',
												'prepend' => '',
												'append' => '',
												'formatting' => 'html',
												'maxlength' => '',
											),
											array (
												'key' => 'field_givb8n7v87n9fyho2a',
												'label' => __('Video link'),
												'name' => 'video_link',
												'type' => 'text',
												'column_width' => '',
												'default_value' => '',
												'placeholder' => '',
												'prepend' => '',
												'append' => '',
												'formatting' => 'html',
												'maxlength' => '',
											),
											array (
												'key' => 'field_3vbvbn5646frn1n',
												'label' => __('Video image'),
												'name' => 'video_image',
												'type' => 'image',
												'column_width' => '',
												'save_format' => 'object',
												'preview_size' => 'thumbnail',
												'library' => 'all',
											),
											array (
												'key' => 'field_hvb8n798zr8rwan1saa',
												'label' => __('Heading type'),
												'name' => 'heading_type',
												'type' => 'select',
												'column_width' => '',
												'choices' => array (
												),
												'default_value' => '',
												'allow_null' => 0,
												'multiple' => 0,
											),
											array (
												'key' => 'field_7778s5888ds8d88sd',
												'label' => __('Class'),
												'name' => 'class',
												'type' => 'text',
												'column_width' => '',
												'default_value' => '',
											),
										),
									),
									array (
										'label' => __('Youtube'),
										'name' => 'youtube',
										'display' => 'row',
										'min' => '',
										'max' => '',
										'sub_fields' => array (
											array (
												'key' => 'field_3v8b7n9828xj9ylukq',
												'label' => __('Heading'),
												'name' => 'heading',
												'type' => 'text',
												'column_width' => '',
												'default_value' => '',
												'placeholder' => '',
												'prepend' => '',
												'append' => '',
												'formatting' => 'html',
												'maxlength' => '',
											),
											array (
												'key' => 'field_gvbn879ktb7dyigw',
												'label' => __('Video link'),
												'name' => 'video_link',
												'type' => 'text',
												'column_width' => '',
												'default_value' => '',
												'placeholder' => '',
												'prepend' => '',
												'append' => '',
												'formatting' => 'html',
												'maxlength' => '',
											),
											array (
												'key' => 'field_8vvbn87v98bw25iotjj',
												'label' => __('Video image'),
												'name' => 'video_image',
												'type' => 'image',
												'column_width' => '',
												'save_format' => 'object',
												'preview_size' => 'thumbnail',
												'library' => 'all',
											),
											array (
												'key' => 'field_v8b7n9v877c9nh9om95d',
												'label' => __('Heading type'),
												'name' => 'heading_type',
												'type' => 'select',
												'column_width' => '',
												'choices' => array (
													'heading_1' => 'Heading 1',
													'heading_2' => 'Heading 2',
													'heading_3' => 'Heading 3',
													'heading_4' => 'Heading 4',
													'paragraph_text' => 'Paragraph text',
												),
												'default_value' => 'paragraph_text',
												'allow_null' => 0,
												'multiple' => 0,
											),
											array (
												'key' => 'field_7778s5888ds8d88sd',
												'label' => __('Class'),
												'name' => 'class',
												'type' => 'text',
												'column_width' => '',
												'default_value' => '',
											),
										),
									),
								),
								'button_label' => 'Add an Item',
								'min' => '',
								'max' => '',
							),
						),
						'row_min' => '',
						'row_limit' => '',
						'layout' => 'row',
						'button_label' => 'Add a Nested Unit',
					),
				),
				'row_min' => '',
				'row_limit' => '',
				'layout' => 'row',
				'button_label' => 'Add a Unit',
				),
			),
			'location' => array (
				array (
					array (
						'param' => 'page_template',
						'operator' => '==',
						'value' => 'taxonomy.php',
						'order_no' => 0,
						'group_no' => 0,
					),
				),
			),
			'options' => array (
				'position' => 'normal',
				'layout' => 'no_box',
				'hide_on_screen' => array (
					0 => 'the_content',
				),
			),
			'menu_order' => 0,
		));
}
?>