<?php

if(function_exists("register_field_group"))
{
	register_field_group(array (
		'id' => 'acf_flexible-content',
		'title' => 'Flexible Content',
		'fields' => array (
			array (
				'key' => 'field_527a680f291f1',
				'label' => __('Containers'),
				'name' => 'containers',
				'type' => 'repeater',
				'sub_fields' => array (
					array (
						'key' => 'field_527a6820291f2',
						'label' => __('Layout'),
						'name' => 'layout',
						'type' => 'select',
						'column_width' => '',
						'choices' => array (
							'one-of-one' => 'One of one',
							'one-of-two' => 'One of two',
							'one-of-three' => 'One of three',
							'one-of-four' => 'One of four',
							'one-of-five' => 'One of five',
							'two-of-three' => 'Two of three',
							'two-of-five' => 'Two of five',
							'three-of-four' => 'Three of four',
							'three-of-five' => 'Three of five',
							'four-of-five' => 'Four of five',
						),
						'default_value' => 'one-of-one',
						'allow_null' => 0,
						'multiple' => 0,
					),
					array (
						'key' => 'field_527a6c8b291f5',
						'label' => __('Content'),
						'name' => 'content',
						'type' => 'flexible_content',
						'column_width' => '',
						'layouts' => array (
							array (
								'label' => __('Main image'),
								'name' => 'main_image',
								'display' => 'row',
								'min' => '',
								'max' => '',
								'sub_fields' => array (
									array (
										'key' => 'field_527b2632285be',
										'label' => __('Image'),
										'name' => 'image',
										'type' => 'image',
										'column_width' => '',
										'save_format' => 'object',
										'preview_size' => 'thumbnail',
										'library' => 'all',
									),
								),
							),
							array (
								'label' => __('Image rotator'),
								'name' => 'image_rotator',
								'display' => 'row',
								'min' => '',
								'max' => '',
								'sub_fields' => array (
									array (
										'key' => 'field_527aca0569bb5',
										'label' => __('Images'),
										'name' => 'images',
										'type' => 'gallery',
										'column_width' => '',
										'preview_size' => 'thumbnail',
										'library' => 'all',
									),
								),
							),
							array (
								'label' => __('Image carousel'),
								'name' => 'image_carousel',
								'display' => 'row',
								'min' => '',
								'max' => '',
								'sub_fields' => array (
									array (
										'key' => 'field_527ad4eadc276',
										'label' => __('Images'),
										'name' => 'images',
										'type' => 'gallery',
										'column_width' => '',
										'preview_size' => 'thumbnail',
										'library' => 'all',
									),
								),
							),
							array (
								'label' => __('Image'),
								'name' => 'image',
								'display' => 'row',
								'min' => '',
								'max' => '',
								'sub_fields' => array (
									array (
										'key' => 'field_527a7b6748836',
										'label' => __('Image'),
										'name' => 'image',
										'type' => 'image',
										'column_width' => '',
										'default_value' => '',
										'placeholder' => '',
										'prepend' => '',
										'append' => '',
										'formatting' => 'html',
										'maxlength' => '',
									),
									array (
										'key' => 'field_527a7b7f48837',
										'label' => __('Image link'),
										'name' => 'image_link',
										'type' => 'text',
										'column_width' => '',
										'default_value' => '',
										'placeholder' => '',
										'prepend' => '',
										'append' => '',
										'formatting' => 'html',
										'maxlength' => '',
									),
									array (
										'key' => 'field_527a7b8748838',
										'label' => __('New window'),
										'name' => 'new_window',
										'type' => 'true_false',
										'column_width' => '',
										'message' => '',
										'default_value' => 0,
									),
								),
							),
							array (
								'label' => __('Image with hover'),
								'name' => 'image_with_hover',
								'display' => 'row',
								'min' => '',
								'max' => '',
								'sub_fields' => array (
									array (
										'key' => 'field_527a7bb96fb2e',
										'label' => __('Image'),
										'name' => 'image',
										'type' => 'image',
										'column_width' => '',
										'save_format' => 'object',
										'preview_size' => 'thumbnail',
										'library' => 'all',
									),
									array (
										'key' => 'field_527a7bc86fb2f',
										'label' => __('Hover image'),
										'name' => 'hover_image',
										'type' => 'image',
										'column_width' => '',
										'save_format' => 'object',
										'preview_size' => 'thumbnail',
										'library' => 'all',
									),
									array (
										'key' => 'field_527a7bda6fb30',
										'label' => __('Link'),
										'name' => 'link',
										'type' => 'text',
										'column_width' => '',
										'default_value' => '',
										'placeholder' => '',
										'prepend' => '',
										'append' => '',
										'formatting' => 'html',
										'maxlength' => '',
									),
									array (
										'key' => 'field_527a7be26fb31',
										'label' => __('New Window'),
										'name' => 'new_window',
										'type' => 'true_false',
										'column_width' => '',
										'message' => '',
										'default_value' => 0,
									),
								),
							),
							array (
								'label' => __('Image gallery'),
								'name' => 'image_gallery',
								'display' => 'row',
								'min' => '',
								'max' => '',
								'sub_fields' => array (
									array (
										'key' => 'field_527d482fb389c',
										'label' => __('Images'),
										'name' => 'images',
										'type' => 'gallery',
										'column_width' => '',
										'preview_size' => 'thumbnail',
										'library' => 'all',
									),
								),
							),
							array (
								'label' => __('Sub menu'),
								'name' => 'sub_nav',
								'display' => 'row',
								'min' => '',
								'max' => '',
								'sub_fields' => array (
									array (
										'key' => 'field_527anmdisn276',
										'label' => __('Theme menu location'),
										'name' => 'theme_location',
										'type' => 'text',
										'column_width' => '',
									),
								),
							),
							array (
								'label' => __('Heading 1'),
								'name' => 'heading_1',
								'display' => 'row',
								'min' => '',
								'max' => '',
								'sub_fields' => array (
									array (
										'key' => 'field_527a781d291f6',
										'label' => __('Heading'),
										'name' => 'heading',
										'type' => 'text',
										'column_width' => '',
										'default_value' => '',
										'placeholder' => '',
										'prepend' => '',
										'append' => '',
										'formatting' => 'html',
										'maxlength' => '',
									),
								),
							),
							array (
								'label' => __('Heading 2'),
								'name' => 'heading_2',
								'display' => 'row',
								'min' => '',
								'max' => '',
								'sub_fields' => array (
									array (
										'key' => 'field_527a784d291f8',
										'label' => __('Heading'),
										'name' => 'heading',
										'type' => 'text',
										'column_width' => '',
										'default_value' => '',
										'placeholder' => '',
										'prepend' => '',
										'append' => '',
										'formatting' => 'html',
										'maxlength' => '',
									),
								),
							),
							array (
								'label' => __('Heading 3'),
								'name' => 'heading_3',
								'display' => 'row',
								'min' => '',
								'max' => '',
								'sub_fields' => array (
									array (
										'key' => 'field_527a7861291fa',
										'label' => __('Heading'),
										'name' => 'heading',
										'type' => 'text',
										'column_width' => '',
										'default_value' => '',
										'placeholder' => '',
										'prepend' => '',
										'append' => '',
										'formatting' => 'html',
										'maxlength' => '',
									),
								),
							),
							array (
								'label' => __('Heading 4'),
								'name' => 'heading_4',
								'display' => 'row',
								'min' => '',
								'max' => '',
								'sub_fields' => array (
									array (
										'key' => 'field_527a7875291fc',
										'label' => __('Heading'),
										'name' => 'heading',
										'type' => 'text',
										'column_width' => '',
										'default_value' => '',
										'placeholder' => '',
										'prepend' => '',
										'append' => '',
										'formatting' => 'html',
										'maxlength' => '',
									),
								),
							),
							array (
								'label' => __('Heading 1 link'),
								'name' => 'heading_1_link',
								'display' => 'row',
								'min' => '',
								'max' => '',
								'sub_fields' => array (
									array (
										'key' => 'field_527a7941ed5fd',
										'label' => __('Heading'),
										'name' => 'heading',
										'type' => 'text',
										'column_width' => '',
										'default_value' => '',
										'placeholder' => '',
										'prepend' => '',
										'append' => '',
										'formatting' => 'html',
										'maxlength' => '',
									),
									array (
										'key' => 'field_527a794eed5fe',
										'label' => __('Link'),
										'name' => 'link',
										'type' => 'text',
										'column_width' => '',
										'default_value' => '',
										'placeholder' => '',
										'prepend' => '',
										'append' => '',
										'formatting' => 'html',
										'maxlength' => '',
									),
									array (
										'key' => 'field_527a795ced5ff',
										'label' => __('New window'),
										'name' => 'new_window',
										'type' => 'true_false',
										'column_width' => '',
										'message' => '',
										'default_value' => 0,
									),
								),
							),
							array (
								'label' => __('Heading 2 link'),
								'name' => 'heading_2_link',
								'display' => 'row',
								'min' => '',
								'max' => '',
								'sub_fields' => array (
									array (
										'key' => 'field_527a7974ed601',
										'label' => __('Heading'),
										'name' => 'heading',
										'type' => 'text',
										'column_width' => '',
										'default_value' => '',
										'placeholder' => '',
										'prepend' => '',
										'append' => '',
										'formatting' => 'html',
										'maxlength' => '',
									),
									array (
										'key' => 'field_527a7974ed602',
										'label' => __('Link'),
										'name' => 'link',
										'type' => 'text',
										'column_width' => '',
										'default_value' => '',
										'placeholder' => '',
										'prepend' => '',
										'append' => '',
										'formatting' => 'html',
										'maxlength' => '',
									),
									array (
										'key' => 'field_527a7974ed603',
										'label' => __('New window'),
										'name' => 'new_window',
										'type' => 'true_false',
										'column_width' => '',
										'message' => '',
										'default_value' => 0,
									),
								),
							),
							array (
								'label' => __('Heading 3 link'),
								'name' => 'heading_3_link',
								'display' => 'row',
								'min' => '',
								'max' => '',
								'sub_fields' => array (
									array (
										'key' => 'field_527a798ced605',
										'label' => __('Heading'),
										'name' => 'heading',
										'type' => 'text',
										'column_width' => '',
										'default_value' => '',
										'placeholder' => '',
										'prepend' => '',
										'append' => '',
										'formatting' => 'html',
										'maxlength' => '',
									),
									array (
										'key' => 'field_527a798ced606',
										'label' => __('Link'),
										'name' => 'link',
										'type' => 'text',
										'column_width' => '',
										'default_value' => '',
										'placeholder' => '',
										'prepend' => '',
										'append' => '',
										'formatting' => 'html',
										'maxlength' => '',
									),
									array (
										'key' => 'field_527a798ced607',
										'label' => __('New window'),
										'name' => 'new_window',
										'type' => 'true_false',
										'column_width' => '',
										'message' => '',
										'default_value' => 0,
									),
								),
							),
							array (
								'label' => __('Heading 4 link'),
								'name' => 'heading_4_link',
								'display' => 'row',
								'min' => '',
								'max' => '',
								'sub_fields' => array (
									array (
										'key' => 'field_527a798ded609',
										'label' => __('Heading'),
										'name' => 'heading',
										'type' => 'text',
										'column_width' => '',
										'default_value' => '',
										'placeholder' => '',
										'prepend' => '',
										'append' => '',
										'formatting' => 'html',
										'maxlength' => '',
									),
									array (
										'key' => 'field_527a798ded60a',
										'label' => __('Link'),
										'name' => 'link',
										'type' => 'text',
										'column_width' => '',
										'default_value' => '',
										'placeholder' => '',
										'prepend' => '',
										'append' => '',
										'formatting' => 'html',
										'maxlength' => '',
									),
									array (
										'key' => 'field_527a798ded60b',
										'label' => __('New window'),
										'name' => 'new_window',
										'type' => 'true_false',
										'column_width' => '',
										'message' => '',
										'default_value' => 0,
									),
								),
							),
							array (
								'label' => __('Editor'),
								'name' => 'editor',
								'display' => 'row',
								'min' => '',
								'max' => '',
								'sub_fields' => array (
									array (
										'key' => 'field_527a79dd748cc',
										'label' => __('Editor'),
										'name' => 'editor',
										'type' => 'repeater',
										'column_width' => '',
										'sub_fields' => array (
											array (
												'key' => 'field_527a99ffe011d',
												'label' => __('Editor'),
												'name' => 'editor',
												'type' => 'wysiwyg',
												'column_width' => '',
												'default_value' => '',
												'toolbar' => 'full',
												'media_upload' => 'yes',
											),
										),
										'row_min' => '',
										'row_limit' => '',
										'layout' => 'row',
										'button_label' => 'Add Editor',
									),
								),
							),
							array (
								'label' => __('Text link'),
								'name' => 'text_link',
								'display' => 'row',
								'min' => '',
								'max' => '',
								'sub_fields' => array (
									array (
										'key' => 'field_527a79f1748ce',
										'label' => __('Text link'),
										'name' => 'text_link',
										'type' => 'repeater',
										'column_width' => '',
										'sub_fields' => array (
											array (
												'key' => 'field_527a79fe748cf',
												'label' => __('Text'),
												'name' => 'text',
												'type' => 'text',
												'column_width' => '',
												'default_value' => '',
												'placeholder' => '',
												'prepend' => '',
												'append' => '',
												'formatting' => 'html',
												'maxlength' => '',
											),
											array (
												'key' => 'field_527a7a15748d0',
												'label' => __('Link'),
												'name' => 'link',
												'type' => 'text',
												'column_width' => '',
												'default_value' => '',
												'placeholder' => '',
												'prepend' => '',
												'append' => '',
												'formatting' => 'html',
												'maxlength' => '',
											),
											array (
												'key' => 'field_527a7a1b748d1',
												'label' => __('New window'),
												'name' => 'new_window',
												'type' => 'true_false',
												'column_width' => '',
												'message' => '',
												'default_value' => 0,
											),
										),
										'row_min' => '',
										'row_limit' => '',
										'layout' => 'row',
										'button_label' => 'Add Text Link',
									),
								),
							),
							array (
								'label' => __('Text to image link'),
								'name' => 'text_to_image_link',
								'display' => 'row',
								'min' => '',
								'max' => '',
								'sub_fields' => array (
									array (
										'key' => 'field_527a7a5c48824',
										'label' => __('Text'),
										'name' => 'text',
										'type' => 'text',
										'column_width' => '',
										'default_value' => '',
										'placeholder' => '',
										'prepend' => '',
										'append' => '',
										'formatting' => 'html',
										'maxlength' => '',
									),
									array (
										'key' => 'field_527d41afb3ba7',
										'label' => __('Text type'),
										'name' => 'text_type',
										'type' => 'select',
										'column_width' => '',
										'choices' => array (
											'heading_1' => 'Heading 1',
											'heading_2' => 'Heading 2',
											'heading_3' => 'Heading 3',
											'heading_4' => 'Heading 4',
											'paragraph_text' => 'Paragraph text',
										),
										'default_value' => 'paragraph_text',
										'allow_null' => 0,
										'multiple' => 0,
									),
									array (
										'key' => 'field_527a7a6c48825',
										'label' => __('Image'),
										'name' => 'image',
										'type' => 'image',
										'column_width' => '',
										'save_format' => 'object',
										'preview_size' => 'thumbnail',
										'library' => 'all',
									),
								),
							),
							array (
								'label' => __('Text rotator'),
								'name' => 'text_rotator',
								'display' => 'row',
								'min' => '',
								'max' => '',
								'sub_fields' => array (
									array (
										'key' => 'field_527d3dda02ed7',
										'label' => __('Heading'),
										'name' => 'heading',
										'type' => 'text',
										'column_width' => '',
										'default_value' => '',
										'placeholder' => '',
										'prepend' => '',
										'append' => '',
										'formatting' => 'html',
										'maxlength' => '',
									),
									array (
										'key' => 'field_527d3de602ed8',
										'label' => __('Heading type'),
										'name' => 'heading_type',
										'type' => 'select',
										'column_width' => '',
										'choices' => array (
											'heading_1' => 'Heading 1',
											'heading_2' => 'Heading 2',
											'heading_3' => 'Heading 3',
											'heading_4' => 'Heading 4',
											'paragraph_text' => 'Paragraph text',
										),
										'default_value' => 'paragraph_text',
										'allow_null' => 0,
										'multiple' => 0,
									),
									array (
										'key' => 'field_527a7a7c48826',
										'label' => __('Text'),
										'name' => 'text',
										'type' => 'repeater',
										'column_width' => '',
										'sub_fields' => array (
											array (
												'key' => 'field_527a7a9348827',
												'label' => __('Text'),
												'name' => 'text',
												'type' => 'text',
												'column_width' => '',
												'default_value' => '',
												'placeholder' => '',
												'prepend' => '',
												'append' => '',
												'formatting' => 'html',
												'maxlength' => '',
											),
										),
										'row_min' => '',
										'row_limit' => '',
										'layout' => 'table',
										'button_label' => 'Add Text',
									),
								),
							),
							array (
								'label' => __('Button link'),
								'name' => 'button_link',
								'display' => 'row',
								'min' => '',
								'max' => '',
								'sub_fields' => array (
									array (
										'key' => 'field_527a7ab948829',
										'label' => __('Text'),
										'name' => 'text',
										'type' => 'text',
										'column_width' => '',
										'default_value' => '',
										'placeholder' => '',
										'prepend' => '',
										'append' => '',
										'formatting' => 'html',
										'maxlength' => '',
									),
									array (
										'key' => 'field_527a7acd4882a',
										'label' => __('Link'),
										'name' => 'link',
										'type' => 'text',
										'column_width' => '',
										'default_value' => '',
										'placeholder' => '',
										'prepend' => '',
										'append' => '',
										'formatting' => 'html',
										'maxlength' => '',
									),
									array (
										'key' => 'field_527a7ad84882b',
										'label' => __('New window'),
										'name' => 'new_window',
										'type' => 'true_false',
										'column_width' => '',
										'message' => '',
										'default_value' => 0,
									),
								),
							),
							array (
								'label' => __('Blockquote'),
								'name' => 'blockquote',
								'display' => 'row',
								'min' => '',
								'max' => '',
								'sub_fields' => array (
									array (
										'key' => 'field_527a7aed4882d',
										'label' => __('Quote'),
										'name' => 'quote',
										'type' => 'text',
										'column_width' => '',
										'default_value' => '',
										'placeholder' => '',
										'prepend' => '',
										'append' => '',
										'formatting' => 'html',
										'maxlength' => '',
									),
									array (
										'key' => 'field_527a7afb4882e',
										'label' => __('Credit line 1'),
										'name' => 'credit_line_1',
										'type' => 'text',
										'column_width' => '',
										'default_value' => '',
										'placeholder' => '',
										'prepend' => '',
										'append' => '',
										'formatting' => 'html',
										'maxlength' => '',
									),
									array (
										'key' => 'field_527a7b064882f',
										'label' => __('Credit line 2'),
										'name' => 'credit_line_2',
										'type' => 'text',
										'column_width' => '',
										'default_value' => '',
										'placeholder' => '',
										'prepend' => '',
										'append' => '',
										'formatting' => 'html',
										'maxlength' => '',
									),
									array (
										'key' => 'field_527d31c986310',
										'label' => __('Credit line 2 type'),
										'name' => 'credit_line_2_type',
										'type' => 'select',
										'column_width' => '',
										'choices' => array (
											'text' => 'Text',
											'class' => 'Class',
											'url' => 'URL',
										),
										'default_value' => '',
										'allow_null' => 0,
										'multiple' => 0,
									),
									array (
										'key' => 'field_527d31f486311',
										'label' => __('New window'),
										'name' => 'new_window',
										'type' => 'true_false',
										'column_width' => '',
										'message' => '',
										'default_value' => 0,
									),
								),
							),
							array (
								'label' => __('Blockquote rotator'),
								'name' => 'blockquote_rotator',
								'display' => 'row',
								'min' => '',
								'max' => '',
								'sub_fields' => array (
									array (
										'key' => 'field_527a7b1e48831',
										'label' => __('Quotes'),
										'name' => 'quotes',
										'type' => 'repeater',
										'column_width' => '',
										'sub_fields' => array (
											array (
												'key' => 'field_527a7b2a48832',
												'label' => __('Quote'),
												'name' => 'quote',
												'type' => 'text',
												'column_width' => '',
												'default_value' => '',
												'placeholder' => '',
												'prepend' => '',
												'append' => '',
												'formatting' => 'html',
												'maxlength' => '',
											),
											array (
												'key' => 'field_527a7b3f48833',
												'label' => __('Credit line 1'),
												'name' => 'credit_line_1',
												'type' => 'text',
												'column_width' => '',
												'default_value' => '',
												'placeholder' => '',
												'prepend' => '',
												'append' => '',
												'formatting' => 'html',
												'maxlength' => '',
											),
											array (
												'key' => 'field_527a7b4d48834',
												'label' => __('Credit line 2'),
												'name' => 'credit_line_2',
												'type' => 'text',
												'column_width' => '',
												'default_value' => '',
												'placeholder' => '',
												'prepend' => '',
												'append' => '',
												'formatting' => 'html',
												'maxlength' => '',
											),
											array (
												'key' => 'field_527d29f6148da',
												'label' => __('Credit line 2 type'),
												'name' => 'credit_line_2_type',
												'type' => 'select',
												'column_width' => '',
												'choices' => array (
													'text' => 'Text',
													'class' => 'Class',
													'url' => 'URL',
												),
												'default_value' => '',
												'allow_null' => 0,
												'multiple' => 0,
											),
											array (
												'key' => 'field_527d2f192499e',
												'label' => __('New window'),
												'name' => 'new_window',
												'type' => 'true_false',
												'column_width' => '',
												'message' => '',
												'default_value' => 0,
											),
										),
										'row_min' => '',
										'row_limit' => '',
										'layout' => 'row',
										'button_label' => 'Add Quote',
									),
								),
							),
							array (
								'label' => __('PDF link'),
								'name' => 'pdf_link',
								'display' => 'row',
								'min' => '',
								'max' => '',
								'sub_fields' => array (
									array (
										'key' => 'field_527a7bfd6fb33',
										'label' => __('Text'),
										'name' => 'text',
										'type' => 'text',
										'column_width' => '',
										'default_value' => '',
										'placeholder' => '',
										'prepend' => '',
										'append' => '',
										'formatting' => 'html',
										'maxlength' => '',
									),
									array (
										'key' => 'field_527d20db9fdb0',
										'label' => __('Text type'),
										'name' => 'text_type',
										'type' => 'select',
										'column_width' => '',
										'choices' => array (
											'heading_1' => 'Heading 1',
											'heading_2' => 'Heading 2',
											'heading_3' => 'Heading 3',
											'heading_4' => 'Heading 4',
											'paragraph_text' => 'Paragraph text',
										),
										'default_value' => 'paragraph_text',
										'allow_null' => 0,
										'multiple' => 0,
									),
									array (
										'key' => 'field_527a7c0c6fb34',
										'label' => __('PDF'),
										'name' => 'pdf',
										'type' => 'file',
										'column_width' => '',
										'save_format' => 'object',
										'library' => 'all',
									),
									array (
										'key' => 'field_527a7c166fb35',
										'label' => __('New window'),
										'name' => 'new_window',
										'type' => 'true_false',
										'column_width' => '',
										'message' => '',
										'default_value' => 0,
									),
								),
							),
							array (
								'label' => __('Accordion editor'),
								'name' => 'accordion_editor',
								'display' => 'row',
								'min' => '',
								'max' => '',
								'sub_fields' => array (
									array (
										'key' => 'field_527a7c426fb39',
										'label' => __('Heading type'),
										'name' => 'heading_type',
										'type' => 'select',
										'column_width' => '',
										'choices' => array (
											'heading_1' => 'Heading 1',
											'heading_2' => 'Heading 2',
											'heading_3' => 'Heading 3',
											'heading_4' => 'Heading 4',
											'paragraph_text' => 'Paragraph text',
										),
										'default_value' => 'paragraph_text',
										'allow_null' => 0,
										'multiple' => 0,
									),
									array (
										'key' => 'field_527b0068a418f',
										'label' => __('Accordion'),
										'name' => 'accordion',
										'type' => 'repeater',
										'column_width' => '',
										'sub_fields' => array (
											array (
												'key' => 'field_527b008da4190',
												'label' => __('Heading'),
												'name' => 'heading',
												'type' => 'text',
												'column_width' => '',
												'default_value' => '',
												'placeholder' => '',
												'prepend' => '',
												'append' => '',
												'formatting' => 'html',
												'maxlength' => '',
											),
											array (
												'key' => 'field_527b00aaa4191',
												'label' => __('Editor'),
												'name' => 'editor',
												'type' => 'wysiwyg',
												'column_width' => '',
												'default_value' => '',
												'toolbar' => 'full',
												'media_upload' => 'yes',
											),
										),
										'row_min' => '',
										'row_limit' => '',
										'layout' => 'row',
										'button_label' => 'Add Item',
									),
								),
							),
							array (
								'label' => __('Accordion links'),
								'name' => 'accordion_links',
								'display' => 'row',
								'min' => '',
								'max' => '',
								'sub_fields' => array (
									array (
										'key' => 'field_527c5669815f4',
										'label' => __('Heading type'),
										'name' => 'heading_type',
										'type' => 'select',
										'column_width' => '',
										'choices' => array (
											'heading_1' => 'Heading 1',
											'heading_2' => 'Heading 2',
											'heading_3' => 'Heading 3',
											'heading_4' => 'Heading 4',
											'paragraph_text' => 'Paragraph text',
										),
										'default_value' => 'paragraph_text',
										'allow_null' => 0,
										'multiple' => 0,
									),
									array (
										'key' => 'field_527c5669815f5',
										'label' => __('Accordion'),
										'name' => 'accordion',
										'type' => 'repeater',
										'column_width' => '',
										'sub_fields' => array (
											array (
												'key' => 'field_527c5669815f6',
												'label' => __('Heading'),
												'name' => 'heading',
												'type' => 'text',
												'column_width' => 3,
												'default_value' => '',
												'placeholder' => '',
												'prepend' => '',
												'append' => '',
												'formatting' => 'html',
												'maxlength' => '',
											),
											array (
												'key' => 'field_527c5669815f7',
												'label' => __('Links'),
												'name' => 'links',
												'type' => 'repeater',
												'column_width' => '',
												'sub_fields' => array (
													array (
														'key' => 'field_527c56b5815f8',
														'label' => __('Text'),
														'name' => 'text',
														'type' => 'text',
														'column_width' => '',
														'default_value' => '',
														'placeholder' => '',
														'prepend' => '',
														'append' => '',
														'formatting' => 'html',
														'maxlength' => '',
													),
													array (
														'key' => 'field_527c56c7815f9',
														'label' => __('Text 2'),
														'name' => 'text_2',
														'type' => 'text',
														'column_width' => '',
														'default_value' => '',
														'placeholder' => '',
														'prepend' => '',
														'append' => '',
														'formatting' => 'html',
														'maxlength' => '',
													),
													array (
														'key' => 'field_527c5b1f3db92',
														'label' => __('Text 2 type'),
														'name' => 'text_2_type',
														'type' => 'select',
														'instructions' => __('Choose type for text 2'),
														'column_width' => '',
														'choices' => array (
															'text' => 'Text',
															'class' => 'Class',
															'url' => 'URL',
														),
														'default_value' => '',
														'allow_null' => 1,
														'multiple' => 0,
													),
												),
												'row_min' => '',
												'row_limit' => '',
												'layout' => 'row',
												'button_label' => 'Add Row',
											),
										),
										'row_min' => '',
										'row_limit' => '',
										'layout' => 'row',
										'button_label' => 'Add Item',
									),
								),
							),
							array (
								'label' => __('Accordion button'),
								'name' => 'accordion_button',
								'display' => 'row',
								'min' => '',
								'max' => '',
								'sub_fields' => array (
									array (
										'key' => 'field_527a7c756fb3b',
										'label' => __('Button text'),
										'name' => 'button_text',
										'type' => 'text',
										'column_width' => '',
										'default_value' => '',
										'placeholder' => '',
										'prepend' => '',
										'append' => '',
										'formatting' => 'html',
										'maxlength' => '',
									),
									array (
										'key' => 'field_527a7c866fb3c',
										'label' => __('Editor'),
										'name' => 'editor',
										'type' => 'text',
										'column_width' => '',
										'default_value' => '',
										'placeholder' => '',
										'prepend' => '',
										'append' => '',
										'formatting' => 'html',
										'maxlength' => '',
									),
								),
							),
							array (
								'label' => __('Youtube'),
								'name' => 'youtube',
								'display' => 'row',
								'min' => '',
								'max' => '',
								'sub_fields' => array (
									array (
										'key' => 'field_527a7c976fb3e',
										'label' => __('Heading'),
										'name' => 'heading',
										'type' => 'text',
										'column_width' => '',
										'default_value' => '',
										'placeholder' => '',
										'prepend' => '',
										'append' => '',
										'formatting' => 'html',
										'maxlength' => '',
									),
									array (
										'key' => 'field_527a7cb46fb3f',
										'label' => __('Video link'),
										'name' => 'video_link',
										'type' => 'text',
										'column_width' => '',
										'default_value' => '',
										'placeholder' => '',
										'prepend' => '',
										'append' => '',
										'formatting' => 'html',
										'maxlength' => '',
									),
									array (
										'key' => 'field_527a7cd26fb40',
										'label' => __('Video image'),
										'name' => 'video_image',
										'type' => 'image',
										'column_width' => '',
										'save_format' => 'object',
										'preview_size' => 'thumbnail',
										'library' => 'all',
									),
									array (
										'key' => 'field_527a7ce06fb41',
										'label' => __('Heading type'),
										'name' => 'heading_type',
										'type' => 'select',
										'column_width' => '',
										'choices' => array (
											'heading_1' => 'Heading 1',
											'heading_2' => 'Heading 2',
											'heading_3' => 'Heading 3',
											'heading_4' => 'Heading 4',
											'paragraph_text' => 'Paragraph text',
										),
										'default_value' => 'paragraph_text',
										'allow_null' => 0,
										'multiple' => 0,
									),
								),
							),
							array (
								'label' => __('Vimeo'),
								'name' => 'vimeo',
								'display' => 'row',
								'min' => '',
								'max' => '',
								'sub_fields' => array (
									array (
										'key' => 'field_527a7d156fb43',
										'label' => __('Heading'),
										'name' => 'heading',
										'type' => 'text',
										'column_width' => '',
										'default_value' => '',
										'placeholder' => '',
										'prepend' => '',
										'append' => '',
										'formatting' => 'html',
										'maxlength' => '',
									),
									array (
										'key' => 'field_527a7d156fb44',
										'label' => __('Video link'),
										'name' => 'video_link',
										'type' => 'text',
										'column_width' => '',
										'default_value' => '',
										'placeholder' => '',
										'prepend' => '',
										'append' => '',
										'formatting' => 'html',
										'maxlength' => '',
									),
									array (
										'key' => 'field_527a7d156fb45',
										'label' => __('Video image'),
										'name' => 'video_image',
										'type' => 'image',
										'column_width' => '',
										'save_format' => 'object',
										'preview_size' => 'thumbnail',
										'library' => 'all',
									),
									array (
										'key' => 'field_527a7d156fb46',
										'label' => __('Heading type'),
										'name' => 'heading_type',
										'type' => 'select',
										'column_width' => '',
										'choices' => array (
										),
										'default_value' => '',
										'allow_null' => 0,
										'multiple' => 0,
									),
								),
							),
							array (
								'label' => __('Map'),
								'name' => 'map',
								'display' => 'row',
								'min' => '',
								'max' => '',
								'sub_fields' => array (
									array (
										'key' => 'field_527d774989f16',
										'label' => __('Map'),
										'name' => 'map',
										'type' => 'google_map',
										'column_width' => '',
										'center_lat' => '',
										'center_lng' => '',
										'height' => '',
									),
									array (
										'key' => 'field_527d774989f17',
										'label' => __('Map height'),
										'name' => 'map_height',
										'type' => 'number',
										'instructions' => __('Please enter the map height'),
										'column_width' => 15,
										'default_value' => 300,
										'placeholder' => '',
										'prepend' => '',
										'append' => 'px',
										'min' => 50,
										'max' => '',
										'step' => '',
									),
									array (
										'key' => 'field_527d774989f18',
										'label' => __('Style ID'),
										'name' => 'style_id',
										'type' => 'text',
										'instructions' => __('This is the ID of the map style you desire an ID can be retrieved from http://maps.cloudmade.com/editor'),
										'column_width' => '',
										'default_value' => 1714,
										'placeholder' => '',
										'prepend' => '',
										'append' => '',
										'formatting' => 'html',
										'maxlength' => '',
									),
									array (
										'key' => 'field_527d774989f19',
										'label' => __('Zoom level'),
										'name' => 'zoom_level',
										'type' => 'number',
										'column_width' => '',
										'default_value' => 3,
										'placeholder' => '',
										'prepend' => '',
										'append' => '',
										'min' => 0,
										'max' => 18,
										'step' => '',
									),
									array (
										'key' => 'field_527d774989f1a',
										'label' => __('Markers'),
										'name' => 'markers',
										'type' => 'repeater',
										'column_width' => '',
										'sub_fields' => array (
											array (
												'key' => 'field_527d774989f1b',
												'label' => __('Location'),
												'name' => 'location',
												'type' => 'google_map',
												'column_width' => '',
												'center_lat' => '',
												'center_lng' => '',
												'height' => '',
											),
											array (
												'key' => 'field_527d774989f1c',
												'label' => __('Image'),
												'name' => 'image',
												'type' => 'image',
												'instructions' => __('Add caption and text to image view on maker'),
												'column_width' => '',
												'save_format' => 'object',
												'preview_size' => 'thumbnail',
												'library' => 'all',
											),
										),
										'row_min' => '',
										'row_limit' => '',
										'layout' => 'row',
										'button_label' => 'Add Marker',
									),
								),
							),
						),
						'button_label' => 'Add Content',
						'min' => '',
						'max' => '',
					),
				),
				'row_min' => '',
				'row_limit' => '',
				'layout' => 'row',
				'button_label' => 'Add Column',
			),
		),
		'location' => array (
			array (
				array (
					'param' => 'page_template',
					'operator' => '==',
					'value' => 'default',
					'order_no' => 0,
					'group_no' => 0,
				),
			),
		),
		'options' => array (
			'position' => 'normal',
			'layout' => 'no_box',
			'hide_on_screen' => array (
				0 => 'the_content',
			),
		),
		'menu_order' => 0,
	));
}
?>